### PR TITLE
Fix early return from YieldingSequenceBase#accumulate.

### LINKED ISSUE #9291: YieldingSequenceBase "accumulate" method returns too early sometimes
Specifically, when the Yielder returned by `toYielder(initValue, accumulator)` yields on its own, before `accumulator.accumulate` tells it to.

### PR DESCRIPTION
**Pull request by gianm**
Fixes #9291.

### CODE REVIEW

File: core/src/test/java/org/apache/druid/java/util/common/guava/LimitedSequenceTest.java [hunk 1]
```diff
@@ -25,45 +25,100 @@
...
+import java.util.Iterator;
 import java.util.List;
 import java.util.concurrent.atomic.AtomicLong;
 
 /**
+ *
  */
 public class LimitedSequenceTest
 {
+  private static final List<Integer> NUMS = Arrays.asList(0, 1, 2, 3, 4, 5, 6, 7, 8, 9);
```
Comment (ccaominh) [inline core/src/test/java/org/apache/druid/java/util/common/guava/LimitedSequenceTest.java]: Looks like this can also be used in `testNoSideEffects()`

**Comment by gianm** [comment]
By the way, for the record, I'm not sure if this bug has production impacts. I found it while working on some test cases for a different patch.
