### PR TITLE
fix bug with aggregator expressions on realtime index with string columns always producing 0 values

### LINKED ISSUE #8970: Expressions within aggregations can no longer use virtual columns
### Affected Version

0.15.0-incubating
0.15.1-incubating
0.16.0-incubating

### Description

Prior to 0.15.0, an expression within an aggregation could use a virtual column. In later versions it seems that a virtual column used within another expression will always evaluate to 0.

This was useful as it allowed expressions using _time to be evaluated once per segment (within a virtual column) rather than evaluating it every aggregation operation.

I'm still trying to decipher why but it looks like when the virtual column selector is loaded, the returned value is a "ArrayExprEval" which has a hardcoded value of 0 for asLong.

bit of a contrived example but to show what's changed

`{
  "dataSource" : "test",
  "intervals" : [
    "2019-11-01/2019-11-02"
  ],
  "granularity" : "all",
  "aggregations" : [
    {
      "type" : "longSum",
      "name" : "computed_value",
      "expression" : "1 + two"
    }
  ],
  "virtualColumns" : [
    {
      "name" : "two",
      "expression" : "2",
      "type" : "expression"
    }
  ],
  "queryType" : "timeseries"
}`

returns 

`[
    {
        "timestamp": "2019-11-01T00:00:00.000Z",
        "result": {
            "computed_value": 1574832721
        }
    }
]`

on 0.14.2

but 

`
[
    {
        "timestamp": "2019-11-01T00:00:00.000Z",
        "result": {
            "computed_value": 0
        }
    }
]
`
on 0.16.0

### PR DESCRIPTION
**Pull request by clintropolis**
Fixes #8970 (well it was already fixed somewhere along the way, but fixes another issue discovered in the comments)

### Description
This PR fixes an issue when using expression virtual columns that reference string values on realtime query segments, where an automatic transform to handle possible multi-valued string inputs forces array output from the selector, which the aggregators are not prepared to handle. See https://github.com/apache/druid/issues/8970#issuecomment-829762963 for details.

This PR adds a modification that fixes the side-effect of these transformations, to allow array typed `ExprEval` to provide scalar values if and only if the array has a single element. Otherwise it will retain its current behavior where methods like `getLong` and `getDouble` return default zero values. This changes makes array expression results mirror the the behavior of scalar expression results, where scalar expressions are currently allowed to present themselves as single element arrays (which exists to handle cases where array functions are used and the input value is a string column is multi-valued in one segment, but single valued in another).

This PR does not address an issue that could occur if legitimate multi-valued rows are processed that are not manipulated with explicit array functions and so are implicitly transformed. Since arrays larger than 1 will still return `0` for primitive value getters, expressions against these values should explicitly decide how to handle actual array inputs and combine them back into a scalar value that the primitive numeric aggregators can understand. Making this a failure condition seemed a bit drastic, but it might be worth considering.

This PR has:
- [x] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Review by bbecker-te — APPROVED** [review]
Looks good.
Too bad that there is so much special casing for each type, but I guess that cannot be avoided.

**Review by ggarcia-te — APPROVED** [review]
Looks good 👍🏼  Thanks for fixing the issue so quickly!

File: core/src/main/java/org/apache/druid/math/expr/ExprEval.java [hunk 1]
```diff
@@ -1025,6 +1034,54 @@ public ExprType type()
       return ExprType.LONG_ARRAY;
     }
 
+    @Override
+    public int asInt()
+    {
+      if (value != null && value.length == 1) {
+        if (value[0] == null) {
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/math/expr/ExprEval.java:1041]: nit: you can use `isNumericNull()`.

File: core/src/main/java/org/apache/druid/math/expr/ExprEval.java [hunk 2]
```diff
@@ -1148,6 +1283,66 @@ public ExprType type()
       return ExprType.STRING_ARRAY;
     }
 
+    @Override
+    public boolean isNumericNull()
+    {
+      if (value != null && value.length == 1) {
+        return computeNumber(value[0]) == null;
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/math/expr/ExprEval.java:1290]: `computeNumber` seems expensive. Since the caller pattern is likely calling this and then one of `asX()` method below, should we cache the result?

File: core/src/main/java/org/apache/druid/math/expr/ExprEval.java [hunk 3]
```diff
@@ -543,7 +543,18 @@ public String asString()
...
+   * If this method returns false, then the values returned by {@link #asLong()}, {@link #asDouble()},
+   * and {@link #asInt()} are "valid", since this method is primarily used during {@link Expr} evaluation to decide
+   * if primitive numbers can be fetched to use.
+   *
+   * If a type cannot sanely convert into a primitive numeric value, then this method should always return true so that
+   * these primitive numeric getters are not called, since returning false is assumed to mean these values are valid.
+   *
+   * Note that all types must still return values for {@link #asInt()}, {@link #asLong()}}, and {@link #asDouble()},
+   * since this can still happen if {@link NullHandling#sqlCompatible()} is false, but it should be assumed that this
+   * can only happen in that mode and 0s are typical and expected for values that would otherwise be null.
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/math/expr/ExprEval.java:557]: 👍

**Review by jihoonson — APPROVED** [review]
LGTM

**Comment by clintropolis** [comment]
thanks for review all :+1:
