### PR TITLE
Fix query-cancellation-executor memory leak

### LINKED ISSUE #15069: Druid Broker Heap memory increase until pod finally crash
### Affected Version

Version 25.0.0

### Description
- Cluster size : 3 brokers with the following configuration:
```yaml
Limits:
  cpu:     18
  memory:  82Gi
Requests:
  cpu:      9
  memory:   41Gi

DRUID_MAXDIRECTMEMORYSIZE: 32000m
DRUID_XMS: 24576m
DRUID_XMX: 49152m
JAVA_OPTS: -XX:+UseG1GC
druid_broker_http_numConnections: 30
druid_processing_buffer_sizeBytes: 1073741824
druid_processing_numMergeBuffers: 16
druid_processing_numThreads: 16
druid_query_groupBy_maxOnDiskStorage: 5242880000
druid_server_http_numThreads: 40
druid_sql_enable: true
druid_sql_planner_metadataSegmentCacheEnable: true
druid_sql_planner_useApproximateTopN: false
```

Faulty behaviour: 
Our druid-cluster-broker pods are automatically restarted due to outOfmemory java-heap memory and the pod restart because of OOMKilled error 137.

We observe the same behaviour on all our broker pods: the JVM heap memory increase slowly and after several days it reaches the limit and crashes:
image

For some reason, the broker is not able to reduce its memory consumption. The number of GC cycles increase and each GC cycle become slower. It looks like it becomes less and less efficient :
image

When we connect to the pods, we see a high number of thread processes with the type `query-cancellat`. This number of `query-cancellat` is slowly increasing until the pods finally crashes.

Here's an example of a thread:
```shell
4631 druid     0:00 {query-cancellat} /usr/lib/jvm/jdk-11.0.17+8/bin/java --add-exports=java.base/jdk.internal.misc=ALL-UNNAMED --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED 
--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/sun.nio.ch=ALL-UNNAMED --add-opens=jdk.management/com.sun.management.internal=ALL-UNNAMED 
-server -XX:+ExitOnOutOfMemoryError -Duser.timezone=UTC -Dfile.encoding=UTF-8 
-Djava.io.tmpdir=var/tmp -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager 
-Xmx49152m -Xms24576m -XX:MaxDirectMemorySize=32000m -XX:+UseG1GC -cp /tmp/conf/druid/cluster/_common:/tmp/conf/druid/cluster/query/broker:lib/*: 
org.apache.druid.cli.Main server broker
```

We set up a script that monitors the total number of thread and the number of thread of type `query-cancellat`in each broker pod:
image

*Note: the graph is the result of all broker pods cumulated*

=> In grey, we see that the number of thread of type `query-cancellat` is continuously increasing.  
=> Meanwhile, the number of thread of all other types is remaining stable (orange)  

**We suspect that this increase of the number of `query-cancellat` thread inside the broker pods might be the root cause of the pod crashes. Does anyone know why it is not able to remove its `query-cancellat` threads ?**

### PR DESCRIPTION
**Pull request by BartMiki**
Fixes #15069.

### Description

This PR fixes #15069 by resolving a memory leak caused by a thread leak in `query-cancellation-executor`.

#### Root of the bug
The problem was caused by removal of queryable server from a Broker list. Some of the servers have a DirectQueryRunner that creates `SingleThreadedScheduledExecutor`. In a case when native query was cancelled a thread would be created.

However, when the server was removed from the list we lost a reference to the server view that holds the runner that holds executor. When at least one query was cancelled, but the reference was lost, then the thread would be waiting infinitely, with no possibility to GC it.

There was no cleanup of the executor.

#### Solution

* Add `AutoClosable` to `QueryRunner` with default empty implementation - this way all functional interfaces implementation are still correct.
* Add timeout of 5 minutes to one of the `future.get` methods that were blocking indefinitely (and they were in our clients case) in `DruidDirectClient`.
* Implement `close` in `DruidDirectClient` that properly shuts down a thread pool.
* Invoke `close` in removal of the `QueryableDruidServer` from the `BrokerServerView`.

#### Reproducing

To reproduce this bug before the patch, we need to have a standard Druid cluster (for example `micro quickstart`) with one broker and one historical. We want to monitor Broker threads (for example with: `jconsol`). We need to have a command to spin up a second historical. Then the steps to reproduce are:

1. Execute a long running native query and cancel it - this should trigger creation of the `query-cancellation-executor` thread. There should be only _one_ thread now.
2. Start another historical.
3. Execute a long running native query and cancel it - there should be _two_ of these threads
4. Kill this 2nd historical - we still should have two threads on a list
5. Start 2nd historical again
6. Execute a long running native query and cancel it - there should be _three_ of these threads
7. Thread leak detected, as we have 2 historical nodes, but 3 threads.
8. Repeat kill, start, execute, cancel to get more threads.

#### Release note

Fixed: DirectDruidClient no longer leaks query-cancellation-executor threads after being removed by BrokerServerView.

<hr>

##### Key changed/added classes in this PR
 * `QueryRunner`
 * `DruidDirectClient`
 * `BrokerServerView`
 * `QueryableDruidServer`

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by abhishekagarwal87** [comment]
I am wondering if we even need an executor per data node. We might as well have a common thread pool for query cancellations. What do you think?

**Comment by BartMiki** [comment]
@abhishekagarwal87 
Yes, that is also a great idea just to have a single executor that is shared. The question is, how much threads should it have? There is for example: `LoadedSegmentDataProviderFactory` that also have `query-cancellation-executor` (but different one):
```java
private static final int DEFAULT_THREAD_COUNT = 4;
...
this.queryCancellationExecutor = ScheduledExecutors.fixed(DEFAULT_THREAD_COUNT, "query-cancellation-executor");
```
So my ideas are:

1. extend `DirectDruidClientFactory` with predefined `this.queryCancellationExecutor` with fix number of threads (e.g. 4 like there) or inject it from outside (as `DirectDruidClientFactory` has inject annotation) and pass it to the `DirectDruidClient` as argument
2. Extract this `queryCancellationExecutor` from both places, create it in a single place (with Druid configuration for number of threads) and inject it in both Factories

I guess the idea 1. is easier and adheres to the pattern that was already present with `LoadedSegmentDataProviderFactory`.

**Comment by abhishekagarwal87** [comment]
idea 1 works. You could also make it 
`Math.max(1, JvmUtils.getRuntimeInfo().getAvailableProcessors() / 2);` so the value scales with broker hardware capacity.

**Comment by BartMiki** [comment]
@abhishekagarwal87 
I push the changes. I also made Factory a LazySingleton, as there should be only one instance of it anyway.

**Comment by BartMiki** [comment]
@abhishekagarwal87 Hi! I see that some tests failed, so I checked if there is already a code change in the master that fixes these tests. I did not change the classes that work with these tests. However, when I check out the current master, these tests also don't work. It is easy to fix them, but I wonder if I should too that in this PR?

It is this [test](https://github.com/apache/druid/blob/959148ad370f4133c59f24f8afc3f297b0911e41/server/src/test/java/org/apache/druid/discovery/BrokerClientTest.java#L104). It doesn't work, because the server sends 504 [here](https://github.com/apache/druid/blob/959148ad370f4133c59f24f8afc3f297b0911e41/server/src/test/java/org/apache/druid/discovery/BrokerClientTest.java#L150) and the [sendQuery](https://github.com/apache/druid/blob/96be82a3e67bb3fdb62d0640c0c8885f7f5813b0/server/src/main/java/org/apache/druid/discovery/BrokerClient.java#L78) fails using retry utils, because it returns `DruidException` which is `RuntimeException`, but recovery is only supported for `IOE` or `ExecutionException` (if cause is `IOException` or `ChannelException`)

File: server/src/main/java/org/apache/druid/client/DirectDruidClient.java [hunk 1]
```diff
@@ -551,7 +553,7 @@ private void cancelQuery(Query<T> query, String cancelUrl)
             if (!responseFuture.isDone()) {
               log.error("Error cancelling query[%s]", query);
             }
-            StatusResponseHolder response = responseFuture.get();
+            StatusResponseHolder response = responseFuture.get(5, TimeUnit.SECONDS);
```
Comment (abhishekagarwal87) [inline server/src/main/java/org/apache/druid/client/DirectDruidClient.java:556]: Should we set it to 30? I don't have a strong opinion but 5 seems low.

File: processing/src/main/java/org/apache/druid/query/QueryRunner.java [hunk 2]
```diff
@@ -31,7 +31,7 @@ public interface QueryRunner<T>
    * Runs the given query and returns results in a time-ordered sequence.
    */
   Sequence<T> run(QueryPlus<T> queryPlus, ResponseContext responseContext);
-  
+
```
Comment (abhishekagarwal87) [inline processing/src/main/java/org/apache/druid/query/QueryRunner.java:34]: could revert this change completely.

**Review by abhishekagarwal87 — COMMENTED** [review]
LGTM. Few minor comments.

**Comment by BartMiki** [comment]
@abhishekagarwal87 
Yes, these jobs:
- https://github.com/apache/druid/actions/runs/7746436332/job/21125153021?pr=15754
- https://github.com/apache/druid/actions/runs/7746436332/job/21125151871?pr=15754
- https://github.com/apache/druid/actions/runs/7746436332/job/21127176318?pr=15754
- https://github.com/apache/druid/actions/runs/7746436332/job/21127178283?pr=15754

File: processing/src/main/java/org/apache/druid/query/QueryRunner.java (hunk 2 above)
Comment (BartMiki) [reply processing/src/main/java/org/apache/druid/query/QueryRunner.java:34]: sure, done

File: server/src/main/java/org/apache/druid/client/DirectDruidClient.java (hunk 1 above)
Comment (BartMiki) [reply server/src/main/java/org/apache/druid/client/DirectDruidClient.java:556]: yes, make sense, let me set to 30 then

Comment (BartMiki) [reply server/src/main/java/org/apache/druid/client/DirectDruidClient.java]: done

**Comment by BartMiki** [comment]
So should I fix this test? 

Also, the code coverage for the TimeoutException is a bit tricky as it is so nested that it is hard to test. 
I'm thinking about refactoring this logic into a separate class that is easier to test. 
That would also improve the readability of the existing code. What do you think @abhishekagarwal87 ?

**Comment by abhishekagarwal87** [comment]
@BartMiki - Go ahead. I am going to merge this patch for now.

**Comment by abhishekagarwal87** [comment]
Yeah. Meanwhile can you also fix the intellij inspection failure - https://github.com/apache/druid/actions/runs/7810988879/job/21305295805?pr=15855#step:5:18154 
I was too quick in merging the PR :|

**Comment by BartMiki** [comment]
@abhishekagarwal87 One more question regarding the test. So the result is that:
```
Warning:  Flakes: 
Warning:  org.apache.druid.discovery.BrokerClientTest.testError
Error:    Run 1: BrokerClientTest.testError:121 » Druid Request to broker failed due to failed response status: [504 ]
Error:    Run 2: BrokerClientTest.testError:121 » Druid Request to broker failed due to failed response status: [504 ]
Error:    Run 3: BrokerClientTest.testError:121 » Druid Request to broker failed due to failed response status: [504 ]
[INFO]   Run 4: PASS
```
so the test actually passes, but it is flaky. So it works, but it does not use the RetryUtils here. The actual failure was this line coverage. So I wonder if I should fix this test to rely on RetryUtils or just leave it as it is.

**Comment by OliveBZH** [comment]
Hello, thanks for the resolution, can you confirm that it will be part of the 29.0 milestone ?

**Comment by BartMiki** [comment]
@OliveBZH Good question. When I forked that, the Druid master had version 30.0.0-SNAPSHOT ([exact line](https://github.com/deep-bi/druid/blob/6e8a9eda351143b0306219d9b70d6fffc9c46a4c/pom.xml#L32) from my branch). So I assume that is not a part of 29.0.0.
