### PR TITLE
Fix ingestion failure of pretty-formatted JSON message

### LINKED ISSUE #10259: Kafka ingestion fails to parse multiple-line messages in 0.19
### Affected Version

- 0.17
- 0.18
- 0.19

### Description

There's a topic in our kafka cluster, which contains messages in **pretty** JSON format as below. The newest 0.19 fails to parse these messages as JSON objects while 0.16 works fine.

JSON example

```
{
        "byteCount":0,
        "partition":0,
        "recordAge":0,
        "recordCount":0,
        "replicationLatency":0,
        "targetCluster":"dst",
        "timestamp":1597045440490,
        "topic":"test"
}
```

0.16

image
image

0.19
image
image

after changing `Input Format` from default `Regex` to `Json`, following error appears.

image

# Reason

After diving into the code between 0.16 and 0.19, I found the problem is caused by `JsonReader` which was introduced in 0.17 by #8823

The new `JsonReader` inherits from `TextReader` which uses `LineIterator` to split the input string and return text LINE BY LINE instead of the whole text.

So for multiple-line json text, this implementation fails to parse the text as JSON object.

https://github.com/apache/druid/blob/e2487bcc30c5ac0f4281ddd2dcf8906dcd00cba8/core/src/main/java/org/apache/druid/data/input/TextReader.java#L57

# How to fix

Maybe `JsonReader` should override the `intermediateRowIterator` function defined in `TextReader` to return an iterator with only one string object.

@jihoonson please check this bug if you're convenient :)

### PR DESCRIPTION
**Pull request by FrankChen021**
This PR fixes #10259 . 

### Description

The cause and solution has been discussed completely in the issue. 

In this PR, 

1. a new `JsonReader` is provided to read json text for streaming ingestion
2. original `JsonReader` is renamed to `JsonLineReader` for batch ingestion

<hr>

This PR has:
- [X] been self-reviewed.
- [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [X] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [X] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by FrankChen021** [comment]
CI reports some failures of integration tests, I'll check it later

**Comment by FrankChen021** [comment]
Once a json text line is ill-formed, the `next` call on iterator returned by `ObjectMapper.readValues` throws exception, and it seems we have no opportunity to process the rest lines. This is case why some old test cases fail. 

I don't know whether jackson provides anyway to skip the ill-formed text, but I guess there's no such API for a parser.
So what's your suggestion on this problem ? @gianm @jihoonson

**Comment by gianm** [comment]
> I don't know whether jackson provides anyway to skip the ill-formed text, but I guess there's no such API for a parser.
> So what's your suggestion on this problem ? @gianm @jihoonson

Hmm, this is definitely a problem. When we're reading JSON from a file, we should be skipping the "lines" that aren't parseable, and marking them as unparseable. I guess that ObjectMapper API was too good to be true 🙂

Maybe we can do one of the following two things.

Option 1: After an error we can manually skip to the line that starts with `{` and begin parsing there. Because the JsonParser has a buffer, we need to make sure we don't miss buffered but unparsed content. We might be able to do that with the `JsonParser.releaseBuffered` method, assuming it works properly after an error.

Option 2: Introduce a `lineSplittable` parameter for the JsonReader like you originally suggested, but it would behave differently in two ways. First: it wouldn't be available on the JsonInputFormat. Instead, it would be automatically set to `true` for batch ingestion and `false` for streaming ingestion. Second: `false` doesn't mean "not line splittable", it just means "we should auto detect". In the `true` case (batch ingestion), the JsonReader will split on lines and parse each line individually. Batch ingestion won't support pretty-printed input, but it never did in the past, and it doesn't seem likely that it's a common requirement anyway. In the `false` case (streaming ingestion), the JsonReader would use the ObjectMapper.readValues API, and it would support all these different kinds of payloads. But if there's an error, it would reject the entire payload. That all-or-nothing behavior seems OK for a streaming ingestion use case.

**Comment by jihoonson** [comment]
@FrankChen021 good catch. The option 2 among @gianm's suggestions sounds better to me. The option 1 sounds hard to actually implement since there will be lots of edge cases we should handle.

Regarding integration tests, I think it would depend on what this PR is going to change. If it needs to modify some behavior in interaction between supervisor and tasks (for example, if the supervisor should set the `lineSplittable` flag properly), we need some. If the change can be contained only on the task side, I think adding some new unit tests in `KafkaIndexTask` would be enough. @suneet-s what do you think?

**Comment by FrankChen021** [comment]
@gianm @jihoonson Thanks for the suggestions. Option 2 is much easier for us to control. As a parameter is introduced on JsonInputFormat, to make the code easy to maintain, there will be two json reader classes named as `JsonReader` and `JsonLineReader`. The former one is the one which directly inherits `InputEntityReader` and uses `ObjectMapper.readValues` to parse input text. And `JsonLineReader` is renamed from the orignal `JsonReader` which inherits `TextReader` to process json line by line.

**Comment by jihoonson** [comment]
@FrankChen021 it sounds good to me :slightly_smiling_face:

File: core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java [hunk 1]
```diff
@@ -49,41 +55,99 @@
...
-  }
 
   @Override
-  public Map<String, Object> toMap(String intermediateRow) throws IOException
+  public CloseableIterator<InputRow> read() throws IOException
   {
-    //noinspection unchecked
-    return mapper.readValue(intermediateRow, Map.class);
+    final MappingIterator<JsonNode> delegate = mapper.readValues(
+        new JsonFactory().createParser(this.source.open()),
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java:69]: The `parser` created from `JsonFactory` is `Closeable` which should be closed when the below `CloseableIterator` is closed.

**Comment by FrankChen021** [comment]
Marked as WIP temporarily.

`JsonReader.hasNext`, which calls the jackson's `MappingIterator.hasNext`, throws exception when a json text is ill-formed, this causes some old test cases on `sample` to fail while test cases on `read` are successfully passed. This is because stream ingestion handle each record one by one, and if one fails to parse the json next, the exception is caught and handled gracefully, while `sample` treats all records as a whole if one record fails, the sample process aborts.

It would take some time to handle this problem.

**Comment by jihoonson** [comment]
@FrankChen021 hmm, do you think it would be better to change the behavior of the sampler? Maybe its behavior should match with the actual data reader.

**Comment by FrankChen021** [comment]
@jihoonson I intended to do that, but after some deep investigation of original implementation, I found that it was not the root cause of previous problem. As a result, exception handling in the new `JsonReader.sample` was improved, as the way it did in `IntermediateRowParsingReader`,  to eliminate the failure of test cases. So neither test cases nor sample and ingestion behaviors were modified to adapt to this PR.

The PR is now ready for review. I would like hear your voices with regarding to the pass of value of `lineSplittable` parameter,  which I think there should be a more graceful way.

File: core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java [hunk 2]
```diff
@@ -33,13 +40,98 @@
...
+ * 1. a JSON string of an object in a line or multiple lines(such as pretty-printed JSON text)
+ * 2. multiple JSON object strings concated by white space character(s)
+ *
+ * For case 2, what should be noticed is that if an exception is thrown when parsing one JSON string,
+ * the rest JSON text will all be ignored
+ *
+ * For more information, see: https://github.com/apache/druid/pull/10383
+ * </pre>
+ */
+public class JsonReader implements InputEntityReader
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java:62]: Thinking about this new reader, I think the new requirement for parsing multiple JSON objects to multiple rows doesn't fit in the current interface of the sampler. The sampler currently assumes that _there is only one JSON object in an input chunk_ which could have either an array or a nested object. That means, the current interface allows multiple out rows as `inputRows` is a list of `InputRow`s in `InputRowListPlusRawValues`, but doesn't allow multiple values in an input chunk as `rawValues` is a map in `InputRowListPlusRawValues`. To support the requirement, I think `rawValues` should be a list of map, so that all raw values in an input chunk can be returned to the sampler.

If we do this, `JsonReader` can simply extend `IntermediateRowParsingReader`, where the intermediate row will be the [`inputText` created from `source.open()`](https://github.com/apache/druid/pull/10383/files#diff-cc591396000acab135e9bd4aa1f31e2aR72). Here is an example.

```java
public class JsonReader2 extends IntermediateRowParsingReader<String>
{
  private final ObjectFlattener<JsonNode> flattener;
  private final ObjectMapper mapper;
  private final InputEntity source;
  private final InputRowSchema inputRowSchema;

  JsonReader2(
      InputRowSchema inputRowSchema,
      InputEntity source,
      JSONPathSpec flattenSpec,
      ObjectMapper mapper,
      boolean keepNullColumns
  )
  {
    this.inputRowSchema = inputRowSchema;
    this.source = source;
    this.flattener = ObjectFlatteners.create(flattenSpec, new JSONFlattenerMaker(keepNullColumns));
    this.mapper = mapper;
  }

  @Override
  protected CloseableIterator<String> intermediateRowIterator() throws IOException
  {
    return CloseableIterators.withEmptyBaggage(
        Iterators.singletonIterator(IOUtils.toString(source.open(), StringUtils.UTF8_STRING))
    );
  }

  @Override
  protected List<InputRow> parseInputRows(String intermediateRow) throws IOException, ParseException
  {
    try (JsonParser parser = new JsonFactory().createParser(intermediateRow)) {
      final Iterator<JsonNode> delegate = mapper.readValues(parser, JsonNode.class);
      return FluentIterable.from(() -> delegate)
                           .transform(jsonNode -> MapInputRowParser.parse(inputRowSchema, flattener.flatten(jsonNode)))
                           .toList();
    }
  }

  @Override
  protected List<Map<String, Object>> toMap(String intermediateRow) throws IOException
  {
    try (JsonParser parser = new JsonFactory().createParser(intermediateRow)) {
      final Iterator<Map> delegate = mapper.readValues(parser, Map.class);
      return FluentIterable.from(() -> delegate).transform(map -> (Map<String, Object>) map).toList();
    }
  }
}
```

File: core/src/main/java/org/apache/druid/data/input/ExceptionThrowingIterator.java [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+package org.apache.druid.data.input;
+
+import org.apache.druid.java.util.common.parsers.CloseableIterator;
+
+public class ExceptionThrowingIterator<T> implements CloseableIterator<T>
```
[the remark this answers is not in the document]
Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/ExceptionThrowingIterator.java:24]: If `JsonReader` extends `IntermediateRowParsingReader`, this class will not have to be extracted.

File: core/src/main/java/org/apache/druid/data/input/impl/JsonInputFormat.java [hunk 4]
```diff
@@ -73,7 +88,14 @@ public boolean isSplittable()
   @Override
   public InputEntityReader createReader(InputRowSchema inputRowSchema, InputEntity source, File temporaryDirectory)
   {
-    return new JsonReader(inputRowSchema, source, getFlattenSpec(), objectMapper, keepNullColumns);
+    return this.lineSplittable ?
+           new JsonLineReader(inputRowSchema, source, getFlattenSpec(), objectMapper, keepNullColumns) :
+           new JsonReader(inputRowSchema, source, getFlattenSpec(), objectMapper, keepNullColumns);
+  }
+
+  public void setLineSplittable(boolean lineSplittable)
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/impl/JsonInputFormat.java:96]: This doesn't look pretty, but simple enough to handle this exceptional case. Maybe we can introduce another layer on top of inputFormat to make it more pretty, but I don't think it will be worth at least at this point.

**Review by jihoonson — COMMENTED** [review]
@FrankChen021 thanks for the update. I think there is an assumption in the sampler design which should be modified to support the new requirement for parsing multiple JSON objects in an input chunk. I left more detailed comments in line.

File: core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java (hunk 2 above)
Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java:62]: > The sampler currently assumes that there is only one JSON object in an input chunk which could have either an array or a nested object. 

That's the root cause why `ExceptionThrowingIterator` is extracted and `JsonReader` inherits from InputEntityReader directly.

Your suggestion provides a new and simple way to deal with it. I'll test the code later.

File: core/src/main/java/org/apache/druid/data/input/ExceptionThrowingIterator.java [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+  @Override
+  public boolean hasNext()
+  {
+    return !thrown;
+  }
+
+  @Override
+  public T next()
+  {
+    thrown = true;
```
[the remark this answers is not in the document]
Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/data/input/ExceptionThrowingIterator.java:46]: I don't know why SpotBugs didn't report the problem before this class is extracted. But if we adopt the solution that makes `JsonReader` inherit `IntermediateRowParsingReader` as you suggest, this modification should be rollback and  I'll check it again if the report of this bug is still there

**Comment by FrankChen021** [comment]
@jihoonson The patch has been submitted. The change of signature of `IntermediateRowParsingReader#toMap` involves changes on all existing subclasses, which are reported insufficient branch or line coverage by CI.

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java [hunk 6]
```diff
@@ -96,23 +99,35 @@ public void close() throws IOException
...
+        return Collections.singletonList(InputRowListPlusRawValues.of(rawColumnsList.isEmpty() ? null : rawColumnsList.get(0), e));
       }
       catch (IOException e) {
-        return InputRowListPlusRawValues.of(rawColumns, new ParseException(e, "Unable to parse row [%s] into inputRow", row));
+        return Collections.singletonList(InputRowListPlusRawValues.of(rawColumnsList.isEmpty() ? null : rawColumnsList.get(0),
+                                                                      new ParseException(e, "Unable to parse row [%s] into inputRow", row)));
+      }
+
+      List<InputRowListPlusRawValues> list = new ArrayList<InputRowListPlusRawValues>();
+      for (int i = 0; i < Math.min(rows.size(), rawColumnsList.size()); i++) {
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java:125]: I think we should check if the sizes of `rawColumnsList` and `rows` are same (as in the Javadoc contract) instead of computing a min of them.

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java [hunk 7]
```diff
@@ -96,23 +99,35 @@ public void close() throws IOException
...
       }
+
+      List<InputRow> rows;
       try {
-        return InputRowListPlusRawValues.of(parseInputRows(row), rawColumns);
+        rows = parseInputRows(row);
       }
       catch (ParseException e) {
-        return InputRowListPlusRawValues.of(rawColumns, e);
+        return Collections.singletonList(InputRowListPlusRawValues.of(rawColumnsList.isEmpty() ? null : rawColumnsList.get(0), e));
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java:117]: Should we return the entire `rawColumnsList` instead of the first element? I thought `InputRowListPlusRawValues` will be able to have a list of `rawColumns`.

Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java:117]: Also, should we fail if `rawColumnsList.isEmpty()`?

File: core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java [hunk 8]
```diff
@@ -49,41 +73,57 @@
...
-  }
+    try (JsonParser parser = new JsonFactory().createParser(intermediateRow)) {
+      final Iterator<JsonNode> delegate = mapper.readValues(parser, JsonNode.class);
+      return FluentIterable.from(() -> delegate)
+                           .transform(jsonNode -> MapInputRowParser.parse(inputRowSchema, flattener.flatten(jsonNode)))
+                           .toList();
+    }
+    catch (RuntimeException e) {
+      //convert Jackson's JsonParseException into druid's exception for further processing
+      if (e.getCause() instanceof JsonParseException) {
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/impl/JsonReader.java:101]: Where is `JsonParseException` thrown wrapped in `RuntimeException`? Can you add a comment about it?

File: core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java [hunk 9]
```diff
@@ -69,7 +69,7 @@ public void testEquals()
               new ObjectMapper(),
               new ObjectMapper()
               )
-              .withIgnoredFields("objectMapper")
+              .withIgnoredFields("objectMapper", "lineSplittable")
```
Comment (jihoonson) [inline core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java:72]: `lineSplittable` shouldn't be ignored, but included in `equals()` and `hashCode()`.

**Review by jihoonson — COMMENTED** [review]
> @jihoonson The patch has been submitted. The change of signature of `IntermediateRowParsingReader#toMap` involves changes on all existing subclasses, which are reported insufficient branch or line coverage by CI.

@FrankChen021 thanks! I left some more comments. For the CI failure, I think we can ignore the test coverage bot for the interface change. However, it seems like there are missing branches in `IntermediateRowParsingReader` and the new `JsonReader` as well. Can you please check it?

```
Diff coverage statistics:
------------------------------------------------------------------------------
|     lines      |    branches    |   functions    |   path
------------------------------------------------------------------------------
| 100% (5/5)     | 100% (2/2)     |  95% (19/20)   | org/apache/druid/data/input/impl/JsonInputFormat.java
|  77% (17/22)   |  25% (1/4)     |  94% (49/52)   | org/apache/druid/data/input/impl/JsonReader.java
|  81% (9/11)    | 100% (0/0)     |  90% (58/64)   | org/apache/druid/data/input/impl/JsonLineReader.java
|   0% (0/1)     | 100% (0/0)     |  50% (1/2)     | org/apache/druid/data/input/impl/DelimitedValueReader.java
|   0% (0/1)     | 100% (0/0)     | 100% (2/2)     | org/apache/druid/data/input/impl/RegexReader.java
|  72% (8/11)    |  33% (2/6)     |  62% (5/8)     | org/apache/druid/data/input/IntermediateRowParsingReader.java
|   0% (0/1)     | 100% (0/0)     |  50% (1/2)     | org/apache/druid/data/input/avro/AvroOCFReader.java
|   0% (0/1)     | 100% (0/0)     |   0% (0/1)     | org/apache/druid/data/input/orc/OrcReader.java
| 100% (1/1)     | 100% (0/0)     | 100% (1/1)     | org/apache/druid/data/input/parquet/ParquetReader.java
------------------------------------------------------------------------------
Total diff coverage:
 - lines: 74% (40/54)
 - branches: 41% (5/12)
 - functions: 89% (136/152)
ERROR: Insufficient branch coverage of 41% (5/12). Required 50%.
```

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java (hunk 7 above)
Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java]: To return the entire `rawColumnsList` here involves changes on `InputRowListPlusRawValues` which are heavily used by test cases. 

I checked the code again and find that there's no need to return raw column object when exception occurs. Because `InputSourceSample` re-throws exception once `InputRowListPlusRawValues.getParseException` returns exception.  

So the new commit passes a `null` to `InputRowListPlusRawValues` to eliminate this strange code here.

File: core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java (hunk 9 above)
Comment (FrankChen021) [reply core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java]: The new property `lineSplittable` is not declared as `final` and `EqualsVerifier` here will report a warning that `equals depends on mutable field`, so the new commit calls `suppress` method on `EqualsVerifier` to suppress this warning.

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java (hunk 7 above)
Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java]: > I checked the code again and find that there's no need to return raw column object when exception occurs. Because `InputSourceSample` re-throws exception once `InputRowListPlusRawValues.getParseException` returns exception.

[Actually, there is a clause catching `ParseException`](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java#L142-L146) in the sampler (this is a bad pattern by the way. We should refactor it at some point). In this case, the `rawColumns` is returned to show the raw data in the UI. I think the entire `rawColumnsList` should be returned to keep the current behaviour.

File: core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java (hunk 9 above)
Comment (jihoonson) [reply core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java]: Hmm, good point. Yeah, it's not a good convention to include a mutable field in `equals()` or `hashCode()` because they can be used as a key of a `HashMap` or `HashSet`. I would like to suggest to make `lineSplittable` immutable, but add a new method `withLineSplittable(boolean lineSplittable)` instead of `setLineSplittable()` which creates a new `JsonInputFormat` instance with the given value.

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java (hunk 7 above)
Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java]: There are some test failing in `InputSourceSamplerTest`. It seems like because of this change.

File: core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java (hunk 9 above)
Comment (FrankChen021) [reply core/src/test/java/org/apache/druid/data/input/impl/JsonInputFormatTest.java]: Good idea!

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java (hunk 7 above)
Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java]: It's been fixed. Now it's ready for final review.

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java [hunk 10]
```diff
@@ -96,23 +101,45 @@ public void close() throws IOException
...
       }
       catch (ParseException e) {
-        return InputRowListPlusRawValues.of(rawColumns, e);
+        return rawColumnsList.stream().map(rawColumn -> InputRowListPlusRawValues.of(rawColumn, e)).collect(Collectors.toList());
       }
       catch (IOException e) {
-        return InputRowListPlusRawValues.of(rawColumns, new ParseException(e, "Unable to parse row [%s] into inputRow", row));
+        ParseException exception = new ParseException(e, "Unable to parse row [%s] into inputRow", row);
+        return rawColumnsList.stream().map(rawColumn -> InputRowListPlusRawValues.of(rawColumn, exception)).collect(Collectors.toList());
+      }
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java:129]: This doesn't still seem correct to me.. The purpose of returning `rawColumn` and `exception` in `InputRowListPlusRawValues` is showing them in the sampler altogether, so that users will debug their data and input format easily. To do that, we should show exactly what the data was when a `ParseException` is thrown. Now, thinking about the new behavior parsing a list of JSONs into `InputRow`s, `row` will contain the list of JSONs here. If a `ParseException` was thrown while parsing one of them, we should return one `InputRowListPlusRawValues` which contains `row` (the whole list of JSONs) and the exception because we don't know exactly in which JSON in the list the `ParseException` was thrown from. For this, I still think we should change `rawValues` in `InputRowListPlusRawValues` to be `List<Map<String, Object>>`. I understand that you don't want to touch it as it is widely used in unit tests, but I'm not sure if we can fix this without touching it.

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java [hunk 11]
```diff
@@ -96,23 +101,45 @@ public void close() throws IOException
...
+
+      if (rows.size() != rawColumnsList.size()) {
+        return Collections.singletonList(InputRowListPlusRawValues.of(null,
```
Comment (jihoonson) [inline core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java:132]: I think we should set both `rows` and `rawColumnsList` in `InputRowListPlusRawValues` in this case, so that users will learn how they are different.

**Review by jihoonson — COMMENTED** [review]
Hi @FrankChen021, thank you for your patience. I think we are almost there. Please check my last comments. 

BTW, now there is only one CI failure:

```
Diff coverage statistics:
------------------------------------------------------------------------------
|     lines      |    branches    |   functions    |   path
------------------------------------------------------------------------------
|   0% (0/1)     | 100% (0/0)     | 100% (1/1)     | org/apache/druid/metadata/input/SqlReader.java
------------------------------------------------------------------------------
Total diff coverage:
 - lines: 0% (0/1)
 - branches: 100% (0/0)
 - functions: 100% (1/1)
ERROR: Insufficient line coverage of 0% (0/1). Required 50%.
```

This is because of the interface change you made for sampler, which means the unit test is missing for sampler for SqlReader. I know the missing test is not your fault, but would you mind adding one? It would be pretty straightforward. You can add one in `SqlInputSourceTest` by mostly replicating `testSingleSplit()`. All you need to modify are calling `sqlReader.sample()` instead of `read()` and verifying `InputRowListPlusRawValues`s insead of `InputRow`s. But I totally understand even if you don't want to do it in this PR.

File: core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java (hunk 10 above)
Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java:129]: I agree with you. 

`rawValues` in `InputRowListPlusRawValues` should also be a list to correspond the list of `inputRows`. Since the `rawValues` is also passed to `SamplerResponseRow` when exception occurs, to change `rawValues` from `Map` to `List<Map>` also involves changes of the web console. I don't know if the change of front-end should also be included in this PR.

Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/IntermediateRowParsingReader.java:129]: Good point. I'm not sure if we have a unit test for parsing sampler response. If we have, the CI will fail and we need to fix it in this PR together. Otherwise, I'm OK with doing the fix in a follow-up. @vogievetsky do you know whether or not we have such a unit test?

**Comment by FrankChen021** [comment]
The branch has been rebased on master because there're some conflicts with it.

@jihoonson  Here're some explanation on the latest changes

1st, a new method `InputRowListPlusRawValues`.`ofList` is added to create instance of that class by passing list of raw column and rows, while the old `of` methods are still kept mainly for no changes on old code;

2nd `InputRowListPlusRawValues`.`getRawValues` is still kept without involving lots of changes on test cases;

3rd, there's no changes made on existing `SamplerResponse` interface. All data returned are still row by row. I think keeping this interface contract is reasonable, because its inner container `SamplerResponseRow` is already a pair of `rawColumn` and parsed json map.

File: indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java [hunk 12]
```diff
@@ -131,17 +130,27 @@ public SamplerResponse sample(
...
             numRowsIndexed++;
           }
         }
         catch (ParseException e) {
-          responseRows[counter] = new SamplerResponseRow(rawColumns, null, true, e.getMessage());
-          counter++;
+          if (rawColumnsList != null) {
+            responseRows.addAll(rawColumnsList.stream()
+                                              .map(rawColumns -> new SamplerResponseRow(rawColumns, null, true, e.getMessage()))
+                                              .collect(Collectors.toList()));
```
Comment (jihoonson) [inline indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java:150]: Can this introduce duplicate rows in `responseRows`? Suppose you have 3 rawColumns in `rawColumnsList` including an unparseable row at the second position. The first row will be added to both `index` and thus a new `SamplerResponseRow` of the first `rawColumns` will be added to `responseRows`. But for the second row, `index.add()` will throw a `ParseException` which will execute these lines. In this case, 2 duplicate `rawColumns` of the first row will be added in `responseRows`.

Looking at [what `JsonReader` does](https://github.com/apache/druid/pull/10383/files#diff-c745a28591c789098f0a9efd75769ad242b6c40379d155fc61143ed63dccc995R93-R108), it seems throwing away the whole `intermediateRow` when there is any unparseable row. The sampler behavior should match to the actual ingestion.

**Review by jihoonson — COMMENTED** [review]
@FrankChen021 thanks, sounds good! I reviewed the latest change, but have a concern with potential duplicate rows in the sampler result.

File: core/src/main/java/org/apache/druid/data/input/InputRowListPlusRawValues.java [hunk 13]
```diff
@@ -82,8 +121,16 @@ private InputRowListPlusRawValues(
     return inputRows;
   }
 
+  /**
+   * This method is left here only for test cases
+   */
   @Nullable
   public Map<String, Object> getRawValues()
+  {
+    return CollectionUtils.isNullOrEmpty(rawValues) ? null : rawValues.get(0);
```
[the remark this answers is not in the document]
Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/data/input/InputRowListPlusRawValues.java:130]: But `Iterables.getOnlyElement` does not check whether the given input is null or not. If the given input is null, there will be a NPE.

File: indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java (hunk 12 above)
Comment (FrankChen021) [reply indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java]: I notice that `index.add` does not throw `ParseException` but returns the exception in its returning result. The previous version of `InputSourceSampler` checks the result to rethrow this exception, while the [change](https://github.com/apache/druid/pull/10336/files#diff-a35198e960bc90b96d559e9ea93be1d4de52655e9a4f04016173114952ae0001) introduced by #10336 deletes these exception related code, which means the code here won't throw ParseException.

Of course, there's possibility that the code in for-loop throws `ParseException` in future. I've made little changes to avoid this potential situation to happen. Let's check it once the CI passes. 

BTW, my local branch has failed to build since last time it was rebased on master, I have to reply on the CI to check if there're any test case failures.

Comment (jihoonson) [reply indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java]: > I notice that `index.add` does not throw `ParseException` but returns the exception in its returning result. The previous version of `InputSourceSampler` checks the result to rethrow this exception, while the [change](https://github.com/apache/druid/pull/10336/files#diff-a35198e960bc90b96d559e9ea93be1d4de52655e9a4f04016173114952ae0001) introduced by #10336 deletes these exception related code, which means the code here won't throw ParseException.
> 
> Of course, there's possibility that the code in for-loop throws `ParseException` in future. I've made little changes to avoid this potential situation to happen. Let's check it once the CI passes.

Oops, good point. I forgot what I have done in #10336.. I think `index.add()` should never throw parseException directly, but return them in `IncrementalIndexAddResult`. We can add this contract on the Javadoc of `IncrementalIndex.add()`. I suggest removing the `catch` clause here to avoid future confusion (there is no point in catching exceptions which cannot be thrown here).

File: core/src/main/java/org/apache/druid/data/input/InputRowListPlusRawValues.java (hunk 13 above)
[the remark this answers is not in the document]
Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/InputRowListPlusRawValues.java:130]: I meant, for `rawValues.get(0)` to make sure there is only one element in there if this method is called.

**Comment by jihoonson** [comment]
@FrankChen021 thanks. I left my last comments. Everything else looks good to me.

File: indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java (hunk 12 above)
Comment (FrankChen021) [reply indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java]: Got it. BTW, should we handle the exception returned in `IncrementalIndexAddResult` by adding the corresponding row to `responseRows` ?

Comment (jihoonson) [reply indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java]: Yes, I think so because the sampler result should match to what will actually be ingested to Druid.

Comment (FrankChen021) [reply indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java]: A new case `testIndexParseException` in `InputSouceSamplerTest` has been added to check whether the exception returned by `index.add` has been processed properly. And also some little changes are applied in `IncrementalIndex.getCombinedParseException` and `SampleInputRow` to make exception message more accurate.

File: indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java [hunk 14]
```diff
@@ -111,38 +113,49 @@ public SamplerResponse sample(
...
+
+        final List<Map<String, Object>> rawColumnsList = inputRowListPlusRawValues.getRawValuesList();
+
+        final ParseException parseException = inputRowListPlusRawValues.getParseException();
+        if (parseException != null) {
+          if (rawColumnsList != null) {
+            // add all rows to response
+            responseRows.addAll(rawColumnsList.stream()
+                                              .map(rawColumns -> new SamplerResponseRow(rawColumns, null, true, parseException.getMessage()))
+                                              .collect(Collectors.toList()));
```
Comment (jihoonson) [inline indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java:130]: nit: with this change, when a parseException is thrown while parsing a list of rows in one message, those rows in the message will be added as separate rows in `responseRows` but with the same parseException. This can be confusing since the parseException error message seem irrelevant to the associated `rawColumns` in the same `responseRow`. IMO, the better fix in this case would be storing the whole `rawColumnsList` in one `SamplerResponseRow`. Then, the parseException can indicate that it was thrown while parsing one of the rows in `rawColumnsList`. However, this requires a change on the web console side as well. I'm OK with fixing this in a follow-up PR.

File: extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/KafkaIndexTaskTest.java [hunk 15]
```diff
@@ -2726,4 +2726,83 @@ public void close()
...
+                     "{\"timestamp\":2049, \"dim1\": \"d5\", \"dim2\":\"y\", \"dimLong\": 10, \"dimFloat\":\"24.0\", \"met1\":invalidFormat }" +
+                     "{\"timestamp\":2049, \"dim1\": \"d6\", \"dim2\":\"z\", \"dimLong\": 10, \"dimFloat\":\"24.0\", \"met1\":\"3.0\" }";
+
+      ProducerRecord[] producerRecords = new ProducerRecord[]{
+          // pretty formatted
+          new ProducerRecord<>(topic, 0, null, jb(true, "2049", "d1", "y", "10", "20.0", "1.0")),
+          //well-formed
+          new ProducerRecord<>(topic, 0, null, StringUtils.toUtf8(wellformed)),
+          //ill-formed
+          new ProducerRecord<>(topic, 0, null, StringUtils.toUtf8("illformed")),
```
Comment (jihoonson) [inline extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/KafkaIndexTaskTest.java:2758]: Did you intend `StringUtils.toUtf8(illformed)`? The variable `illformed` is not in use.

File: indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java [hunk 16]
```diff
@@ -1060,6 +1062,107 @@ public void testWithFilter() throws IOException
     );
   }
 
+  @Test
+  public void testIndexParseException() throws IOException
```
Comment (jihoonson) [inline indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1066]: Thanks for adding this test! Similar to https://github.com/apache/druid/pull/10383/files#diff-ef25ac1cc1f275b47b939b65e1d0c8b8b8512aeada52d06b8541b8f381df03eeR2731, could you please add a unit test for sampling a block of multiple JSON strings? The unit test can be run only when `parserType` is `STR_JSON`. [We usually just return in the unit test when the parameter is not what we want to test with](https://github.com/apache/druid/blob/master/processing/src/test/java/org/apache/druid/query/groupby/GroupByQueryRunnerTest.java#L6812-L6814). It would be nice if the test verifies the followings:
- The sampler response when there is no parseException with a list of multiple JSON strings.
- The sampler response when there is a parseException thrown while parsing a list of multiple JSON strings. Maybe you can improve this unit test to do it as well.

**Review by jihoonson — COMMENTED** [review]
@FrankChen021, thanks for addressing comments! I have 2 major comments on the test side though. Please take a look.

File: extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/KafkaIndexTaskTest.java (hunk 15 above)
Comment (FrankChen021) [reply extensions-core/kafka-indexing-service/src/test/java/org/apache/druid/indexing/kafka/KafkaIndexTaskTest.java:2758]: Yes, `illformed` here should be a variable instead of a text string.

File: indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java (hunk 16 above)
Comment (FrankChen021) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1066]: A block of multiple json strings is only supported in stream ingestion as we discussed above, that's also why the test cases are added in kafka-indexing-service module.[It's implemented by setting the new property on `JsonInputFormat` in `RecordSupplierInputSource`](https://github.com/apache/druid/pull/10383/files#diff-72b4a411d4ce193935a708df516b00f94827e9563ba7adf00c9e0be479435b5bR106).

 For test cases for `InputSourceSampler` here, the input source is `InlineInputSource` which always uses `InputEntityIteratingReader` even when input format is `JsonInputFormat`, there's no chance to test that. So I think we don't need add test cases here.

File: indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java (hunk 14 above)
Comment (FrankChen021) [reply indexing-service/src/main/java/org/apache/druid/indexing/overlord/sampler/InputSourceSampler.java:130]: Yes, returning the whole `rawColumnsList` involves some changes at the web-console side which is currently out of my ability. Thanks for understanding.

File: indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java (hunk 16 above)
Comment (jihoonson) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1066]: I think we need such tests because `KafkaIndexTaskTest` only covers the actual indexing side, but not the sampling side. Without those tests, we could break the sampler without being noticed.

> For test cases for `InputSourceSampler` here, the input source is `InlineInputSource` which always uses `InputEntityIteratingReader` even when input format is `JsonInputFormat`, there's no chance to test that. So I think we don't need add test cases here.

Maybe this is not a good place for the new tests, but you don't have to use the `InlineInputSource` for them. Rather, you should use `RecordSupplierInputSource` as you mentioned. Since `RecordSupplierInputSource` accepts the `RecordSupplier` interface as a parameter which is the data supplier, I think you could implement a mock for testing (I don't think we should test `Firehose` as it's deprecated). Or do you see some reason you cannot? If it's hard, I'm also OK with adding them in a follow-up.

Comment (FrankChen021) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1066]: > I think we need such tests because `KafkaIndexTaskTest` only covers the actual indexing side, but not the sampling side. Without those tests, we could break the sampler without being noticed.

I forgot that test cases in `KafkaIndexTaskTest` only cover the indexing process. It's OK for me to add such tests. 

BTW, integration tests failed, I don't think it's related to changes in this PR, and the failure can also be seen in my other PR, is there any other problem ?

Comment (jihoonson) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1066]: Thanks for understanding. Do you want to add those tests in this PR? For the integration test failure, I don’t think it’s relevant to the changes in this PR. I just retriggered it.

Comment (FrankChen021) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1075]: I've added a test [`testMultipleJsonStringInOneBlock`](https://github.com/apache/druid/pull/10383/files#diff-b4114cca5866803474d2b6ec21a1d566b90eab5d4a31d4f051b93cd8883914ebR1187),  please check it.

File: indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java [hunk 17]
```diff
@@ -1163,6 +1172,121 @@ public void testIndexParseException() throws IOException
...
+        granularitySpec,
+        transformSpec
+    );
+
+    List<String> jsonBlockList = ImmutableList.of(
+        // include the line which can't be parsed into JSON object to form a illegal json block
+        String.join("", STR_JSON_ROWS),
+
+        // exclude the last line to form a legal json block
+        String.join("", STR_JSON_ROWS.stream().limit(STR_JSON_ROWS.size() - 1).collect(Collectors.toList()))
```
Comment (jihoonson) [inline indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1221]: > [ERROR] indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java:1221 -- Can be replaced with 'Collectors.joining'

Seems like the Intellij Inspection CI doesn't like this line.

**Review by jihoonson — APPROVED** [review]
@FrankChen021 thanks for adding a test! All changes good to me, but please fix the CI.

File: indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java (hunk 17 above)
Comment (FrankChen021) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java]: Every time I push a commit to a branch that is being merge, I run the test cases in the module which contains the changes in that commit. If it's OK, I'll push the commit. But I find that there's a high probability that CI fails. Sometime it's related to inspection check, sometimes it's caused by failures of test cases in other modules, sometime it's about dependency check, sometime it has something with license check. 

I wonder what steps do you follow to check before push a commit ? Do you run all the cases in all modules ? Or is there any simple ways to run the checks mentioned above ?

Comment (FrankChen021) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java]: could you re-trigger the CI ? The failure does not related to changes in the PR.



```
Failed with bad exit code during 'Extraction'

[ERROR] Failed to execute goal on project druid-sql: Could not resolve dependencies for project org.apache.druid:druid-sql:jar:0.21.0-SNAPSHOT: Failed to collect dependencies at org.apache.calcite:calcite-core:jar:1.21.0 -> org.codehaus.janino:janino:jar:3.0.11: Failed to read artifact descriptor for org.codehaus.janino:janino:jar:3.0.11: Could not transfer artifact org.codehaus.janino:janino-parent:pom:3.0.11 from/to central (https://repo.maven.apache.org/maven2): Failed to transfer file https://repo.maven.apache.org/maven2/org/codehaus/janino/janino-parent/3.0.11/janino-parent-3.0.11.pom with status code 503 -> [Help 1]
```

Comment (suneet-s) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java]: Re-triggered LGTM

Comment (FrankChen021) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java]: Hi @suneet-s , do you have any comments ?

Comment (jihoonson) [reply indexing-service/src/test/java/org/apache/druid/indexing/overlord/sampler/InputSourceSamplerTest.java]: > Every time I push a commit to a branch that is being merge, I run the test cases in the module which contains the changes in that commit. If it's OK, I'll push the commit. But I find that there's a high probability that CI fails. Sometime it's related to inspection check, sometimes it's caused by failures of test cases in other modules, sometime it's about dependency check, sometime it has something with license check.
> 
> I wonder what steps do you follow to check before push a commit ? Do you run all the cases in all modules ? Or is there a simple way to run the checks mentioned above ?

That's what I usually do as well. To be honest, unexpected CI failures make me annoyed too :sweat_smile: You can run those checks on your own by running the same command as what Travis runs. You may want to set up some pre-commit/post-commit hooks. The best would be some automatic correction for trivial issues, but I'm not sure if there is such a tool available which is matured and reliable enough.

**Comment by jihoonson** [comment]
I'm merging this PR. Thanks @FrankChen021!

**Comment by FrankChen021** [comment]
> I'm merging this PR. Thanks @FrankChen021!

I appreciate your review and comments very much!
