### PR TITLE
Coordinator Dynamic Config changes to ease upgrading with new config value

### LINKED ISSUE #10723: Exception in Coordinator if upgrading to Druid packages with `percentOfSegmentsToConsiderPerMove` implemented
### Affected Version

master only (unreleased patch, #10284 causes this).

### Description

When you update your coordinator to run with the latest code that has #10284 and this new dynamic coordinator config. The coordinator will have non fatal exceptions when checking the dynamic config that is in metastore because that config does not have a value for `percentOfSegmentsToConsiderPerMove` and the code has a precondition check that demands it is between 1 and 100. It appears to me that this causes only a WARN and the dynamic config is replaced with the default dynamic config until an operator submits the coordinator config json with the new config to be persisted in the metastore.

I think the easiest fix is to add a handler for null in the constructor of the dynamic config that will catch the issue and set the value to the default of 100 while logging a warn notifying the operator that they need to submit a valid spec. That way the whole config would be the default, just the missing value. another option to try would be to use the DynamicConfig Builder in CoordinatorDynamicConfig#watch to properly handle this case. In that case there would be no warning log to the end user.

### PR DESCRIPTION
**Pull request by capistrant**
Fixes #10723 

#### Fixed the bug introduced in #10723 

The mentioned change introduced undesirable behavior during upgrade. The new config value `percentOfSegmentsToConsiderPerMove` requires a value of 1 - 100. Default is 100. However on upgrade the coordinator will load the dynamic config from metastore using `CoordinatorDynamicConfig` for deserialization. Since the config will not have existed pre-upgrade, it will be null for the constructor which violates the precondition check on the value. This would cause the code to load the Builder default of CoordinatorDynamicConfig at startup. I believe this is undesirable. Instead we want Druid to load the existing persisted config with the default for the new config while logging a warn to the operator telling them their persisted config is out of date. 

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * CoordinatorDynamicConfig

### CODE REVIEW

**Comment by capistrant** [comment]
@suneet-s I have added you as reviewer since you were reviewer on initial PR.

File: server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java [hunk 1]
```diff
@@ -126,6 +129,15 @@ public CoordinatorDynamicConfig(
     this.mergeSegmentsLimit = mergeSegmentsLimit;
     this.maxSegmentsToMove = maxSegmentsToMove;
 
+    if (percentOfSegmentsToConsiderPerMove == null) {
+      log.warn("percentOfSegmentsToConsiderPerMove was null! This is likely because your metastore does not "
```
Comment (suneet-s) [inline server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java:133]: I don't think this should be a warn log message. A user should not be expected to set an optional config. If the config is not set, it seems reasonable to me that the default is set to preserve the old behavior (ie all segments are considered per move). 

For users who want to use the new behavior, I suspect they will hear about it in the release notes or the docs, and update the config to get the new functionality.
 
```suggestion
      log.debug("percentOfSegmentsToConsiderPerMove was null! This is likely because your metastore does not "
```

**Review by suneet-s — COMMENTED** [review]
@capistrant good catch! Let me know if you think it should remain a warn log instead of debug, otherwise LGTM

File: server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java (hunk 1 above)
Comment (capistrant) [reply server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java:133]: ya, I guess this is fine as a debug. It will actually automatically get set to the default (or the user specified value) the next time a user submits a new dynamic config since that code path uses builder which will populate missing values. will update now

**Review by suneet-s — APPROVED** [review]
👍

**Comment by suneet-s** [comment]
@capistrant It looks like CI is complaining about a missing file for a newly added (I think) integration test 🤔 I'm not sure how this PR could have caused that failure - https://travis-ci.com/github/apache/druid/jobs/468930258 (I tried re-triggering this job a couple times just incase)

Could you maybe try merging master back into this PR to see if that will make Travis happy

File: server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java [hunk 2]
```diff
@@ -96,7 +99,7 @@ public CoordinatorDynamicConfig(
       @JsonProperty("mergeBytesLimit") long mergeBytesLimit,
       @JsonProperty("mergeSegmentsLimit") int mergeSegmentsLimit,
       @JsonProperty("maxSegmentsToMove") int maxSegmentsToMove,
-      @JsonProperty("percentOfSegmentsToConsiderPerMove") double percentOfSegmentsToConsiderPerMove,
+      @JsonProperty("percentOfSegmentsToConsiderPerMove") Double percentOfSegmentsToConsiderPerMove,
```
[the remark this answers is not in the document]
Comment (suneet-s) [reply server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java:102]: This was because of my comment in the initial PR - https://github.com/apache/druid/pull/10284#discussion_r546171183

I was thinking about developer error in calculating the percentage

**Comment by jihoonson** [comment]
@capistrant the code changes LGTM, but could you add a unit test that verifies JSON deserialization of `CoordinatorDynamicConfig` with missing `percentOfSegmentsToConsiderPerMove`?

**Review by jihoonson — APPROVED** [review]
LGTM. +1 after CI
