### PR TITLE
remove DruidLeaderClient.goAsync(..) that does not follow redirect. Replace its usage by DruidLeaderClient.go(..) with InputStreamFullResponseHandler

### LINKED ISSUE #8716: Handle coordinator leader changes for segments view
### Affected Version

Druid 0.16

### Description
The web-console's Datasources view and the Segments view would not work if there is a leader change in the background. It's because the backend API which invokes the coordinator to get segments does not handle leader changes.

The workaround for now would be to restart the coordinator, so that router connects to the current leader.

### PR DESCRIPTION
**Pull request by himanshug**
Fixes #8716.

After this, we can revert #9702

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

<hr>

@surekhasaharan @jihoonson

### CODE REVIEW

**Comment by surekhasaharan** [comment]
Thank you @himanshug for raising this PR, I'll take a look soon(this week or next).

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java [hunk 1]
```diff
@@ -201,32 +197,41 @@ private void poll()
...
       );
+
+      responseHolder = coordinatorClient.go(
+          request,
+          new InputStreamFullResponseHandler()
+      );
+      if (responseHolder.getStatus().getCode() != HttpServletResponse.SC_OK) {
+        throw new RE(
+            "Failed to talk to coordinator leader at [%s]. Error code[%d], description[%s].",
+            query,
```
Comment (surekhasaharan) [inline sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java:214]: instead of `query`, it should be `request.getUrl().toString()` or something which gives info about the leader location.

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java [hunk 2]
```diff
@@ -201,32 +197,41 @@ private void poll()
...
     return new JsonParserIterator<>(
         typeRef,
-        future,
+        Futures.immediateFuture(responseHolder.getContent()),
         request.getUrl().toString(),
         null,
         request.getUrl().getHost(),
         jsonMapper,
-        responseHandler
+        null
```
Comment (surekhasaharan) [inline sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java:234]: can we remove this param now

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java [hunk 3]
```diff
@@ -736,37 +733,48 @@ public void close()
...
+
+      responseHolder = indexingServiceClient.go(
+          request,
+          new InputStreamFullResponseHandler()
       );
+
+      if (responseHolder.getStatus().getCode() != HttpServletResponse.SC_OK) {
+        throw new RE(
+            "Failed to talk to overlord leader at [%s]. Error code[%d], description[%s].",
+            query,
```
Comment (surekhasaharan) [inline sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java:757]: same comment about replacing `query` with more meaningful info here and at other places

**Comment by himanshug** [comment]
@surekhasaharan sorry, I was away for a while, thanks for reviewing. I will try to address those this week.

File: core/src/main/java/org/apache/druid/java/util/http/client/response/FullResponseHolder.java [hunk 4]
```diff
@@ -49,12 +49,7 @@ public HttpResponse getResponse()
   }
 
   /**
-   * Append a new chunk of data.
-   */
-  public abstract FullResponseHolder addChunk(T chunk);
```
[the remark this answers is not in the document]
Comment (himanshug) [reply core/src/main/java/org/apache/druid/java/util/http/client/response/FullResponseHolder.java:54]: removed it because newly introduced `InputStreamFullResponseHolder.addChunk(byte[] chunk)` whereas `getContent()` needs to return `InputStream` . We could do the necessary wrapping so as to have `InputStreamFullResponseHolder.addChunk(InputStream chunk)` but would have required an extra wrap/unwrap of byte[] into/outof `ByteArrayInputStream` in `InputStreamResponseHandler .

File: server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java [hunk 5]
```diff
@@ -121,42 +120,20 @@ public void stop()
...
-  }
-
   /**
    * Make a Request object aimed at the leader. Throws IOException if the leader cannot be located.
    */
   public Request makeRequest(HttpMethod httpMethod, String urlPath) throws IOException
   {
-    return makeRequest(httpMethod, urlPath, true);
+    Preconditions.checkState(lifecycleLock.awaitStarted(1, TimeUnit.MILLISECONDS));
+    return new Request(httpMethod, new URL(StringUtils.format("%s%s", getCurrentKnownLeader(true), urlPath)));
```
[the remark this answers is not in the document]
Comment (himanshug) [reply server/src/main/java/org/apache/druid/discovery/DruidLeaderClient.java:129]: if cached "leader" has disappeared then connection to that host will fail and we will  retry with a randomly  chosen  available server in code path starting line-160 .
if cached "leader" is not leader anymore then it should send a `TEMPORARY_REDIRECT` and we would retry with code flow starting at line 193

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java (hunk 1 above)
Comment (himanshug) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java:214]: as explained above, since we change the server on-the-fly as explained above, request.getUrl() would contain  the original cached host and might print host1 which has  disappeared and response has really come from current discovered leader inside go(..) method impl, "request" object passed is not modified.
with some hackery, we could get it to print real server contacted, but I thought that would be overkill  for this logging use case and just printing that got this blah response from "coordinator leader" was good enough.

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java (hunk 2 above)
Comment (himanshug) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java:234]: I didn't know where else it was used, if it is not used anywhere then we can remove  it yes.

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java (hunk 3 above)
Comment (himanshug) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/SystemSchema.java:757]: same

File: sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java (hunk 2 above)
Comment (himanshug) [reply sql/src/main/java/org/apache/druid/sql/calcite/schema/MetadataSegmentView.java]: removed

**Comment by surekhasaharan** [comment]
LGTM, thanks @himanshug 
Though it seems CI is failing because of code coverage
```
ERROR: Insufficient line coverage of 20% (10/50). Required 65%.
ERROR: Insufficient branch coverage of 33% (2/6). Required 65%.
```

**Comment by himanshug** [comment]
@surekhasaharan thanks for checking.
yeah, I noticed that we recently added code coverage expectation to builds. changes here is mostly updating existing  code and  new classes `InputStreamResponse***` are don't have much  logic except for calling methods , ideally we could unit test it with mocks but I am not sure how much value is there.
many PRs appear to be struggling with new requirement ... maybe the newly introduced expectation around code coverage needs to be tuned down a bit.

**Comment by surekhasaharan** [comment]
> @surekhasaharan thanks for checking.
> yeah, I noticed that we recently added code coverage expectation to builds. changes here is mostly updating existing code and new classes `InputStreamResponse***` are don't have much logic except for calling methods , ideally we could unit test it with mocks but I am not sure how much value is there.
> many PRs appear to be struggling with new requirement ... maybe the newly introduced expectation around code coverage needs to be tuned down a bit.

Yeah, there are discussions going on related to code coverage checks requirement, i'll wait on the decision on that, otherwise PR is good to go.

**Comment by surekhasaharan** [comment]
@himanshug could you try to merge master, it seems https://github.com/apache/druid/pull/9969 was merged to help with code coverage check failures.

**Comment by surekhasaharan** [comment]
@himanshug  While we are improving the usability of code coverage checks, it seems this PR is still failing with the more lenient checks.
```
Diff coverage statistics:
------------------------------------------------------------------------------
|     lines      |    branches    |   functions    |   path
------------------------------------------------------------------------------
|   0% (0/10)    | 100% (0/0)     |  55% (11/20)   | org/apache/druid/java/util/http/client/response/InputStreamFullResponseHolder.java
|   0% (0/14)    | 100% (0/0)     |  50% (15/30)   | org/apache/druid/java/util/http/client/response/InputStreamFullResponseHandler.java
|  55% (10/18)   |  50% (2/4)     | 100% (5/5)     | org/apache/druid/sql/calcite/schema/SystemSchema.java
|   0% (0/8)     |   0% (0/2)     | 100% (4/4)     | org/apache/druid/sql/calcite/schema/MetadataSegmentView.java
------------------------------------------------------------------------------
Total diff coverage:
 - lines: 20% (10/50)
 - branches: 33% (2/6)
 - functions: 59% (35/59)
ERROR: Insufficient line coverage of 20% (10/50). Required 50%.
ERROR: Insufficient branch coverage of 33% (2/6). Required 50%.
```
Some suggestions to move forward:
For `InputStreamFullResponseHolder` and `InputStreamFullResponseHandler` you could add coverage suppression like [here](https://github.com/apache/druid/blob/master/pom.xml#L1259)
For `SystemSchema` and `MetadataSegmentView`, the new code  around this check is not covered in the existing `SystemSchemaTest`
```
if (responseHolder.getStatus().getCode() != HttpServletResponse.SC_OK) {
```
It might be possible to cover this for the branch and line coverage for above condition.

**Comment by himanshug** [comment]
@surekhasaharan this should be ready to merge now, thanks for the reviews.

**Comment by himanshug** [comment]
@surekhasaharan can you please +1 this? thanks.
