### PR TITLE
Fix native batch range partition segment sizing

### LINKED ISSUE #10057: index_parallel with single_dim partitionSpec type generating just one file/segment
### Affected Version
Druid Built From Source as of Fri Jun 5, 2020

### Description

We are trying to create new druid ingestion specs to pull from s3 directly via index_parallel rather than hadoop. The outputs simply don't seem to be partitioned though.

To make it easy to reproduce, here is a simple config that shows the issue:

```
{
  "spec": {
    "type": "index_parallel",
    "ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "http",
        "uris": [
          "https://druid.apache.org/data/wikipedia.json.gz",
          "https://druid.apache.org/data/wikipedia.json.gz"
        ]
      },
      "inputFormat": {
        "type": "json"
      }
    },
    "tuningConfig": {
      "type": "index_parallel",
      "partitionsSpec": {
        "type": "single_dim",
        "partitionDimension": "channel",
        "maxRowsPerSegment": 2000
      },
      "forceGuaranteedRollup": true,
      "maxNumConcurrentSubTasks": 4
    },
    "dataSchema": {
      "dataSource": "wikipedia-test-partitioned-2",
      "granularitySpec": {
        "type": "uniform",
        "segmentGranularity": "DAY",
        "queryGranularity": "HOUR",
        "rollup": true,
        "intervals": [
          "2000-01-01/2030-01-01"
        ]
      },
      "timestampSpec": {
        "column": "timestamp",
        "format": "iso"
      },
      "dimensionsSpec": {
        "dimensions": [
          "channel",
          "cityName",
          "comment",
          "countryIsoCode",
          "countryName",
          "diffUrl",
          "flags",
          "isAnonymous",
          "isMinor",
          "isNew",
          "isRobot",
          "isUnpatrolled",
          "metroCode",
          "namespace",
          "page",
          "regionIsoCode",
          "regionName",
          "user"
        ]
      },
      "metricsSpec": [
        {
          "name": "count",
          "type": "count"
        },
        {
          "name": "sum_added",
          "type": "longSum",
          "fieldName": "added"
        },
        {
          "name": "sum_commentLength",
          "type": "longSum",
          "fieldName": "commentLength"
        },
        {
          "name": "sum_deleted",
          "type": "longSum",
          "fieldName": "deleted"
        },
        {
          "name": "sum_delta",
          "type": "longSum",
          "fieldName": "delta"
        },
        {
          "name": "sum_deltaBucket",
          "type": "longSum",
          "fieldName": "deltaBucket"
        }
      ]
    }
  },
  "type": "index_parallel"
}
```

Since maxRowsPerSegment is 2,000 and there are 24,000 rows in the dateset, I was expecting many partitions.

I made sure to set two files so that it could be parallelized, since I saw some comments about needing to set maxNumConcurrentSubTasks and figured this might also apply to needing multiple input files.

Of course the data that I have is much larger, coming out to a few GB, but I'm seeing the exact same issue.

I have tried both setting targetRowsPerSegment and maxRowsPerSegment, and neither work.

### PR DESCRIPTION
**Pull request by ccaominh**
Fixes #10057.

### Description

Native batch range partitioning was only considering the partition dimension value when grouping rows instead of using all of the row's partition values. Thus, for schemas with multiple dimensions, the rollup was overestimated, which would cause too many dimension values to be packed into the same range partition. The resulting segments would then be overly large (and not honor the target or max partition sizes).

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.

<hr>

##### Key changed/added classes in this PR
* `PartialDimensionDistributionTask`: Consider all dimension values when grouping row
* `RangePartitionMultiPhaseParallelIndexingTest`: Regression test by having input with rows that should roll up and rows that should not roll up

### CODE REVIEW

**Comment by ccaominh** [comment]
Also manually tested with the ingestion spec provided in https://github.com/apache/druid/issues/10057 (but modified the intervals to be the tighter range of "2016-06-26/2016-06-28" instead of "2000-01-01/2030-01-01"). After the fix, 14 segments are created, whereas only 1 segment was getting created before.

File: indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTask.java [hunk 1]
```diff
@@ -223,17 +224,19 @@ public TaskStatus runTask(TaskToolbox toolbox) throws Exception
...
+                .granularitySpec(granularitySpec)
+                .nullRowRunnable(IndexTaskInputRowIteratorBuilder.NOOP_RUNNABLE)
+                .absentBucketIntervalConsumer(IndexTaskInputRowIteratorBuilder.NOOP_CONSUMER)
+                .build()
     ) {
       Map<Interval, StringDistribution> distribution = determineDistribution(
           iterator,
           granularitySpec,
           partitionDimension,
+          dataSchema.getDimensionsSpec().getDimensionNames(),
```
Comment (gianm) [inline indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTask.java:239]: I haven't fully looked into the logic of `determineDistribution`, but a warning: this isn't the right way to get the list of dimension names that will end up in the finished product, since it won't work properly in [schemaless dimensions](https://druid.apache.org/docs/latest/ingestion/schema-design.html#schema-less-dimensions) mode. So `determineDistribution` may need to accept the DimensionsSpec itself and do the same logic that the index generator code itself would do.

Watch out for the queryGranularity as well, which is part of the rollup key. It looks like `determineDistribution` isn't currently inspecting it (it comes from `granularitySpec.getQueryGranularity()`).

Comment (gianm) [reply indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTask.java:239]: Maybe use `Rows.toGroupKey`?

Comment (ccaominh) [reply indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTask.java]: Changed to use `Rows.toGroupKey()`. The code was already using `queryGranualrity` as part of the rollup key.
