### PR TITLE
Segment loading: Allow cancellation and prioritization of load queue items

### LINKED ISSUE #12881: Segment loading and balancing improvements
## Motivation
Segment loading is one of the more complicated pieces of Druid operations and is prone to failures and race conditions. Due to lack clean logs and metrics, it is often very difficult to debug too. 

## Identified issues and proposed changes
Discussed below are a few issues with the current implementation and possible fixes that can help improve the coordinator operation.

### 1. Balancing always causes over-replication!

**Problem:**
While moving a segment from server A to B, the load succeeds on B but the drop on A is never invoked. This happens because the server inventory view maintained by the coordinator may still not be updated when the drop callback comes. Under normal circumstances, this is not noticeable because load rules quickly drop the over-replicated segments. But if load rules get stuck for some reason, the number of over-replicated segments keeps increasing thereby overloading historicals.

over_replication

**Proposed fix:**
1. Do not check the server inventory to determine if the drop should be invoked.
2. Use the HTTP status (applicable only to `HttpLoadQueuePeon`) received from the change request to determine if the load was successful or not.
3. Provide a success as well as a failure callback to the `LoadQueuePeon`.

### 2. Changes to `replicationThrottleLimit`

**Definition:**
> The maximum number of segments that can be replicated at one time.

The main aim of throttling replication is to avoid a stampede when a server suddenly disappears. It is possible that the server is temporarily invisible to the coordinator due to ephemeral network issues. In such scenarios, the load queue should not be completely filled up with replicas which might appear soon after.

**Problem 1:**
This design considers replication on a cluster level, rather than a tier level. Ideally, if load rules determine that a segment should be available on a tier, the segment should be quickly loaded there. Relying on data existing on other tiers kind of defeats the purpose of tiering.

**Proposed fix:**
1. Do not consider the first copy of a segment on a tier as a replica and do not subject it to replication throttling.

At the start of every run, a tier is considered eligible for replication only if there is no pending replication in that tier. Based on the `replicationThrottleLimit`, we add items to the replication queue during the course of `RunRules`. 

**Problem 2:**
While rules are executing, the replication queue might free up as replicas get successfully loaded. The rules misinterpret this situation as the `replicationThrottleLimit` not having been met and queue up more replicas. In some situations, this can go on for a very long time increasing the duration of a now stale coordinator run cycle.

**Proposed fix:**
1. Clarify the definition of the `replicationThrottleLimit` as `The maximum number of segment that can be queued up for replication in one coordinator cycle.`
2. Determine `replicationThrottleLimit` at the start of the run for each tier. Compare the number of segments assigned for replication in this run rather than the current queue size against the `replicationThrottleLimit` to determine if the limit has been reached.

### 3. Drops happen only after target replication is met on every tier

**Problem:**
The target replication level on a new tier might be high and would be subject to replication throttling. Drop of an unneeded replica should not have to wait on this.

**Proposed fix:**
Drop over-replicated segments as soon as a single replica of the segment is available on every required tier.

### 4. Only loaded segments count towards over-replication

Changes in item (2) above ensure that segments assigned freshly to a tier would not be subject to replication throttling anymore. This implies that when a server disappears temporarily (due to intermittent network issues), segments whose only copy in this tier was on the disappeared server would quickly be reassigned to other servers. It's possible that the server then reappears soon after.

In the current implementation, all the items in the load queue would finish loading and only then would the rules realise that there is an over-replication. This could take several cycles to happen and would unnecessarily block other important load operations.

**Proposed fix:**
1. Consider a segment as over-replicated if `loaded + loading > required` in any tier.
2. While dropping over-replicated segments, look first in the loading queues. If found, cancel the loading operation. Otherwise, drop one of the loaded segments.

### 5. Segments being balanced may count towards over-replication

As a consequence of the fix in item (4) above, segments that are in the loading queue for balancing might be viewed as over-replicated.

**Proposed fix:**
1. Maintain a marker to distinguish between "moving" segments and "loading" segments.
2. Do not consider "moving" segments while computing replication level or while cancelling load operations to fix over-replication.
3. For all other purposes, continue to treat "moving" and "loading" segments as the same.

### 6. Historicals can get overassigned

During the course of a coordinator run, the available space on a server is not updated even when a load completes. This is because a snapshot of the cluster is taken at the start of the run and the coordinator duties use this snapshot to make assignment decisions.

**Proposed fix:**
1. Maintain the current size and max size of every server inside the `HttpLoadQueuePeon`.
2. Refresh this value at the start of every run.
3. `HttpLoadQueuePeon` already maintains the size of items currently in queue.
3. As soon as an item in the load/drop queue succeeds, update the current size.
4. Add a method `boolean canLoad(DataSegment segment)` which checks both the current size, the queue size and the `maxSegmentsInNodeLoadingQueue` to determine if a segment can be loaded.

Currently, both the `LoadRule` and `BalanceSegments` have to account for the space available on a server and its loading queue to determine if a segment can be assigned to a server. The new method `canLoad` would simplify this logic. Hopefully, we would also be able to phase out `maxSegmentsInNodeLoadingQueue` after this.

### 7. Changes to `cachingCost` balancer strategy

**Problem:**
There are some ways in which `cachingCost` differs from `cost` balancer strategy.
1. It does not subtract the cost of segments about to be dropped.
2. It has a correction factor of `maxSize / availableSize` which is supposed to work for heterogeneous historicals but causes issues with homogeneous historicals.

**Proposed fix:**
1. Subtract the cost of segments marked to be dropped.
2. Remove the correction factor from `cachingCost`. This means that clusters with heterogeneous historical sizes in the same tier should use `diskNormalized` and should avoid both `cost` and `cachingCost` strategies.

### 8. Balancing skips unused segments but not overshadowed segments

**Problem:**
The duty `MarkAsUnusedOvershadowedSegments` marks overshadowed segments as unused. But unfortunately, the `BalanceSegments` is unable to use this information as it works off of an older snapshot.

**Proposed fix:**
This can be easily remedied by updating the list of used segments maintained by the `CoordinatorRuntimeParams` whenever a segment is marked as unused.

### 9. Logging and metrics

Load rules currently flood the logs with cryptic info which hardly provides any assistance while debugging a stuck load.

We should clean up the logs and provide verbose info only on debug or trace levels. Some new metrics should also be added to track the following info:
1. Number of items currently in the replication queue.
2. Number of cancelled load operations.
3. Average time taken for cost computation of each segment.

## Current work status
I am working on the changes for the above fixes and will publish the PRs soon.

## Further improvements
Alongwith these, there are other areas that require improvement to make segment loading more robust and reliable.

1. A single rule run can sometimes take a lot of time (upto hours). This is highly undesirable as the rules would be using a stale metadata snapshot and keep making incorrect decisions. Ideally, the coordinator should make short and quick decisions and keep dynamically correcting itself.
Most of this time is spent in cost computation, as can be easily verified by using a `RandomBalancerStrategy`. An in-depth comparison of cost strategies and identification of possible improvements would go a long way to improve balancing and loading.

2. The cache used by `cachingCost` balancer strategy is constructed freshly at the start of every coordinator cycle. The advantage that `cachingCost` seems to offer over `cost` is that you would need to compute the cost for a segment only against the relevant interval buckets rather than all the segments. But the cost of all the segments is anyway computed at the start while building the cache. Since the number of segments for which cost is to be computed is typically much lower than the total number of segments, this does not offer any real advantage. An improvement could be to maybe reuse the cache across coordinator runs if possible or atleast populate the cache lazily for interval buckets when they are needed.

3. The `replicationThrottleLimit` considers the _number_ of replicas rather than their size to throttle replication. Ideally, this throttling should try to ensure that only a certain percentage (based on size) of the segments that each historical of a tier currently houses are considered for replication in each run. This value can be determined for each tier at the start of the run. Using this approach, we should be able to eventually phase out this config.

### PR DESCRIPTION
**Pull request by kfaraz**
Fixes #12881

### Description

This PR lays the ground work to allow load queue to safely have an unlimited number of items, and thus
eventually phase out `maxSegmentsInNodeLoadingQueue` and `replicationThrottleLimit`.

Load queue is already allowed to have unlimited items (by setting `maxSegmentsInNodeLoadingQueue = 0`)
but this leads to
- each coordinator run taking a very long time
- poor assignments which take several more runs to be rectified

#### Classes to review
- `StrategicSegmentAssigner`
- `LoadRule`, `BroadcastDistributionRule`, `DropRule`, `Rule.SegmentActionHandler`
- `SegmentLoadQueueManager`
- `LoadQueuePeon`: http and curator
- `SegmentHolder`
- `ServerHolder`

#### Behavioral changes

Change | Motivation
--------|-------------
Both loaded and loading items count towards replication. | Allow coordinator to take corrective action of removing superfluous replicas without waiting for them to be fully loaded.
Load, drop or move operations can be cancelled. | - Allow move of loading items from queue of one server to another. <br> - Allow coordinator to take corrective actions quickly.
During tier shift, always maintain the currently configured level of replication, no matter which tier it happens to be on. | - Queue drop of unneeded segments as soon as possible, thus allowing faster decommission of servers and freeing up disk space to load new segments.<br>- Always maintain target level of replication, thus ensuring that segment read concurrency does not suffer
LoadQueuePeon can distinguish and prioritize segment actions as DROP > LOAD > REPLICATE > MOVE (i.e. balancing). | - Allow prioritization of items, which becomes important if load queue size is unlimited. <br> - Avoid considering balancing items in load queue as over-replicated.
`replicationThrottleLimit` does not act on a tier if the segment is not loaded on that tier at all | Throttling first replica on a tier undermines the purpose of tiering. Tiering is not meant for fault tolerance, rather serving different query needs. Thus segments should be available on target tiers as soon as possible.
`maxNonPrimaryReplicantsToLoad` does not act on first replica in any tier | This was done keeping in line with the changes to `replicationThrottleLimit`
num items in load queue at start of run + num items assigned to load queue during run must be <=`maxSegmentsInNodeLoadingQueue` | Currently, if the configured load queue size is large enough to allow load of some segments while a coordinator run is in progress, the load queue limit is violated as there is always some room in the queue. This causes coordinator runs to get stuck cycling through all the segments in spite of a limited load queue.

#### Structural changes

Change | Motivation
--------|-----------
Add `StrategicSegmentAssigner` which handles all segment assignments. The lifecycle of the assigner is tied to a single coordinator run. | - Allow reuse of logic for loading, balancing and broadcasting. <br> - Single place to maintain state of a single run thus allowing better metrics and logging.
Load rules just specify their desired state and leave the actual decision making to the `StrategicSegmentAssigner`. | Simpler logic for load rules.
Add `SegmentLoadQueueManager` that interacts with the load queues. | - Single place to interact with load queue <br>- Allow reporting of metrics from queue callbacks. <br>- Prevent callbacks from holding references to items from the previous coordinator run.

#### New metrics
- `segment/loadQueue/assigned`
- `segment/loadQueue/success`
- `segment/loadQueue/cancelled`
- `segment/loadQueue/failed`
- `segment/assigned/broadcast`
- `segment/dropped/broadcast`
- Added dimension `"datasource"` in most segment level metrics

### Release notes

__--TODO--__

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: server/src/main/java/org/apache/druid/server/coordinator/BalancerSegmentHolder.java [hunk 1]
```diff
@@ -19,29 +19,28 @@
 
 package org.apache.druid.server.coordinator;
 
-import org.apache.druid.client.ImmutableDruidServer;
 import org.apache.druid.timeline.DataSegment;
 
 /**
  */
 public class BalancerSegmentHolder
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/BalancerSegmentHolder.java:26]: Change summary:
Added `ServerHolder` to avoid having to find the corresponding peon later in the flow.

File: server/src/main/java/org/apache/druid/server/coordinator/BalancerStrategy.java [hunk 2]
```diff
@@ -46,13 +46,18 @@
...
    * @param proposalSegment segment to replicate
-   * @param serverHolders servers to consider as replica holders
-   * @return The server to replicate to, or null if no suitable server is found
+   * @param serverHolders   servers to consider as replica holders
+   * @return Iterator over the best servers (in order) on which the replica(s)
+   * can be placed.
    */
-  @Nullable
-  ServerHolder findNewSegmentHomeReplicator(DataSegment proposalSegment, List<ServerHolder> serverHolders);
+  Iterator<ServerHolder> findNewSegmentHomeReplicator(
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/BalancerStrategy.java:57]: Change summary:
Find all the best servers to place replicas in one go rather than multiple strategy computations.

File: server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java [hunk 3]
```diff
@@ -63,7 +56,7 @@
  * of the same or different methods.
  */
 @Deprecated
-public class CuratorLoadQueuePeon extends LoadQueuePeon
+public class CuratorLoadQueuePeon implements LoadQueuePeon
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java:59]: Change summary:
Commoned out class `SegmentHolder` as `QueuedSegment` to represent an item in a load queue and to be used by both `HttpLoadQueuePeon` and `CuratorLoadQueuePeon`.
Implemented new methods in `LoadQueuePeon`.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java [hunk 4]
```diff
@@ -405,111 +405,6 @@ public String getCurrentLeader()
     return coordLeaderSelector.getCurrentLeader();
   }
 
-  public void moveSegment(
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:408]: Change summary:
Moved this method to `SegmentLoader`/`SegmentStateManager`.

File: server/src/main/java/org/apache/druid/server/coordinator/LoadQueuePeon.java [hunk 5]
```diff
@@ -21,37 +21,48 @@
...
+import java.util.Map;
 import java.util.Set;
 
 /**
  * This interface exists only to support configurable load queue management via curator or http. Once HttpLoadQueuePeon
  * has been verified enough in production, CuratorLoadQueuePeon and this interface would be removed.
  */
 @Deprecated
-public abstract class LoadQueuePeon
+public interface LoadQueuePeon
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/LoadQueuePeon.java:32]: Change summary:
Added methods to `cancelLoad`, `cancelDrop`, and `loadSegment(segment, type)` (primary, replica or balance)

File: server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java [hunk 6]
```diff
@@ -65,7 +66,7 @@
 
 /**
  */
-public class HttpLoadQueuePeon extends LoadQueuePeon
+public class HttpLoadQueuePeon implements LoadQueuePeon
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java:69]: Change summary:
Used `QueuedSegment` instead of `SegmentHolder` and implemented new `LoadQueuePeon` methods for cancellation and loading with type.

File: server/src/main/java/org/apache/druid/server/coordinator/CostBalancerStrategy.java [hunk 7]
```diff
@@ -184,20 +193,17 @@ public CostBalancerStrategy(ListeningExecutorService exec)
   }
 
   @Override
-  public ServerHolder findNewSegmentHomeReplicator(DataSegment proposalSegment, List<ServerHolder> serverHolders)
+  public Iterator<ServerHolder> findNewSegmentHomeReplicator(DataSegment proposalSegment, List<ServerHolder> serverHolders)
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/CostBalancerStrategy.java:196]: Change summary:
Find all the best servers to place replicas in one go.

File: server/src/main/java/org/apache/druid/server/coordinator/ReplicationThrottler.java [hunk 8]
```diff
@@ -36,74 +39,89 @@
 {
   private static final EmittingLogger log = new EmittingLogger(ReplicationThrottler.class);
 
-  private final Map<String, Boolean> replicatingLookup = new HashMap<>();
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/ReplicationThrottler.java:39]: Change summary:
Commoned out `ReplicationSegmentHolder` as `TierLoadingState` to be used for tracking both `currentlyReplicatingSegments` and `currentlyMovingSegments` (in `SegmentStateManager`).

File: server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java [hunk 9]
```diff
@@ -20,31 +20,61 @@
...
 import org.apache.druid.timeline.SegmentId;
 
 import java.util.Objects;
+import java.util.concurrent.ConcurrentHashMap;
+import java.util.concurrent.ConcurrentMap;
 
 /**
+ *
  */
 public class ServerHolder implements Comparable<ServerHolder>
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java:33]: Change summary:
Maintain a map containing
- segments that were in load or drop queue when this run started
- segments that were queued for load or drop during this run
This helps the `SegmentLoader` determine the current state of a segment on a server and make load/drop decisions.

File: server/src/main/java/org/apache/druid/server/coordinator/duty/BalanceSegments.java [hunk 10]
```diff
@@ -26,85 +26,65 @@
...
 import java.util.Map;
 import java.util.NavigableSet;
 import java.util.SortedSet;
-import java.util.concurrent.ConcurrentHashMap;
-import java.util.concurrent.ConcurrentMap;
 import java.util.stream.Collectors;
 
 /**
  */
 public class BalanceSegments implements CoordinatorDuty
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/duty/BalanceSegments.java:44]: Change summary:
Move state of `currentlyMovingSegments` to `SegmentStateManager`.

File: server/src/main/java/org/apache/druid/server/coordinator/duty/EmitClusterStatsAndMetrics.java [hunk 11]
```diff
@@ -234,36 +218,40 @@ private void emitStatsForHistoricalManagementDuties(DruidCluster cluster, Coordi
         }
     );
 
+    // Log load queue status of all replication or broadcast targets
     log.info("Load Queues:");
-    for (Iterable<ServerHolder> serverHolders : cluster.getSortedHistoricalsByTier()) {
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/duty/EmitClusterStatsAndMetrics.java:238]: Change summary: Report queue status not just of historicals but all replication or broadcast targets.

File: server/src/main/java/org/apache/druid/server/coordinator/duty/EmitClusterStatsAndMetrics.java [hunk 12]
```diff
@@ -322,18 +310,14 @@ private void emitStatsForHistoricalManagementDuties(DruidCluster cluster, Coordi
...
-          final int numUnavailableUsedSegmentsInDataSource = entry.getIntValue();
-          emitter.emit(
-              new ServiceMetricEvent.Builder()
-                  .setDimension(DruidMetrics.DUTY_GROUP, groupName)
-                  .setDimension(DruidMetrics.DATASOURCE, dataSource).build(
-                  "segment/unavailable/count", numUnavailableUsedSegmentsInDataSource
-              )
-          );
-        }
+    coordinator.computeNumsUnavailableUsedSegmentsPerDataSource().forEach(
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/duty/EmitClusterStatsAndMetrics.java:313]: Style change: Use simpler iterator.

File: server/src/main/java/org/apache/druid/server/coordinator/duty/RunRules.java [hunk 13]
```diff
@@ -46,38 +45,16 @@ public class RunRules implements CoordinatorDuty
   private static final EmittingLogger log = new EmittingLogger(RunRules.class);
   private static final int MAX_MISSING_RULES = 10;
 
-  private final ReplicationThrottler replicatorThrottler;
+  private final SegmentStateManager stateManager;
 
-  private final DruidCoordinator coordinator;
-
-  public RunRules(DruidCoordinator coordinator)
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/duty/RunRules.java:53]: Change summary:
Move replication throttling logic to `SegmentStateManager`.
Move check on `maxNonPrimaryReplicantsToLoad` to `ReplicationThrottler` (requires revisit).

File: server/src/test/java/org/apache/druid/server/coordinator/simulate/SegmentLoadingNegativeTest.java [hunk 14]
```diff
@@ -91,130 +88,4 @@ public void testImmediateLoadingViolatesThrottleLimit()
     verifyDatasourceIsFullyLoaded(datasource);
   }
 
-  /**
-   * Correct behaviour: The first replica on any tier should not be throttled.
-   * <p>
-   * Fix Apache #12881 to fix this test.
-   */
-  @Test
```
Comment (kfaraz) [inline server/src/test/java/org/apache/druid/server/coordinator/simulate/SegmentLoadingNegativeTest.java:99]: Change summary: 
The underlying behaviour for these tests is now fixed!
The corresponding positive test cases can be found in `SegmentLoadingTest`.

**Review by kfaraz — COMMENTED** [review]
Added change summary to important classes.
The tests have been updated to use new flow but the same behaviour is still being verifiied.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentAction.java [hunk 15]
```diff
@@ -0,0 +1,33 @@
...
+
+/**
+ * Represents actions that can be performed on a server for a single segment.
+ * <p>
+ * The different action types can be used to prioritize items in a LoadQueuePeon.
+ */
+public enum SegmentAction
+{
+  DROP,
+  LOAD_AS_PRIMARY,
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentAction.java:30]: Rename to something like `ACTIVE_LOAD`, `LAZY_LOAD`.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java [hunk 16]
```diff
@@ -0,0 +1,235 @@
...
+import org.apache.druid.timeline.DataSegment;
+
+import java.util.HashSet;
+import java.util.Set;
+import java.util.concurrent.ConcurrentHashMap;
+
+/**
+ * Manages state of segments being loaded.
+ */
+public class SegmentStateManager
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:34]: Rename to `LoadQueueManager` as this class really acts as an interface between the duties and the load queues.

File: server/src/main/java/org/apache/druid/server/coordinator/CostBalancerStrategy.java [hunk 17]
```diff
@@ -49,6 +50,14 @@ public class CostBalancerStrategy implements BalancerStrategy
   private static final double MILLIS_IN_HOUR = 3_600_000.0;
   private static final double MILLIS_FACTOR = MILLIS_IN_HOUR / LAMBDA;
 
+  /**
+   * Comparator that prioritizes servers by cost. Cheaper servers come before
+   * costlier servers. Servers with the same cost may appear in a random order.
+   */
+  private static final Comparator<Pair<Double, ServerHolder>> CHEAPEST_SERVERS_FIRST
+      = Comparator.<Pair<Double, ServerHolder>, Double>comparing(pair -> pair.lhs)
+      .thenComparing(pair -> ThreadLocalRandom.current().nextInt());
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/CostBalancerStrategy.java:59]: Sure, that would work too. 

This PR does not make any modifications to strategies, so it has not been included here. The only modification done here is reduction in the number of calls to strategy.

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java [hunk 18]
```diff
@@ -0,0 +1,72 @@
...
+import java.util.List;
+import java.util.concurrent.ConcurrentHashMap;
+
+/**
+ * Contains segments being loaded or replicated in a tier.
+ */
+public class TierLoadingState
+{
+  private int lifetime;
+  private final ConcurrentHashMap<SegmentId, String> processingSegments = new ConcurrentHashMap<>();
```
Comment (AmatyaAvadhanula) [inline server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:34]: Can't a tier load / balance the same segment on multiple servers simultaneously with these changes?

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java [hunk 19]
```diff
@@ -0,0 +1,72 @@
...
+import java.util.ArrayList;
+import java.util.List;
+import java.util.concurrent.ConcurrentHashMap;
+
+/**
+ * Contains segments being loaded or replicated in a tier.
+ */
+public class TierLoadingState
+{
+  private int lifetime;
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:33]: That would be the ideal behaviour but as it turns out, this is the existing implementation. I have tried to keep it unchanged for now.

Let's say, in a coordinator run, we queue some segments to move within a tier. All the segments queued would start with the same lifecycle. Only when all these queued segments have been processed will we consider this tier for moving again. So, at it turns out, in `BalanceSegments.currentlyMovingSegments` in the existing code, all segment holders for a given tier will always have the same lifecycle.

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java (hunk 18 above)
Comment (AmatyaAvadhanula) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:34]: The code doesn't enforce it, and it is possible for the same segment to be replicated / moved on different servers within the same tier.
This datastructure would lead to a loss of that information  (which also happens to be the case with the current implementation of ReplicationThrottler)

Comment (AmatyaAvadhanula) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:34]: A simple example is a LoadRule within a tier with a replication factor of 2. Both replicas can be loaded in the same cycle but the TierLoadingState would only keep track of the second load

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (AmatyaAvadhanula) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:33]: Please consider the usage in ReplicationThrottler where a TierLoadingState is added to `currentlyReplicating`.
A tier may be busy for a period greater than the lifetime without the load queue being stuck. In such a case the lifetime would still be decreased and may become < 0.

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java (hunk 18 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:34]: Yes, as you mention, that is the current implementation and we have retained it here.
We are hoping to relax replication throttle limit further anyway. So changing this behaviour is not really required.

Incidentally, it is also the desirable implementation, being simpler to understand and reason about than the alternative. From the docs, definition of `replicationThrottleLimit`:
`The maximum number of segments that can be replicated at one time.`
Alternative would be: 
`The number of replica segments (i.e. non primary) that can be in the queue at any time`.

We could try an alternative implementation but it would have these issues:
- Counting each replica separately would hit the throttle limit sooner (i.e. with fewer _unique_ segments), thus increasing the time to full replication. We could always increase the throttle limit but we would have to keep increasing it whenever we decided to increase the replication level on _any_ datasource.
- Assigning 1st replica of each segment, then 2nd replica of each segment is not an option either because we must make all decisions for a given segment in a single invocation of the `LoadRule.run()`.

Hope that clarifies the design choice 🙂

Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:34]: However, this PR does modify the definition of `replicationThrottleLimit` and `maxSegmentsInNodeLoadingQueue` slightly (docs to be updated). The limits now apply on number of assignments done during a single coordinator run rather than items in the queue at a given instant.
This change was done to:
- make the configs easier to use
- ensure that the configs actually take effect. In some cases (where loading happens quickly enough), these limits are constantly violated.

File: server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java [hunk 20]
```diff
@@ -470,134 +486,98 @@ public Set<DataSegment> getSegmentsMarkedToDrop()
...
-      if (scheduleTime < 0) {
-        scheduleTime = System.currentTimeMillis();
-        return false;
-      } else if (System.currentTimeMillis() - scheduleTime > config.getLoadTimeoutDelay().getMillis()) {
-        return true;
-      } else {
-        return false;
-      }
-    }
+    return System.currentTimeMillis() - holder.getFirstRequestTimeMillis()
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java:497]: I fear that this logic is broken.  The call to `getFirstRequestTimeMillis()` ends up actually setting the current timestamp.  But, I don't know why this check is only actually done once the request is sent to the downstream server.  Rather than relying on such side-effects we would be better off having an explicit lifecycle to the assignment and asking the holder itself how long it has been queued at the server.  I.e. `holder.getTimeElapsedSinceFirstRequestToServer()` or something like that, which can return `null` if there hasn't been any request to the server (and thus should never be timed out)

File: server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java [hunk 21]
```diff
@@ -26,24 +26,20 @@
...
 import java.util.List;
 import java.util.NavigableSet;
-import java.util.concurrent.ThreadLocalRandom;
 import java.util.stream.Collectors;
 
 public class RandomBalancerStrategy implements BalancerStrategy
 {
   @Override
-  public ServerHolder findNewSegmentHomeReplicator(DataSegment proposalSegment, List<ServerHolder> serverHolders)
+  public Iterator<ServerHolder> findNewSegmentHomeReplicator(DataSegment proposalSegment, List<ServerHolder> serverHolders)
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java:34]: Sometimes returning an `Iterator<>` is right, this signature feels like we might as well just return the `List<>` instead?

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java [hunk 22]
```diff
@@ -0,0 +1,472 @@
...
+
+    // Drop segment from unneeded tiers if requirement is met across target tiers
+    int loadedTargetReplicas = 0;
+    final Set<String> targetTiers = tierToReplicaCount.keySet();
+    for (String tier : targetTiers) {
+      loadedTargetReplicas += replicantLookup.getLoadedReplicants(segment.getId(), tier);
+    }
+    if (loadedTargetReplicas < minLoadedSegments) {
+      return;
+    }
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java:126]: I'm perhaps missing something here, but the logic seems to be saying "if the replication factor is set higher than 1, make sure that there are 2 replicas and no more", which seems... weird.  We should have the target number that the user told us to have?

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java [hunk 23]
```diff
@@ -0,0 +1,472 @@
...
+   * <ul>
+   *   <li>is not already serving or loading the segment</li>
+   *   <li>is not being decommissioned</li>
+   *   <li>has not already exceeded the load queue limit in this run</li>
+   *   <li>has available disk space</li>
+   * </ul>
+   */
+  public boolean canLoadSegment(ServerHolder server, DataSegment segment)
+  {
+    return server.canLoadSegment(segment)
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java:186]: I find myself wondering why the ServerHolder doesn't know about its own loadQueue?  Seems like this entire thing can be delegated.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java [hunk 24]
```diff
@@ -0,0 +1,472 @@
...
+    boolean dropCancelled = stateManager.cancelOperation(SegmentState.DROPPING, segment, server);
+    if (dropCancelled) {
+      return false;
+    }
+
+    if (canLoadSegment(server, segment)
+        && stateManager.loadSegment(segment, server, true)) {
+      return true;
+    } else {
+      log.makeAlert("Failed to broadcast segment for [%s]", segment.getDataSource())
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java:211]: Be careful with messages in this code.  "Failed to broadcast segment" is ambiguous about whether there was an issue with the server actually downloading the segment (definitely not the case given the code here) versus an issue with the coordinator believing that it is safe to assign the segment (much more likely).  We should be very explicit about what it is that is happening and, also, what we might expect the end user to do about it.

**Review by imply-cheddar — COMMENTED** [review]
I'm not done, but need to do something else and don't want the comments to be stuck in draft, so submitting for now to make the comments visible.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java (hunk 23 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java:186]: It does and I did start with that, in fact. But then did this because of laziness in fixing the tests to pass the config `maxSegmentsInNodeLoadingQueue` to every `ServerHolder`. 😅

I will fix this up.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java [hunk 25]
```diff
@@ -255,6 +253,8 @@ public DruidCoordinator(
     this.coordLeaderSelector = coordLeaderSelector;
     this.objectMapper = objectMapper;
     this.compactSegments = initializeCompactSegmentsDuty();
+    this.segmentStateManager =
+        new SegmentStateManager(serverInventoryView, segmentsMetadataManager, taskMaster.isHttpLoading());
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:257]: Agreed, I do have that in a separate patch. Will include it here.

File: server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java (hunk 20 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java:497]: Yes, that would be cleaner.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java (hunk 22 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java:126]: This is the check for queueing up drops in unwanted tiers. If there is even the minimum level of fault tolerance (2 replicas) in the wanted tiers, we can proceed with the drops on unwanted tiers while full replication continues on the wanted tiers.

The assignment to new target tiers is already done by this point.

File: server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java [hunk 26]
```diff
@@ -181,10 +183,10 @@ public int getNumberOfSegmentsInQueue()
   }
 
   @Override
-  public void loadSegment(final DataSegment segment, @Nullable final LoadPeonCallback callback)
+  public void loadSegment(final DataSegment segment, SegmentAction action, @Nullable final LoadPeonCallback callback)
   {
-    SegmentHolder segmentHolder = new SegmentHolder(segment, Action.LOAD, Collections.singletonList(callback));
-    final SegmentHolder existingHolder = segmentsToLoad.putIfAbsent(segment, segmentHolder);
+    QueuedSegment segmentHolder = new QueuedSegment(segment, action, callback);
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java:188]: Yes, I will rename `QueuedSegment` back to `SegmentHolder` as it is adding unnecessarily to the diff clutter.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCluster.java [hunk 27]
```diff
@@ -138,7 +138,7 @@ public Set<ServerHolder> getBrokers()
     return brokers;
   }
 
-  public Iterable<String> getTierNames()
+  public Set<String> getTierNames()
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCluster.java:141]: `DruidCluster` is immutable, and I ended up using this method just once in the new code. So I will just stick to using the original `Iterable<String>`.

File: server/src/main/java/org/apache/druid/server/coordinator/BalancerStrategy.java [hunk 28]
```diff
@@ -46,13 +46,18 @@
   ServerHolder findNewSegmentHomeBalancer(DataSegment proposalSegment, List<ServerHolder> serverHolders);
 
   /**
-   * Find the best server on which to place a {@link DataSegment} replica according to the balancing strategy
+   * Finds the best servers on which to place a replica of the {@code proposalSegment}
+   * according to the balancing strategy.
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/BalancerStrategy.java:50]: Okay, I will try to update the javadoc to reflect this distinction. But, as it happens, the same method is used for both "new/unavailable" segments as well "replicating/available" segments. (this would go away if we do a round-robin assignment in the first cycle for every segment) 
So I guess the method name should just be `findSegmentHomes`?

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java [hunk 29]
```diff
@@ -986,6 +887,7 @@ public DruidCoordinatorRuntimeParams run(DruidCoordinatorRuntimeParams params)
 
       stopPeonsForDisappearedServers(currentServers);
 
+      segmentStateManager.prepareForRun(params);
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:890]: Thanks for the suggestion! I was not happy with this myself.

File: server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java (hunk 21 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java:34]: Sounds good.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java (hunk 24 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java:211]: Yes, I am going through all the log messages to make sure they are less ambiguous.

File: server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java (hunk 21 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java:34]: On second thought, I wonder if `Iterator` is actually better. A caller should always iterate over the eligible servers in order and we get the benefit of the simple `hasNext` and `next` methods, rather than having to use `isEmpty` and `get`.

The one benefit I see with having a list is if we wanted to get the count of servers that were found to be eligible upfront (in case we wanted to report that).
What do you advise?

File: server/src/main/java/org/apache/druid/server/coordinator/duty/EmitClusterStatsAndMetrics.java [hunk 30]
```diff
@@ -43,41 +42,31 @@ public class EmitClusterStatsAndMetrics implements CoordinatorDuty
...
   private final String groupName;
   private final boolean isContainCompactSegmentDuty;
+  private final ServiceEmitter emitter;
 
-  public EmitClusterStatsAndMetrics(DruidCoordinator coordinator, String groupName, boolean isContainCompactSegmentDuty)
+  public EmitClusterStatsAndMetrics(
+      DruidCoordinator coordinator,
+      String groupName,
+      boolean isContainCompactSegmentDuty,
+      ServiceEmitter emitter
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/duty/EmitClusterStatsAndMetrics.java:57]: There is a single DI'd instance of `ServiceEmitter` that gets passed around. The emitter itself and the dimension map that it carries are immutable, so we should be good there.

Unfortunately, we didn't have any existing test that verified (all) the dimensions that were being emitted in a metric event. Such tests passing would have helped us validate this fully. But at least looking at the code, we shouldn't be breaking anything.

I will be doing some further cluster testing today to further verify the emitted metric events. We should be able to add some sim tests for this too.

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (AmatyaAvadhanula) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:33]: Yes

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java [hunk 31]
```diff
@@ -0,0 +1,72 @@
...
+package org.apache.druid.server.coordinator;
+
+import org.apache.druid.timeline.SegmentId;
+
+import java.util.ArrayList;
+import java.util.List;
+import java.util.concurrent.ConcurrentHashMap;
+
+/**
+ * Contains segments being loaded or replicated in a tier.
```
Comment (AmatyaAvadhanula) [inline server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:29]: Isn't it segments being moved or being replicated, but not as a primary replica?

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:33]: This is the current code:
https://github.com/apache/druid/blob/45dfd679e92e668172c470c37615e7447b601af1/server/src/main/java/org/apache/druid/server/coordinator/ReplicationThrottler.java#L73-L98

Here too a tier may be busy for a period greater than the lifetime, the lifetime would keep decreasing and we would keep alerting for this tier.

Saying that the load queue is stuck is probably not the correct message here and is causing the confusion. But AFAICT, the behaviour is unchanged.

Or are you talking about a `TierLoadingState` that doesn't have any segments inside and is empty? That has been handled like this:
```
// Reset state for inactive tiers
inactiveTiers.forEach(currentlyReplicating::remove);
```
The next time when a replica comes for this tier, a new entry would be created with a fresh lifetime value. The same handling has been done for moving segments as well.

File: server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java (hunk 6 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java:69]: Reverted.

File: server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java]: Reverted to use `SegmentHolder`.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java (hunk 22 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java]: Fixed this to always maintain the currently configured level of replication.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java (hunk 23 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java]: Fixed.

File: server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java (hunk 19 above)
[the remark this answers is not in the document]
Comment (AmatyaAvadhanula) [reply server/src/main/java/org/apache/druid/server/coordinator/TierLoadingState.java:33]: Apologies, the situation I'm thinking of can occur with the existing code as well.
I was thinking of timedOut in LoadQueue while making thing comment.

File: server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java (hunk 26 above)
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/CuratorLoadQueuePeon.java]: > That said, I would've expected the queue itself to return a QueuedSegment rather than something creating one of those before it's actually queued...

Do you mean like a `computeIfAbsent` rather than `putIfAbsent`?

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java (hunk 25 above)
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java]: Added.

File: server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java [hunk 32]
```diff
@@ -366,8 +372,9 @@ public void stop()
   }
 
   @Override
-  public void loadSegment(DataSegment segment, LoadPeonCallback callback)
+  public void loadSegment(DataSegment segment, SegmentAction action, LoadPeonCallback callback)
   {
+    Preconditions.checkArgument(action != SegmentAction.DROP);
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java]: Fixed.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java (hunk 29 above)
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java]: Fixed this to ensure that `SegmentStateManager` can never be used with improper initialization.

**Comment by kfaraz** [comment]
@imply-cheddar , thanks a lot for your review! I have addressed your comments.
More improvements to logging, metrics and docs will be included in a quick follow-up PR.

File: server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java (hunk 21 above)
Comment (imply-cheddar) [reply server/src/main/java/org/apache/druid/server/coordinator/RandomBalancerStrategy.java:34]: I don't feel overly strong about it.  Was more of a stream-of-conciousness/feeling comment.  So now that you've thought about it directly and like Iterator better, let's keep that.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java [hunk 33]
```diff
@@ -0,0 +1,261 @@
...
+      ServerHolder server,
+      boolean isPrimary,
+      ReplicationThrottler throttler
+  )
+  {
+    final String tier = server.getServer().getTier();
+    final LoadPeonCallback callback;
+    if (isPrimary) {
+      // Primary replicas are not subject to throttling
+      callback = null;
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:76]: What's the definition of "isPrimary"?  There really isn't a notion of "primary" or "secondary" replication, at least there shouldn't be.  The only semantic difference that should exist is

1) If the data is not available at all inside of the tier -> get the data loaded as fast as humanly possibly
2) If the data is available somewhere inside of the tier -> throttle the loading so that there is capacity in the cluster for other activities as well as under the assumption that this usually happens due to a failure and the node could just be flapping.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java [hunk 34]
```diff
@@ -0,0 +1,261 @@
...
+  }
+
+  private boolean canLoadReplica(String tier, ReplicationThrottler throttler)
+  {
+    if (!throttler.canAssignReplica(tier)) {
+      return false;
+    }
+
+    TierLoadingState tierState = currentlyReplicatingSegments.get(tier);
+    return tierState == null || tierState.getNumProcessingSegments() < throttler.getReplicationThrottleLimit();
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:258]: The latter part of this really "feels" like it's a throttling decision, but the throttler appears to not be making that decision?  I don't know that I have a specific suggestion, just, it caught my eye as I read the code.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java [hunk 35]
```diff
@@ -0,0 +1,261 @@
...
+    if (isPrimary) {
+      // Primary replicas are not subject to throttling
+      callback = null;
+    } else if (canLoadReplica(tier, throttler)) {
+      throttler.incrementAssignedReplicas(tier);
+
+      final TierLoadingState replicatingInTier = currentlyReplicatingSegments
+          .computeIfAbsent(tier, t -> new TierLoadingState(throttler.getMaxLifetime()));
+      replicatingInTier.addSegment(segment.getId(), server.getServer().getHost());
+      callback = success -> replicatingInTier.removeSegment(segment.getId());
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:83]: Is this just internal bookkeeping?  Or is it actually asking for the segment to be removed?

If it's internal bookkeeping, `.markCompleted()` might be a better name.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java [hunk 36]
```diff
@@ -0,0 +1,261 @@
...
+    }
+
+    try {
+      if (!server.startOperation(segment, SegmentState.LOADING)) {
+        return false;
+      }
+
+      server.getPeon().loadSegment(
+          segment,
+          isPrimary ? SegmentAction.LOAD_AS_PRIMARY : SegmentAction.LOAD_AS_REPLICA,
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:96]: Let's please kill this false notion of primary/replica and use words that actually align with the semantics that should exist.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java [hunk 37]
```diff
@@ -0,0 +1,261 @@
...
+          success -> {
+            // Drop segment only if:
+            // (1) segment load was successful on toServer
+            // AND (2) segment not already queued for drop on fromServer
+            // AND (3a) loading is http-based
+            //     OR (3b) inventory shows segment loaded on toServer
+
+            // Do not check the inventory with http loading as the HTTP
+            // response is enough to determine load success or failure
+            if (success
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:161]: If it wasn't successful, do we need to update the state that was set from the call to `fromServerPeon.markSegmentToDrop`?

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java (hunk 33 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:76]: Yes, I have made this change in a follow up PR which fully enables prioritisation and does away with the notion of primary and secondary. Should I include that here itself?

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java (hunk 36 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:96]: Okay, I will include those changes in this PR itself. I am going with the term LOAD vs PRIORITY_LOAD.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java (hunk 34 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:258]: Fair point. I will clean it up.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java (hunk 37 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java:161]: Yes, it happens through the `moveFinishCallback.execute()` in the `else` block.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java (hunk 33 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java]: Fixed.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java (hunk 36 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentStateManager.java]: Fixed.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentAction.java (hunk 15 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentAction.java]: Renamed to `LOAD`, `PRIORITY_LOAD`.

File: server/src/test/java/org/apache/druid/server/coordinator/RunRulesTest.java [hunk 38]
```diff
@@ -119,35 +118,39 @@ public void testOneTierTwoReplicantsWithStrictReplicantLimit()
...
+                .build()
+        )
         .build();
 
     DruidCoordinatorRuntimeParams afterParams = ruleRunner.run(params);
     CoordinatorStats stats = afterParams.getCoordinatorStats();
 
-    Assert.assertEquals(34L, stats.getTieredStat("assignedCount", "normal"));
-    Assert.assertEquals(10L, stats.getGlobalStat("totalNonPrimaryReplicantsLoaded"));
+    // There are 24 under-replicated segments, but only 10 replicas are assigned
```
Comment (imply-cheddar) [inline server/src/test/java/org/apache/druid/server/coordinator/RunRulesTest.java:152]: Is there a stat that can be looked at and asserted on the 24 number?

Comment (kfaraz) [reply server/src/test/java/org/apache/druid/server/coordinator/RunRulesTest.java:152]: Added.

File: server/src/test/java/org/apache/druid/server/coordinator/BalancerStrategyTest.java [hunk 39]
```diff
@@ -84,29 +84,32 @@ public void findNewSegmentHomeReplicatorNotEnoughSpace()
         new LoadQueuePeonTester());
     serverHolders = new ArrayList<>();
     serverHolders.add(serverHolder);
-    final ServerHolder foundServerHolder = balancerStrategy.findNewSegmentHomeReplicator(proposedDataSegment, serverHolders);
     // since there is not enough space on server having available size 10L to host a segment of size 11L, it should be null
-    Assert.assertNull(foundServerHolder);
+    Assert.assertFalse(
+        balancerStrategy.findNewSegmentHomeReplicator(proposedDataSegment, serverHolders)
+                        .hasNext()
+    );
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/test/java/org/apache/druid/server/coordinator/BalancerStrategyTest.java]: Removed as we don't need the comment anymore.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java [hunk 40]
```diff
@@ -156,4 +161,45 @@ public Object2LongMap<String> getBroadcastUnderReplication(SegmentId segmentId)
...
+    int moving;
+
+    void addLoaded()
+    {
+      ++loaded;
+    }
+
+    void addQueued(SegmentState state)
+    {
+      switch (state) {
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java]: Fixed.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java [hunk 41]
```diff
@@ -0,0 +1,460 @@
...
+      if (!server.isServingSegment(segment)) {
+        // ignore this server
+      } else if (server.isDecommissioning()) {
+        eligibleDyingServers.add(server);
+      } else {
+        eligibleLiveServers.add(server);
+      }
+    }
+
+    // Drop as many replicas as possible from decommissioning servers
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java:334]: Thanks for the suggestion. Will include this changes along with the changes for full node replication in a follow up PR.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java [hunk 42]
```diff
@@ -0,0 +1,460 @@
...
+  {
+    final String tier = toServer.getServer().getTier();
+    if (!fromServer.getServer().getTier().equals(tier)) {
+      return false;
+    }
+
+    if (fromServer.isServingSegment(segment)) {
+      // Segment is loaded on fromServer, move it to toServer
+      return stateManager.moveSegment(segment, fromServer, toServer, replicationThrottler.getMaxLifetime());
+    } else if (!fromServer.isLoadingSegment(segment)) {
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentLoader.java]: Yeah, it does make reading a little difficult. Fixed this here and a couple other places where I had used them.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentHolder.java [hunk 43]
```diff
@@ -0,0 +1,172 @@
...
+  {
+    firstRequestMillis.compareAndSet(0L, System.currentTimeMillis());
+  }
+
+  public boolean isRequestSentToServer()
+  {
+    return firstRequestMillis.get() > 0;
+  }
+
+  public long getMillisSinceFirstRequestToServer()
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentHolder.java]: Thanks for the suggestion!

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentAction.java [hunk 44]
```diff
@@ -0,0 +1,33 @@
...
+ * Represents actions that can be performed on a server for a single segment.
+ * <p>
+ * The different action types can be used to prioritize items in a LoadQueuePeon.
+ */
+public enum SegmentAction
+{
+  DROP,
+  LOAD,
+  REPLICATE,
+  MOVE_TO,
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentAction.java]: Added.

File: server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java [hunk 45]
```diff
@@ -380,10 +407,12 @@ public void loadSegment(DataSegment segment, LoadPeonCallback callback)
       }
 
       SegmentHolder holder = segmentsToLoad.get(segment);
-
       if (holder == null) {
         log.trace("Server[%s] to load segment[%s] queued.", serverId, segment.getId());
-        segmentsToLoad.put(segment, new LoadSegmentHolder(segment, callback));
+        queuedSize.addAndGet(segment.getSize());
+        holder = new SegmentHolder(segment, action, callback);
+        segmentsToLoad.put(segment, holder);
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/HttpLoadQueuePeon.java:415]: We might still need the `segmentsToLoad` and `segmentsToDrop` atleast for now because the balancer strategies use these to compute cost. This can be done with `queuedSegments` itself but we might have to filter out the relevant entries on every cost computation. 

I do have a follow up PR which deals with the fixes in the strategy. I will try to clean up this part there.

File: server/src/main/java/org/apache/druid/server/coordinator/BalancerStrategy.java (hunk 28 above)
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/BalancerStrategy.java:50]: Updated.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java [hunk 46]
```diff
@@ -888,26 +799,101 @@ public DruidCoordinatorRuntimeParams run(DruidCoordinatorRuntimeParams params)
...
+          replicationThrottleLimit, throttlePercentage, maxSegmentsToMove
+      );
+
+      return CoordinatorDynamicConfig.builder()
+                                     .withMaxSegmentsInNodeLoadingQueue(0)
+                                     .withReplicationThrottleLimit(replicationThrottleLimit)
+                                     .withMaxSegmentsToMove(maxSegmentsToMove)
+                                     .withUseRoundRobinSegmentAssignment(true)
+                                     .withUseBatchedSegmentSampler(true)
+                                     .withEmitBalancingStats(false)
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:863]: Instead of recomputing the dynamic config, I would've preferred that there be a separate config which houses all of the things that are recomputed and that reference gets updated/changed.  The `DynamicConfig` object itself should really only be mutated by users changing config values.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java [hunk 47]
```diff
@@ -888,26 +799,101 @@ public DruidCoordinatorRuntimeParams run(DruidCoordinatorRuntimeParams params)
...
+        );
+      }
+
+      if (cancelledCount.get() > 0) {
+        log.info(
+            "Cancelled [%d] load/move operations on [%d] decommissioning servers.",
+            cancelledCount.get(), decommissioningServers.size()
+        );
+      }
     }
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:897]: I would've expected that the act of decommissioning would put the queue into a state where it will only accept DROP requests and then dropped the load queue immediately.  It seems weird to me that this is logic handled in this class instead.  The only thing I'd expect a CoordinatorDuty to do about it is to look for decomissioning servers and move the segments away.

File: server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java [hunk 48]
```diff
@@ -155,128 +211,161 @@ public long getAvailableSize()
...
+    // Remove from projected if load is cancelled or drop is started, add otherwise
+    if (addToQueue ^ action.isLoad()) {
+      projectedSegments.remove(segment);
+    } else {
+      projectedSegments.add(segment);
     }
 
-    return server.getType().compareTo(serverHolder.server.getType());
+    return true;
+  }
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java]: nit: the boolean parameter here feels really weird.  Why not just have 2 methods:

```
addQueuedSegment()
removeQueuedSegment()
```

File: server/src/main/java/org/apache/druid/server/coordinator/StrategicSegmentAssigner.java [hunk 49]
```diff
@@ -0,0 +1,577 @@
...
+    final boolean assigned = loadQueueManager.loadSegment(segment, server, action);
+
+    if (!assigned) {
+      incrementSkipStat(Stats.Segments.ASSIGN_SKIPPED, "Encountered error", segment, tier);
+    } else if (isAlreadyLoadedOnTier) {
+      replicationThrottler.incrementAssignedReplicas(tier);
+    }
+
+    return assigned;
+  }
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/StrategicSegmentAssigner.java:514]: boolean police again: is it really better to have this boolean and a bunch of checks strewn through this code than to just have a `replicateSegment` method and a `loadSegment` method?

File: server/src/main/java/org/apache/druid/server/coordinator/StrategicSegmentAssigner.java [hunk 50]
```diff
@@ -0,0 +1,577 @@
...
+
+  private ReplicationThrottler createReplicationThrottler(CoordinatorDynamicConfig dynamicConfig)
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/StrategicSegmentAssigner.java:516]: Can this be static?  I think it can and maybe should be.  If it cannot be static, please rename to `initializeReplicationThrottler()` to help indicate that it is intended for initialization and not as a factory to be called multiple times from the same object.

File: server/src/main/java/org/apache/druid/server/coordinator/loadqueue/HttpLoadQueuePeon.java [hunk 51]
```diff
@@ -470,134 +517,127 @@
...
 
-    @Override
-    public void requestFailed(String failureCause)
+    CoordinatorStat getStatForAction(SegmentAction action)
     {
-      queuedSize.addAndGet(-getSegment().getSize());
-      super.requestFailed(failureCause);
-    }
-  }
+      switch (action) {
```
[the remark this answers is not in the document]
Comment (imply-cheddar) [reply server/src/main/java/org/apache/druid/server/coordinator/loadqueue/HttpLoadQueuePeon.java:613]: This codeQL seems legitimate?

**Review by imply-cheddar — APPROVED** [review]
Overall, I don't like the introduction of so many magical boolean parameters on methods.  It makes it more difficult to understand what is happening.  

Additionally, there is commentary in here, but I'm not sure any of them necessarily need to block this PR, it's all mostly just hygiene stuff that could be done later too (especially given that this PR is already so large and has existed for so long).

Given that we've run this in some legitimate production clusters as well as some performance environments and it's done what we expect, I'm approving this.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java [hunk 52]
```diff
@@ -125,49 +117,85 @@ public int getMovingReplicas(SegmentId segmentId, String tier)
    * Number of replicas of the segment which are safely loaded on the given tier
    * and are not being dropped.
    */
-  public int getLoadedReplicas(SegmentId segmentId, String tier)
+  public int getLoadedNotDroppingReplicas(SegmentId segmentId, String tier)
+  {
+    ReplicaCount count = replicaCounts.get(segmentId, tier);
+    return (count == null) ? 0 : count.loadedNotDropping();
+  }
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java]: Yes, that would be neater, thanks!

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java (hunk 46 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:863]: Yeah, I was not too keen on this myself. I considered putting this logic inside `DruidCoordinatorRuntimeParams` itself but I guess the best thing to do is just have a separate config object, as you suggest.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java (hunk 47 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:897]: Cancelling all loads on decomissioning servers is faster than moving the segments away.

Balancing moves are subject to the cost computation performance in `BalancerStrategy` and thus are typically limited (`maxSegmentsToMove <= 1000`). With unlimited load queues, there can potentially be many more segments in the load queue of decommissioning servers.

With cancellation of loads on decommissioning servers, these segments would immediately be (round-robin) assigned to active servers in this run itself.

Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java:897]: We are doing this cancellation in this duty (as opposed to `RunRules` or `BalanceSegments`) since the `SegmentReplicantLookup` is constructed right after this method and thus the Coordinator knows in this run itself that some segments are under-replicated and it needs to queue up some loads on active servers.

File: server/src/main/java/org/apache/druid/server/coordinator/StrategicSegmentAssigner.java (hunk 49 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/StrategicSegmentAssigner.java:514]: The boolean here is used to determine if the assignment was successful or not, not distinguish between load and replicate. I can add a comment to that effect. The boolean status is used downstream for other decisions, like counting the number of successful assignments so far.

Please let me know if you think some other approach would be cleaner.

File: server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java [hunk 53]
```diff
@@ -428,66 +489,36 @@ public boolean equals(Object o)
...
+           && maxNonPrimaryReplicantsToLoad == that.maxNonPrimaryReplicantsToLoad
+           && useRoundRobinSegmentAssignment == that.useRoundRobinSegmentAssignment
+           && pauseCoordination == that.pauseCoordination
+           && Objects.equals(
+               specificDataSourcesToKillUnusedSegmentsIn,
+               that.specificDataSourcesToKillUnusedSegmentsIn)
+           && Objects.equals(
+               dataSourcesToNotKillStalePendingSegmentsIn,
+               that.dataSourcesToNotKillStalePendingSegmentsIn)
+           && Objects.equals(decommissioningNodes, that.decommissioningNodes);
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java:514]: Thanks for catching this, must have missed adding it.

File: server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java [hunk 54]
```diff
@@ -194,21 +211,46 @@ public CoordinatorDynamicConfig(
...
     }
+
+    debugDimensions.forEach(
+        (dimensionName, value) -> {
+          Dimension dimension = nameToDimension.get(dimensionName);
+          if (dimension != null && value != null) {
+            validDebugDimensions.put(dimension, value);
+          }
+        }
+    );
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/CoordinatorDynamicConfig.java:251]: Don't know what I had done it in such a round about way in the first place 😅 , thanks for pointing this out!

File: server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java (hunk 48 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java]: Yeah, the boolean here is stupid, it's always `true`, must have been doing some other things originally. With the recent changes, it would have become redundant. Can get rid of it without breaking up the method too.

File: server/src/main/java/org/apache/druid/server/coordinator/loadqueue/HttpLoadQueuePeon.java (hunk 51 above)
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/loadqueue/HttpLoadQueuePeon.java:613]: No, it is okay, `MOVE_FROM` operations aren't supposed to come to the peon. So the next line will throw an IAE. I can just have the `default` case throw the exception too so that `CodeQL` does not complain.

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java [hunk 55]
```diff
@@ -125,49 +117,85 @@ public int getMovingReplicas(SegmentId segmentId, String tier)
...
+          Object2LongOpenHashMap<String> datasourceToUnderReplicated = (Object2LongOpenHashMap<String>)
+              tierToUnderReplicated.computeIfAbsent(tier, ds -> new Object2LongOpenHashMap<>());
+          datasourceToUnderReplicated.addTo(segment.getDataSource(), underReplicated);
+        }
+      });
     }
-    return perTier;
+
+    return tierToUnderReplicated;
   }
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java]: Hmm, let me see what can be done here. 

It turned out like this mostly because it is a direct translation of the flag `computeUsingClusterView` passed in from `OverlordResource` to `DruidCoordinator` to `SegmentReplicantLookup`.

File: server/src/main/java/org/apache/druid/server/coordinator/balancer/BalancerStrategy.java [hunk 56]
```diff
@@ -36,77 +39,65 @@
...
+   *                             already loaded on a server.
+   * @return Iterator over {@link BalancerSegmentHolder}s, each of which contains
+   * a segment picked for moving and the server currently serving/loading it.
    */
   default Iterator<BalancerSegmentHolder> pickSegmentsToMove(
       List<ServerHolder> serverHolders,
       Set<String> broadcastDatasources,
-      int reservoirSize
+      int maxSegmentsToPick,
+      boolean pickLoadingSegments
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/balancer/BalancerStrategy.java]: Updated:
1. Removed these methods from `BalancerStrategy`
2. Added 2 methods to `ReservoirSegmentSampler`, `pickMovableLoadingSegment` and `pickMovableLoadedSegments`, which are used directly by the coordinator duty

File: server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java [hunk 57]
```diff
@@ -125,49 +117,85 @@ public int getMovingReplicas(SegmentId segmentId, String tier)
...
+  public int getLoadedReplicas(SegmentId segmentId, boolean includeDropping)
   {
     final Map<String, ReplicaCount> allTiers = replicaCounts.row(segmentId);
     int totalLoaded = 0;
     for (ReplicaCount count : allTiers.values()) {
-      totalLoaded += count.safelyLoaded();
+      totalLoaded += includeDropping ? count.loaded : count.loadedNotDropping();
     }
     return totalLoaded;
   }
```
[the remark this answers is not in the document]
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/SegmentReplicantLookup.java]: Updated.

File: server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java (hunk 46 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/coordinator/DruidCoordinator.java]: Added a new `SegmentLoadingConfig` which contains the recomputed values and is used by the coordinator duties.

File: server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java [hunk 58]
```diff
@@ -337,29 +347,42 @@ private SegmentAction simplify(SegmentAction action)
...
-      sizeOfLoadingSegments += sizeDelta;
+      sizeOfLoadingSegments += segment.getSize();
     } else if (action == SegmentAction.DROP) {
-      sizeOfDroppingSegments += sizeDelta;
+      sizeOfDroppingSegments += segment.getSize();
+    } else {
+      // MOVE_FROM actions graduate to DROP after the corresponding MOVE_TO has finished
+      // Do not consider size delta until then, otherwise we might over-assign the server
     }
+  }
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java]: After the change to remove teh `addToQueue` boolean, you now have the exact same if clause at the beginning of 2 subsequence if statements.  You should be able to make it

```
if (action.isLoad()) {
  projectedSegments.add(segment);
  sizeOfLoadingSegments += segment.getSize();
} else {
  projectedSegments.remove(segment);
  // The current else block could be from a DROP or a MOVE_FROM.  The MOVE_FROM will eventually graduate to
  // DROP after ...
  if (action == SegmentAction.DROP) {
    sizeOfDroppingSegments += segment.getSize()
  }
}
```

File: server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java [hunk 59]
```diff
@@ -337,29 +347,42 @@ private SegmentAction simplify(SegmentAction action)
...
       projectedSegments.add(segment);
     }
 
-    return true;
+    if (action.isLoad()) {
+      sizeOfLoadingSegments -= segment.getSize();
+    } else if (action == SegmentAction.DROP) {
+      sizeOfDroppingSegments -= segment.getSize();
+    }
   }
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/ServerHolder.java]: Same comments here, basically have the same if statement twice.

File: server/src/main/java/org/apache/druid/server/coordinator/balancer/ReservoirSegmentSampler.java [hunk 60]
```diff
@@ -21,28 +21,86 @@
...
+   *
+   * @param serverHolders        Set of historicals to consider for picking segments
+   * @param maxSegmentsToPick    Maximum number of segments to pick
+   * @param broadcastDatasources Segments belonging to these datasources will not
+   *                             be picked for balancing, since they should be
+   *                             loaded on all servers anyway.
+   * @return Iterator over {@link BalancerSegmentHolder}s, each of which contains
+   * a segment picked for moving and the server currently loading it.
+   */
+  public static List<BalancerSegmentHolder> pickMovableLoadingSegmentsFrom(
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/balancer/ReservoirSegmentSampler.java:52]: nit: the different in name is soooo minute it took me a long time to realize.  One is `ing` and the other is `ed`.

Is there a reason not to expose the 4-argument method as `public` and have the call sites pass in one of the two lambdas?  It looks like there's only a single call-site for each of them except for tests.

That or maybe try to make the names a bit more different from each other.

File: server/src/main/java/org/apache/druid/server/coordinator/loading/SegmentLoadingConfig.java [hunk 61]
```diff
@@ -0,0 +1,124 @@
...
+  private final int maxReplicaAssignmentsInRun;
+  private final int maxLifetimeInLoadQueue;
+
+  private final int maxSegmentsToMove;
+  private final int percentDecommSegmentsToMove;
+
+  private final boolean useRoundRobinSegmentAssignment;
+  private final boolean emitBalancingStats;
+
+  public SegmentLoadingConfig(CoordinatorDynamicConfig dynamicConfig, int numUsedSegments)
```
Comment (imply-cheddar) [inline server/src/main/java/org/apache/druid/server/coordinator/loading/SegmentLoadingConfig.java:44]: design nit: a constructor should generally define the "dependency relationship" of a class.  I.e. the things passed in on the constructor are the things that the current class is dependent upon.  This constructor is doing a bunch of work, that work is dependent on the `CoordinatorDynamicConfig` object, but `SegmentLoadingConfig` is not dependent on the object.

In this case, it would be preferable for this to be a static method and the constructor just take all of the various values.

**Review by cheddar — APPROVED** [review]
making my gray check green.
