### PR TITLE
Fix Hadoop Indexing CLI for versions JDK v9+

### LINKED ISSUE #17574: Fix Hadoop Indexing CLI for versions JDK v9+
### Affected Versions

All Druid versions which allow JDK v9+

### Description

For JDK v9+ this job will fail as URLClassloader is no longer the default classloader. Additionally, with the introduction of the jmod system, the job failed to find the correct JDK-included modules because the new classloader constructed for the job didn't reference the system classloader. Adding ClassLoader.getSystemClassLoader() as the parent classloader fixes this.

### PR DESCRIPTION
**Pull request by jtuglu-netflix**
Fixes #17574.

### Description

For JDK v9+ this job will fail as URLClassloader is no longer the default classloader. Additionally, with the introduction of the jmod system, the job failed to find the correct JDK-included modules because the new classloader constructed for the job didn't reference the system classloader. Adding ClassLoader.getSystemClassLoader() as the parent classloader fixes this.

#### Release note

Fix Hadoop Indexing CLI for versions JDK v9+

<hr>

##### Key changed/added classes in this PR
 * `services/src/main/java/org/apache/druid/cli/CliHadoopIndexer.java`

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] a release note entry in the PR description.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: services/src/main/java/org/apache/druid/cli/CliHadoopIndexer.java [hunk 1]
```diff
@@ -84,9 +86,13 @@ public void run()
         extensionURLs.addAll(Arrays.asList(extensionLoader.getURLs()));
       }
 
-      final List<URL> nonHadoopURLs = Arrays.asList(
-          ((URLClassLoader) CliHadoopIndexer.class.getClassLoader()).getURLs()
-      );
+      final List<URL> nonHadoopURLs;
+      final ClassLoader indexerLoader = CliHadoopIndexer.class.getClassLoader();
```
Comment (cryptoe) [inline services/src/main/java/org/apache/druid/cli/CliHadoopIndexer.java:90]: We have removed java 8 support. So we donot need to support JDK 8 and below. so the if on line 91 can be removed.

**Review by maytasm — APPROVED** [review]

**Comment by jtuglu-netflix** [comment]
Can we merge this? cc @maytasm

**Comment by maytasm** [comment]
@jtuglu-netflix Merged. Thanks!
