### PR TITLE
fix bug with json_value expression array extraction

### LINKED ISSUE #14374: JSON_VALUE extract as weird values for JSON_OBJECT
### Affected Version

26.0.0

### Description

image

`
with nested_data  as (
  SELECT
    JSON_OBJECT('k1':ARRAY['v1','v2'],'k2':'v3','k3':4) json_arr
)
SELECT 
  JSON_VALUE(json_arr,'$.k1') k1,
  JSON_VALUE(json_arr,'$.k1' RETURNING VARCHAR ARRAY) k1_string_arr,
  JSON_VALUE(json_arr,'$.k1' RETURNING INTEGER ARRAY) k1_int_arr,
  JSON_VALUE(json_arr,'$.k2') k2,
  JSON_VALUE(json_arr,'$.k2' RETURNING VARCHAR ARRAY) k2_string_arr,
  JSON_VALUE(json_arr,'$.k2' RETURNING INTEGER ARRAY) k2_int_arr,
  JSON_VALUE(json_arr,'$.k3') k3,
  JSON_VALUE(json_arr,'$.k3' RETURNING VARCHAR ARRAY) k3_string_arr,
  JSON_VALUE(json_arr,'$.k3' RETURNING INTEGER ARRAY) k3_int_arr
from nested_data
`

When i want to extract values from a json object ( SQL as above ), it will get some unexpected and weird values.

In order to understand more easily, the object can be equivalent to json as below:
`
{
  "k1": [
    "v1",
    "v2"
  ],
  "k2": "v3",
  "k3": 4
}
` 
image

What i expect is as below:

#1 - `JSON_VALUE(json_arr,'$.k1')` = `['v1','v2']`, actual is `empty`
#2 - `JSON_VALUE(json_arr,'$.k1' RETURNING VARCHAR ARRAY)` = `['v1','v2']`, actual is `null`
#3 - `JSON_VALUE(json_arr,'$.k2' RETURNING VARCHAR ARRAY)` = `null`, actual is `['v3']`
#4 - `JSON_VALUE(json_arr,'$.k2' RETURNING INTEGER ARRAY)` = `null`, actual is `[null]`
#5 - `JSON_VALUE(json_arr,'$.k3' RETURNING VARCHAR ARRAY)` = `null`, actual is `['4']`
#6 - `JSON_VALUE(json_arr,'$.k3' RETURNING INTEGER ARRAY)` = `null`, actual is `[4]`

I can understand results of #3#4#5#6 might be converted for type implicitly, but what's the cause for #1 and #2?

### PR DESCRIPTION
**Pull request by clintropolis**
Mostly fixes #14374. The first expression will currently throw a class cast exception because it is trying to cast `ARRAY<STRING>` to `STRING` because it seems that by default the query plans to 'RETURNING VARCHAR' instead of using JSON_VALUE_ANY, will work on resolving that in a different PR.

### Description
The `JSON_VALUE` expression (e.g. when not using the specialized `NestedFieldVirtualColumn`) was using a stale method that predated support for returning arrays, which would always return null if the value was an object or an array. This method has been removed so that the `JSON_VALUE` expression now matches the behavior of `JSON_VALUE` using `NestedFieldVirtualColumn`.
<hr>

This PR has:

- [x] been self-reviewed.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/segment/column/TypeSignature.java [hunk 1]
```diff
@@ -167,6 +167,12 @@ default boolean isArray()
     return getType().isArray();
   }
 
+  @JsonIgnore
+  default boolean isArrayPrimitive()
```
Comment (imply-cheddar) [inline processing/src/main/java/org/apache/druid/segment/column/TypeSignature.java:171]: Nit: "primitive array" would be the normal order of those words.  "array primitive" makes it sound like there's some primitive that is an array?

**Review by imply-cheddar — APPROVED** [review]
