### PR TITLE
Fix some potential resource leak

### LINKED ISSUE #18086: ResultSet may lead to resource leak in DerbyConnector
`org.apache.druid.metadata.storage.derby.DerbyConnector#tableHasColumn`  ResultSet columns

Image

`ResultSet` implements the java.lang.AutoCloseable interface. This means it is a resource that holds onto database resources
It seems that `ResultSet` is never closed,  which may lead to resource leak. I suggest to use a `try-with-resources block`, which ensures the ResultSet is automatically closed.

### PR DESCRIPTION
**Pull request by xcx1r3**
Fixes #18086.

### Description

I've used `try-with` stmt to close the resource mentioned in #18086, and  found some other leaks in this project and fix them with try-with too.

#### Release note

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentKiller.java [hunk 1]
```diff
@@ -72,49 +72,50 @@ public void kill(DataSegment segment) throws SegmentLoadingException
...
       String filename = segmentPath.getName();
-      final FileSystem fs = segmentPath.getFileSystem(config);
-      if (!filename.endsWith(".zip")) {
-        throw new SegmentLoadingException("Unknown file type[%s]", segmentPath);
-      } else {
-
-        if (!fs.exists(segmentPath)) {
-          log.warn("Segment path [%s] does not exist", segmentPath);
-          return;
+      try (final FileSystem fs = segmentPath.getFileSystem(config)) {
```
Comment (kfaraz) [inline extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentKiller.java]: There's already a try on line 73. Maybe just update that to assign the filesystem variable `fs`.
You can move the assignment `filename = segmentPath.getName()` outside the try.

Comment (AROP-REPLICATION) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentKiller.java]: Thanks, I moved it here

File: extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentKiller.java [hunk 2]
```diff
@@ -70,52 +70,51 @@ public void kill(DataSegment segment) throws SegmentLoadingException
...
-              org.apache.druid.java.util.common.StringUtils.format(
-                  "%s_%sdescriptor.json",
-                  zipParts[0],
-                  zipParts.length == 2 ? "" : zipParts[1] + "_"
-              )
-          );
-        }
-
-        if (!fs.delete(segmentPath, false)) {
-          throw new SegmentLoadingException("Unable to kill segment, failed to delete [%s]", segmentPath.toString());
```
Comment (kfaraz) [inline extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentKiller.java]: I don't think anything has changed on these lines. Could you please check the formatting and revert any superfluous change from the patch?

Comment (AROP-REPLICATION) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentKiller.java]: sry for the wrong formatting , this time should be right.

File: server/src/main/java/org/apache/druid/server/initialization/jetty/JettyServerModule.java [hunk 3]
```diff
@@ -500,8 +500,7 @@ private static int getMaxJettyAcceptorsSelectorsNum(DruidNode druidNode)
   private static int getTCPAcceptQueueSize()
   {
     if (SystemUtils.IS_OS_LINUX) {
-      try {
-        BufferedReader in = Files.newBufferedReader(Paths.get("/proc/sys/net/core/somaxconn"));
+      try (BufferedReader in = Files.newBufferedReader(Paths.get("/proc/sys/net/core/somaxconn")) ) {
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/server/initialization/jetty/JettyServerModule.java]:
```suggestion
      try (BufferedReader in = Files.newBufferedReader(Paths.get("/proc/sys/net/core/somaxconn"))) {
```

Comment (kfaraz) [reply server/src/main/java/org/apache/druid/server/initialization/jetty/JettyServerModule.java]: This caused checkstyle to fail.

**Comment by kfaraz** [comment]
Thanks for contributing to Apache Druid, @xcx1r3 !
