### PR TITLE
Fix CombiningFirehose compatibility

### LINKED ISSUE #9389: CombiningFirehoseFactory cannot be cast to FiniteFirehoseFactory
I am attempting to combing two datasources using the CombiningFirehoseFactory
For reference, I am following the [update data tutorial](https://druid.apache.org/docs/latest/tutorials/tutorial-update-data.html)

My ingestion spec looks like this 
`{
  "type" : "index",
  "spec" : {
    "dataSchema" : {
      "dataSource" : "updates-tutorial",
      "parser" : {
        "type" : "string",
        "parseSpec" : {
          "format" : "json",
          "dimensionsSpec" : {
            "dimensions" : [
              "animal"
            ]
          },
          "timestampSpec": {
            "column": "timestamp",
            "format": "iso"
          }
        }
      },
      "metricsSpec" : [
        { "type" : "count", "name" : "count" },
        { "type" : "longSum", "name" : "number", "fieldName" : "number" }
      ],
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "hour",
        "queryGranularity" : "minute",
        "intervals" : ["2018-01-01/2018-01-03"],
        "rollup" : false
      }
    },
    "ioConfig" : {
      "type" : "index",
      "firehose" : {
        "type": "combining",
        "delegates": [
          {
            "type"    : "ingestSegment",
            "dataSource"   : "s1",
            "interval" : "2018-01-01/2018-01-03"
          },
          {
            "type" : "ingestSegment",
            "dataSource"   : "s2",
            "interval" : "2018-01-01/2018-01-03"
          }
        ]
      },
      "appendToExisting" : false
    },
    "tuningConfig" : {
      "type" : "index",
      "maxRowsPerSegment" : 5000000,
      "maxRowsInMemory" : 25000
    }
  }
}`

After reading into the code a bit, I believe that CombiningFirehoseFactory allows you to combine multiple datasources

But when i submit the task, i get the following error

`2020-02-21T11:35:39,222 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.common.task.IndexTask - Encountered exception in NOT_STARTED.
java.lang.ClassCastException: org.apache.druid.segment.realtime.firehose.CombiningFirehoseFactory cannot be cast to org.apache.druid.data.input.FiniteFirehoseFactory
	at org.apache.druid.indexing.common.task.IndexTask$IndexIOConfig.getNonNullInputSource(IndexTask.java:1148) ~[druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.common.task.IndexTask.runTask(IndexTask.java:477) [druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.common.task.AbstractBatchIndexTask.run(AbstractBatchIndexTask.java:138) [druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.17.0.jar:0.17.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]`

I am not sure, if this is a issue with the datasource of my selection or config issue.
In the interim, i have tried to alternate the datasource from `ingestSegment` to `local` as well, but i continue to get the same error. 

Would really appreciate if i could get any help on this or if someone can help rectify my understanding on the matter.

### PR DESCRIPTION
**Pull request by a2l007**
Fixes #9389.

This fixes `CombiningFirehose` to be compatible with `FiniteFirehoseFactory` . Will look into adding `index_parallel` support for this.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

<hr>

### CODE REVIEW

**Comment by suneet-s** [comment]
Thanks for this fix @a2l007 ! I see [this comment](https://github.com/apache/druid/issues/9389#issuecomment-633253290) that indicates one of the tutorial specs were broken before your fix. 

Can you add an integration test for this so that we don't break the tutorial going forward.

**Comment by a2l007** [comment]
Thanks for checking @suneet-s 
I've added an integration test

File: server/src/main/java/org/apache/druid/segment/realtime/firehose/CombiningFirehoseFactory.java [hunk 1]
```diff
@@ -33,11 +36,12 @@
 import java.io.IOException;
 import java.util.Iterator;
 import java.util.List;
+import java.util.stream.Stream;
 
 /**
  * Creates firehose that combines data from different Firehoses. Useful for ingesting data from multiple sources.
  */
-public class CombiningFirehoseFactory implements FirehoseFactory<InputRowParser>
+public class CombiningFirehoseFactory implements FiniteFirehoseFactory<InputRowParser, List<FirehoseFactory>>
```
Comment (suneet-s) [inline server/src/main/java/org/apache/druid/segment/realtime/firehose/CombiningFirehoseFactory.java:44]: I looked for implementations of `FirehoseFactory` that do not also implement `FiniteFirehoseFactory` and I found a few... eg. `ClippedFirehoseFactory`, `FixedCountFirehoseFactory`, etc.

I think the underlying problem is in `IndexIOConfig#getNonNullInputSource`

`IndexIOConfig` accepts a FirehoseFactory, but [getNonNullInputSource](https://github.com/apache/druid/blob/f6594fff608d4b2e071c7bdd6d86d7f87398ce4f/indexing-service/src/main/java/org/apache/druid/indexing/common/task/IndexTask.java#L1135) expects a `FiniteFirehoseFactory`.

I wonder if we could fix this by creating an adapter that translates any FirehoseFactory into a non-splittable FiniteFirehoseFactory (ie. the same functionality you've implemented in this class).

I understand that the FirehoseFactories are deprecated, so I'm open to other ways of fixing the broken quickstart material as well - can we update the spec used so that the combining firehose factory works without a code change?

Comment (a2l007) [reply server/src/main/java/org/apache/druid/segment/realtime/firehose/CombiningFirehoseFactory.java:44]: I feel that adding a non-splittable adapter would apply only to `CombiningFirehoseFactory`.  `ClippedFirehoseFactory` , `TimedShutoffFirehoseFactory` and `FixedCountFirehoseFactory` can be potentially splittable if the delegate `FirehoseFactory` is splittable, it's just that they haven't been fixed yet. 
What we actually need is for index_parallel to support nested InputSource say DelegateInputSource. The delegate FirehoseFactories such as the ones listed above can then be easily provided their equivalent InputSource implementations. I've been looking at adding this support and hopefully can have a proposal out once I have something.

**Comment by suneet-s** [comment]
Verified by running the tutorial locally. Thanks again @a2l007 !
