### PR TITLE
Avoid OOM-killing query if result-level caching fails

### LINKED ISSUE #17651: ResultLevelCache Population OOM
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

31.0.1

### Description

Currently, if a query's result set size is large enough, the result set serializer can OOM [here](https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java#L294) when allocating large buffers. Not only will this affect one-off queries, but this causes a crash-loop on Broker nodes if they are attempting to make/cache large SegmentMetadata queries on boot.

### PR DESCRIPTION
**Pull request by jtuglu-netflix**
Fixes #17651.

### Description

Currently, result-level caching which attempts to allocate a large enough buffer to store query results will overflow the Integer.MAX_INT capacity. `ByteArrayOutputStream` materializes this case as an `OutOfMemoryError`, which is not caught and terminates the query. This limits the allocated buffer for storing query results to whatever is set in `CacheConfig.getResultLevelCacheLimit()`. Although we do a check comparing buffer size to `CacheConfig.getResultLevelCacheLimit()` [here](https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java#L295), this comes after the exception is thrown and is too late to gracefully catch the issue.

##  **Important Note**
I opted to use `LimitedOutputStream` here as it is already used with `ByteArrayOutputStream`. While ok in QueryRunners (single-threaded), this still is less-than-ideal in the general case because it doesn't guarantee strict consistency between overflow exception delivery and ordering of writes to the buffer(see another example below). As such, this class in general is \*not\* thread-safe and I think should be refactored to account for this. This is because every case of `LimitedOutputStream` already uses `ByteArrayOutputStream`, which \*is\* already using locks, we should suffer no performance hit by synchronizing `LimitedOutputStream::write` methods. This is just in the general spirit of future-proofing code, given that we're already using locks, we might as well avoid as many future races as we can : ). Given that this would take some changes to the `LimitedOutputStream` API (from extending `ByteArrayOutputStream` directly) I've opted to not change these APIs here, but in a separate PR.

#### Changes to `LimitedOutputStream`
- Expose an public `LimitedOutputStream::toByteArray()` which returns the underlying byte array for stream-specific operations.

```
T1: write():
T1: read written = INT_MAX - 1
INT
T2: write():
T2: read written = INT_MAX - 1
T2: write written += 1
T2: write() succeeds
INT
T1: write written += 1
T1: write() succeeds
FIN
```

#### Release note

Avoid OOM-killing query if large result-level cache population fails for query

<hr>

##### Key changed/added classes in this PR
* `processing/src/main/java/org/apache/druid/io/LimitedOutputStream.java`
* `server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java`
* `server/src/test/java/org/apache/druid/query/ResultLevelCachingQueryRunnerTest.java`

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/io/LimitedOutputStream.java [hunk 1]
```diff
@@ -24,18 +24,19 @@
...
- * is exceeded.
+ * is exceeded. *Not* thread-safe.
  */
 public class LimitedOutputStream extends OutputStream
 {
   private final OutputStream out;
   private final long limit;
   private final Function<Long, String> exceptionMessageFn;
-  long written;
+  AtomicLong written;
```
Comment (samarthjain) [inline processing/src/main/java/org/apache/druid/io/LimitedOutputStream.java:39]: If the class is not thread safe, then I don't see the point of using an `AtomicLong` here. The hope is that someone would read the above documentation and not share the stream among multiple threads.

File: server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java [hunk 2]
```diff
@@ -152,6 +153,8 @@ public void after(boolean isDone, Throwable thrown)
                   // The resultset identifier and its length is cached along with the resultset
                   resultLevelCachePopulator.populateResults();
                   log.debug("Cache population complete for query %s", query.getId());
+                } else { // thrown == null && !resultLevelCachePopulator.isShouldPopulate()
+                  log.error("Failed (and recovered) to populate result level cache for query %s", query.getId());
```
Comment (samarthjain) [inline server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java:157]: The error message is a bit confusing. This block will be hit when `!resultLevelCachePopulator.isShouldPopulate()` evaluates to true. So no attempt would have been made to populate the result level cache. Also, if thrown is null, why was there a failure?

Comment (jtuglu-netflix) [reply server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java:157]: The block will be hit when `thrown == null and !resultLevelCachePopulator.isShouldPopulate()`. In this case, `thrown` represents when an irrecoverable exception was found [here](https://github.netflix.net/corp/bdp-druid/blob/netflix/31.0.x/server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java#L311), where we re-throw the exception. `resultLevelCachePopulator.isShouldPopulate()` references the case when we hit an exception that we could recover from and that we know how to handle properly (e.g IOException). That is where `stopPopulating()` is called.

The distinction is errors we can (and should) effectively recover from and those where we should fail the query.

I can switch to `Failed (gracefully) ...`.

File: processing/src/main/java/org/apache/druid/io/LimitedOutputStream.java (hunk 1 above)
Comment (jtuglu-netflix) [reply processing/src/main/java/org/apache/druid/io/LimitedOutputStream.java:39]: It's best effort fix against the worst-case race I mentioned above (resulting in an overflow) until a switch is made to a properly thread-safe solution for `ByteArrayOutputStream`. I can switch back, but I don't see the harm in keeping it.

**Review by maytasm — APPROVED** [review]

File: server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java [hunk 3]
```diff
@@ -270,7 +273,14 @@ private ResultLevelCachePopulator(
       this.serialiers = mapper.getSerializerProviderInstance();
       this.key = key;
       this.cacheConfig = cacheConfig;
-      this.cacheObjectStream = shouldPopulate ? new ByteArrayOutputStream() : null;
+      this.cacheObjectStream = shouldPopulate ? new LimitedOutputStream(
```
Comment (kgyrtkirk) [inline server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java:276]: possible cleanup: seems to me that there is only one callsite for `ResultLevelCachePopulator` ; which passes `true` for `shouldPopulate`

**Review by kgyrtkirk — APPROVED** [review]
+1
left a note and you have some minor checkstyle issue

File: server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java (hunk 3 above)
Comment (jtuglu-netflix) [reply server/src/main/java/org/apache/druid/query/ResultLevelCachingQueryRunner.java:276]: Given this is evaluated once at construction I don't see a need to remove the flexibility.

**Comment by kgyrtkirk** [comment]
note: there is no need to force-push the branch; the changes will be squashed on merge - its ok to just add more commits
