### PR TITLE
Fixed flaky BlockingPoolTest.testConcurrentTakeBatch()

### LINKED ISSUE #6218: BlockingPoolTest.testConcurrentTakeBatch transient failure
seems like a bug in BlockingPool .

from build log...
```
testConcurrentTakeBatch(io.druid.collections.BlockingPoolTest)  Time elapsed: 0.019 sec  <<< FAILURE!
java.lang.AssertionError
	at io.druid.collections.BlockingPoolTest.testConcurrentTakeBatch(BlockingPoolTest.java:246)

```

### PR DESCRIPTION
**Pull request by alex-plekhanov**
Fixes #6218.

### Description

Fixed the flaky test.
 

<hr>

This PR has:
- [x] been self-reviewed.

### CODE REVIEW

File: core/src/test/java/org/apache/druid/collections/BlockingPoolTest.java [hunk 1]
```diff
@@ -218,7 +218,7 @@ public void testConcurrentTakeBatch() throws ExecutionException, InterruptedExce
     final List<ReferenceCountingResourceHolder<Integer>> r1 = f1.get();
     final List<ReferenceCountingResourceHolder<Integer>> r2 = f2.get();
 
-    if (r1 != null) {
+    if (!r1.isEmpty()) {
```
Comment (gianm) [inline core/src/test/java/org/apache/druid/collections/BlockingPoolTest.java:221]: Wow, good catch!
