### PR TITLE
Guard against exponential increase of filters during CNF conversion

### LINKED ISSUE #12311: Historical crashes with OOM on SQL join query
### Affected Version

21.1

### Description

```
SELECT "field1", "field2", "subquery_count", Count(*) as "count"
FROM datamodel
LEFT JOIN (
  SELECT "field1" as "subquery_field", Count(*) as "subquery_count"
  FROM datamodel
  WHERE ("field1", "field2") IN (('a1, 'a2'), ('b1, 'b2'), {more_values})
  AND {various_other_filters}
  GROUP BY 1
) ON "subquery_field"="field1"
WHERE ("field1", "field2") IN (('a1, 'a2'), ('b1, 'b2'), {more_values})
AND {various_other_filters}
GROUP BY 1,2,3
```

The issue appears to crop up whenever we have a query with a LEFT JOIN and the `("field1", "field2") IN (('a1, 'a2'), ('b1, 'b2'), {more_values})` has more than 16 pairs of values on the right side. It does matter if the values on the right side are unique, i.e. if a1=b1=c1 for every pair, then the crash does not happen (likely runs a more optimal query plan in that case).  The query will take a long time and will eventually crash the historical, even sometimes if you cancel the query well before the OOM is hit.  It's a bit surprising that it happens at all, because the total amount of data the subquery would return should be pretty small.

cluster is 2 historicals, 2 routers, 1 broker

broker settings:
```
    - name: DRUID_XMX
      value: 4g
    - name: DRUID_XMS
      value: 4g
    - name: DRUID_MAXDIRECTMEMORYSIZE
      value: 3g
    - name: JAVA_OPTS
      value: -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError
    - name: druid_broker_http_numConnections
      value: "25"
    - name: druid_broker_http_maxQueuedBytes
      value: "10000000"
    - name: druid_server_http_numThreads
      value: "30"
    - name: druid_plaintextPort
      value: "8082"
    - name: druid_broker_cache_useCache
      value: "false"
    - name: druid_broker_cache_populateCache
      value: "false"
    - name: druid_processing_buffer_sizeBytes
      value: "524288000"
    - name: druid_processing_numThreads
      value: "3"
    - name: druid_processing_numMergeBuffers
      value: "2"
    - name: druid_sql_enable
      value: "true"
```
historical settings:
```
    - name: DRUID_XMX
      value: 9g
    - name: DRUID_XMS
      value: 9g
    - name: DRUID_MAXDIRECTMEMORYSIZE
      value: 7g
    - name: JAVA_OPTS
      value: -XX:+UseG1GC -XX:+ExitOnOutOfMemoryError
    - name: druid_server_http_numThreads
      value: "60"
    - name: druid_plaintextPort
      value: "8083"
    - name: druid_processing_numThreads
      value: "8"
    - name: druid_processing_numMergeBuffers
      value: "2"
    - name: druid_processing_buffer_sizeBytes
      value: "524288000"
    - name: druid_segmentCache_locations
      value: '[{"maxSize":2199023255552,"path":"var/druid/segment-cache"}]'
    - name: druid_segmentCache_numLoadingThreads
      value: "12"
    - name: druid_segmentCache_lazyLoadOnStart
      value: "true"
    - name: druid_server_maxSize
      value: "2199023255552"
    - name: druid_historical_cache_useCache
      value: "true"
    - name: druid_historical_cache_populateCache
      value: "true"
    - name: druid_cache_sizeInBytes
      value: "1073741824"
    - name: druid_monitoring_monitors
      value: '["org.apache.druid.java.util.metrics.JvmMonitor","org.apache.druid.server.metrics.QueryCountStatsMonitor","org.apache.druid.server.metrics.HistoricalMetricsMonitor","org.apache.druid.client.cache.CacheMonitor"]'
  - name: druid_query_groupBy_maxOnDiskStorage
    value: "10737418240"
```
plugins:
```
druid-aws-common
org.apache.druid.common.aws.AWSModule
0.21.1
druid-gcp-common
org.apache.druid.common.gcp.GcpModule
0.21.1
postgresql-metadata-storage
org.apache.druid.metadata.storage.postgresql.PostgreSQLMetadataStorageModule
0.21.1
druid-kafka-indexing-service
org.apache.druid.indexing.kafka.KafkaIndexTaskModule
0.21.1
druid-histogram
org.apache.druid.query.aggregation.histogram.ApproximateHistogramDruidModule
0.21.1
druid-datasketches
org.apache.druid.query.aggregation.datasketches.theta.SketchModule
0.21.1
druid-datasketches
org.apache.druid.query.aggregation.datasketches.theta.oldapi.OldApiSketchModule
0.21.1
druid-datasketches
org.apache.druid.query.aggregation.datasketches.quantiles.DoublesSketchModule
0.21.1
druid-datasketches
org.apache.druid.query.aggregation.datasketches.tuple.ArrayOfDoublesSketchModule
0.21.1
druid-datasketches
org.apache.druid.query.aggregation.datasketches.hll.HllSketchModule
0.21.1
druid-lookups-cached-global
org.apache.druid.server.lookup.namespace.NamespaceExtractionModule
0.21.1
druid-hdfs-storage
org.apache.druid.storage.hdfs.HdfsStorageDruidModule
0.21.1
druid-stats
org.apache.druid.query.aggregation.stats.DruidStatsModule
0.21.1
statsd-emitter
org.apache.druid.emitter.statsd.StatsDEmitterModule
0.21.1
druid-processing
org.apache.druid.guice.BloomFilterExtensionModule
0.21.1
```

Any more configuration / details worth sharing?

### PR DESCRIPTION
**Pull request by rohangarg**
Fixes #12311 

Currently, the CNF conversion of a filter is unbounded, which means that it can create as many filters as possible thereby also leading to OOMs in historical heap. We should throw an error or disable CNF conversion if the filter count starts getting out of hand. There are ways to do CNF conversion with linear increase in filters as well but that has been left out of the scope of this change since those algorithms add new variables in the predicate - which can be contentious. Any improved algorithm for conversion can be taken up later upon discussion.  

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java [hunk 1]
```diff
@@ -178,6 +179,11 @@ private static void generateAllCombinations(
           a.add(child);
           // Result must receive an actual OrFilter.
           result.add(idempotentOr(Filters.or(a)));
+          if (result.size() >= 10_000) {
```
Comment (clintropolis) [inline processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java:182]: any reason for this limit to be configurable?

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+package org.apache.druid.segment.filter.cnf;
+
+import org.apache.druid.java.util.common.StringUtils;
+
+public class CNFFilterExplosionException extends Exception
```
Comment (clintropolis) [inline processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java:24]: should this be a `BadQueryException`? Since i think this is user controllable by setting a context flag or not, I think doing this would result in it being a user error when it eventually surfaces

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java (hunk 1 above)
Comment (rohangarg) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java:182]: this could be configurable - didn't keep it as of now to avoid more configs.
but if it feels like disruptive (because it could lead to failure in some existing queries which create > 10k filters and still run), I can add a config for this

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java (hunk 2 above)
Comment (rohangarg) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java:24]: Yes, `BadQueryException` makes sense but one problem is that it is an un-checked exception. I was trying to make this a checked exception so that callers must decide how to handle it. wdyt?

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java [hunk 3]
```diff
@@ -178,6 +179,11 @@ private static void generateAllCombinations(
...
+            throw new CNFFilterExplosionException(
+                "Atleast 10,000 filters created by CNF (conjunctive normal form) conversion of the filter. "
```
Comment (LakshSingla) [inline processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java:184]: nit: Can `10_000` here and in the `if` be made a final variable somewhere? Would reduce the changes we need to track when updating the limit

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java (hunk 1 above)
Comment (rohangarg) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java]: I've added the change where exceeding this limit for not fail queries for now. when the limit exceeds, the join flow will disable pushdown optimization and the normal filter flow will return the non-CNF filter. does that seem ok to not add a config to toggle the limit?

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java (hunk 3 above)
Comment (rohangarg) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java]: Yes, fixed by creating a constant

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java (hunk 2 above)
Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java:24]: i think that makes sense, looking closer I see now that these exceptions are always eaten and don't make it to the user, i admittedly just did a drive by scan of this PR earlier and thought they might make it to the surface 😅  

though thinking about it, maybe it is worth a log of some sort to know that this is happening so that there is some indicator of why the expected query isn't happening?

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java (hunk 1 above)
Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/HiveCnfHelper.java]: yeah, i think that is ok, the transformation _shouldn't_ be changing results afaik, though per my other comment there should be some way to know that this has happened

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java (hunk 2 above)
Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java:24]: i guess a log might be kind of noisy if this was coming from the SQL planner, and would need to be collected and printed at the end instead. We have a mechanism for collecting errors this way, but not for informative messages; this could be done at a later time I think (if is actually useful to have a way to know why the planner did or didn't do a think that was asked for).

**Review by clintropolis — APPROVED** [review]

File: processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java (hunk 2 above)
Comment (rohangarg) [reply processing/src/main/java/org/apache/druid/segment/filter/cnf/CNFFilterExplosionException.java:24]: Yes, I agree with that - it would make more sense to have something in a per query structure which is shown to the user.

File: processing/src/main/java/org/apache/druid/segment/filter/Filters.java [hunk 4]
```diff
@@ -433,10 +434,15 @@ public static Filter convertToCNFFromQueryContext(Query query, @Nullable Filter
       return null;
     }
     boolean useCNF = query.getContextBoolean(QueryContexts.USE_FILTER_CNF_KEY, QueryContexts.DEFAULT_USE_FILTER_CNF);
-    return useCNF ? Filters.toCnf(filter) : filter;
+    try {
+      return useCNF ? Filters.toCnf(filter) : filter;
+    }
+    catch (CNFFilterExplosionException cnfFilterExplosionException) {
+      return filter; // cannot convert to CNF, return the filter as is
```
Comment (cryptoe) [inline processing/src/main/java/org/apache/druid/segment/filter/Filters.java:441]: I would just put a log that we are not converting to cnf due to 'CNFFilterExplosionExceptions` so that people debugging the query know whats happening

**Review by cryptoe — APPROVED** [review]
LGTM

File: processing/src/main/java/org/apache/druid/segment/filter/Filters.java (hunk 4 above)
Comment (cheddar) [reply processing/src/main/java/org/apache/druid/segment/filter/Filters.java:441]: For clusters where this happens regularly, that can generate a lot of log spew.  You could argue that they should respond to the log spew by not doing the queries, but it would still be a sudden chunk of log spew.  In general, CNF is a potential optimization done by the planner, we don't log other optimization choices that we make, we just make them.  In this case, it's deeming that converting to CNF is more expensive than just leaving it as is, which is yet another optimization decision.  I don't think it needs a log, or if it does, maybe at debug level.

**Review by cheddar — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
Merged since failures on jdk15 tests are unrelated.

File: processing/src/main/java/org/apache/druid/segment/filter/Filters.java (hunk 4 above)
Comment (cryptoe) [reply processing/src/main/java/org/apache/druid/segment/filter/Filters.java:441]: I understand where your coming from. In such a case, I would then tend towards not throwing an exception and refactoring the `Filter.toCnf(filter)` to return an appropriate state which helps us decide if the conversionWasSucessfull or not. Maybe use `Optional.of()`so that we avoid throwing exceptions due to performance overheads of exceptions. 
We can take this up as future work. Maybe when we are making this limit configurable.
