### PR TITLE
HttpPostEmitter back off send() busy-loop

### LINKED ISSUE #11279: High CPU (or event submission timeouts) in HttpPostEmitter with bursty events
When configured with a `minHttpTimeoutMilis`, coordinator node has HttpPostEmitter thread pegged at 100% CPU when large batches arrive followed by an idle period. Alternatively, when no min timeout is set, submissions to backend fail due to very short timeout periods (2ms).

### Affected Version

0.20.0

### Description

HttpPostEmitter has some heuristic logic to batch events and ship them in an efficient and timely fashion, while also trying to somewhat throttle itself.

When a large batch of data is received in too short a time frame, the heuristics arrive to a state such that the emitter gets stuck in a busy-loop and unable to make forward progress. This is the case until enough normal messages have accrued to reset the `lastBatchFillTimeMillis` duration.

I can detect this as follows:
- Configuration set as follows 
```
# Emit metrics over http
druid.emitter=http
druid.emitter.http.recipientBaseUrl=http://localhost:8078/druidmetrics
druid.emitter.http.minHttpTimeoutMillis=100
```
- Debug logs on, and look for `Failed to send events to url[http://localhost:8078/druidmetrics] with timeout less than minimum`
- CPU up to 100% on one thread (`HttpPostEmitter-1`)
- Monitor logs of downstream service (ie: the receiver of the HTTP POSTs). One post arrives and then no more for some period of time.
- Take heap dump to inspect service configuration - many buffers present in failed buffer queue.
- Heap analysis also shows `lastBatchFillTimeMillis` = 2, and `approximateXxxToEmitCount` = 0.

### Current logic

With reference to the logic [here](https://github.com/apache/druid/blob/8296123d895db7d06bc4517db5e767afb7862b83/core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java#L501-L521) and [here](https://github.com/apache/druid/blob/8296123d895db7d06bc4517db5e767afb7862b83/core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java#L708-L716):
- As data arrives, it is batched. Once a batch is filled, a timer is captured `lastBatchFillTimeMillis` to use later, and the batch submitted to the endpoint.
- The overall flow is a `while(true) { readFromQueueAndSubmitBatch(); }` flow, with some ability to park failed messages for resubmission.
- In all cases, the control flows through `sendWithRetries()` into `send()`.
- In `send()`, through to `[computeTimeoutForSendRequestInMillis]`(https://github.com/apache/druid/blob/8296123d895db7d06bc4517db5e767afb7862b83/core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java#L805-L810), a calculation is made to set a timer based on how long the last batch took to fill and how much is waiting in queue.
- `send()` then compares that to the configuration item `minHttpTimeoutMillis` and if it is lower, than it stalls submission.

### Issue

- When a large burst of data arrives into the emitter, that fills more than a single buffer, the `lastBatchFillTimeMillis` becomes very short, (say, 2ms). The burst stops, and so no more messages are arriving to completely fill a batch for "some time" (maybe 10s of seconds).
- As long as the queue depth is modest, (< 25 in this case), the calculated timeout will _always be < 100ms_ (lastBatchFillTime * allowance), and so _the send operation will always be rejected_ to wait for later. The allowance factor is always `2.0f` or less as the queue grows, which gives a best case of 2ms * 2.0f = 4ms which is drastically less than the minimum 100ms.
- The message is immediately failed, and eventually accumulates in the failed queue.
- Once a "normal throughput" batch completes, the last batch fill time will be more normal (15818ms in captured analysis).
- On next iteration, the failed submission queue will attempt a send, and a calculated timeout will be greater than the minimum 100ms. Submission proceeds. Very quickly all failed batches are submitted to the backend and CPU drops back to normal (~0% for HttpPostEmitter).

### Attempts to work around
- Setting the `.minHttpTimeoutMillis` from 1-4ms results in a high rate of failure under normal operations.
- Setting `.maxBatchSize` smaller does help reduce it, however the lowest limit is strictly defined [here](https://github.com/apache/druid/blob/8296123d895db7d06bc4517db5e767afb7862b83/core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java#L157-L164)  `maxBatchSize must be greater than MAX_EVENT_SIZE[1,047,552] + overhead`
- Setting `.flushCount` to a lower number (eg: `50` instead of default `500`), means the busy loop is resolved a little quicker (30-60sec) but it is more likely that a buffer filling event occurs.
- Clearing the `minHttpTimeoutMillis` (default of `0`), shows a different error under the same circumstances, fundamentally due to the same causes - where the timeout heuristic calculated is based on the previous batch fill timer but that batch fill was short) - `Request timeout .. after 2ms` and `@4000000060a6f8f62fdf1aa4 2021-05-21T00:03:56,803 ERROR [HttpPostEmitter-1] org.apache.druid.java.util.emitter.core.HttpPostEmitter - Timing out emitter batch send, last batch fill time [1] ms, timeout [2] ms`:
```
@4000000060a6f7350c20a31c Caused by: java.util.concurrent.TimeoutException: Request timeout to localhost/127.0.0.1:8078 after 2 ms
@4000000060a6f7350c20a31c 	at org.asynchttpclient.netty.timeout.TimeoutTimerTask.expire(TimeoutTimerTask.java:43) ~[async-http-client-2.5.3.jar:?]
@4000000060a6f7350c20aed4 	at org.asynchttpclient.netty.timeout.RequestTimeoutTimerTask.run(RequestTimeoutTimerTask.java:50) ~[async-http-client-2.5.3.jar:?]
@4000000060a6f7350c20aed4 	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
@4000000060a6f7350c20b2bc 	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
@4000000060a6f7350c20b2bc 	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472) ~[netty-common-4.1.48.Final.jar:4.1.48.Final]
@4000000060a6f7350c20b2bc 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_282]```

### PR DESCRIPTION
**Pull request by jasonk000**
### Description

Introduce a back-off to the `HttpPostEmitter` `send()` thread loop to minimise the amount of log spamming and CPU.

Fixes #11279.

#### Introduce HttpPostEmitterLoggerStressTest

Introduce a test to count how many logged events are triggered during a loop scenario. It confirms that no more than some maximum send timeout log events are written in duration of the test. Test runs typically for 6 seconds, and expects limit of 1000 send attempts in that 6 second period.

Currently, the HttpPostEmitter thread submits 150K events in the test window.
```
[ERROR] Failures: 
[ERROR] org.apache.druid.java.util.emitter.core.HttpPostEmitterLoggerStressTest.testBurstFollowedByQuietPeriod(org.apache.druid.java.util.emitter.core.HttpPostEmitterLoggerStressTest)
[ERROR]   Run 1: HttpPostEmitterLoggerStressTest.testBurstFollowedByQuietPeriod:98 too many timeouts (159620), expect less than (1000)
[ERROR]   Run 2: HttpPostEmitterLoggerStressTest.testBurstFollowedByQuietPeriod:98 too many timeouts (166201), expect less than (1000)
[ERROR]   Run 3: HttpPostEmitterLoggerStressTest.testBurstFollowedByQuietPeriod:98 too many timeouts (173177), expect less than (1000)
[ERROR]   Run 4: HttpPostEmitterLoggerStressTest.testBurstFollowedByQuietPeriod:98 too many timeouts (175135), expect less than (1000)
```

#### Introduce a backoff to the send() loop when the specific timeout is experienced.

A simple backoff is chosen at 1/5th the minimum time.

An alternative solution which might be better involves a larger rewrite of this class, as the class currently splits responsibilities for managing the batching and sending across multiple classes and threads. A simpler codebase might run a simpler submission loop with a more explicit throttle and batching mechanism instead of the current batching handoffs.

This PR has:
- [x] been self-reviewed.
   - [ ] N/A using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] N/A added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] N/A added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by jasonk000** [comment]
Hi @FrankChen021 - do you have suggestions on taking forward this PR? it seems straightforward to me, let me know if you suggest more tests etc or should I tag another reviewer?

**Comment by jasonk000** [comment]
@abhishekagarwal87 is this something you could take a look at too?

**Comment by abhishekagarwal87** [comment]
Sure @jasonk000. Hoping to review it sometime next week.

File: core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java [hunk 1]
```diff
@@ -698,13 +698,42 @@ public boolean apply(Throwable e)
...
+      // Making this technically correct, across all possible Batches, including large events,
+      // etc is complicated in this codebase, since batch flush timing is not tracked here,
+      // so rather than introduce new bugs, let's keep it simple.
+
+      final long backoffCheckDelayMillis = config.getMinHttpTimeoutMillis() / 5;
+
+      try {
+        Thread.sleep(backoffCheckDelayMillis);
+      }
+      catch (InterruptedException e) {
```
Comment (FrankChen021) [inline core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java:732]:
```suggestion
      catch (InterruptedException ignored) {
```

File: core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java [hunk 2]
```diff
@@ -698,13 +698,42 @@ public boolean apply(Throwable e)
...
+      // This is called when the send() call hits a timeoutLessThanMinimumException
+      // condition. Ideally, what we should do is delay until either the timeout increases
+      // to above the minHttpTimeout, and so the send() will be issued, or, until a Batch
+      // wants to flush based on the configured timeout.
+
+      // Making this technically correct, across all possible Batches, including large events,
+      // etc is complicated in this codebase, since batch flush timing is not tracked here,
+      // so rather than introduce new bugs, let's keep it simple.
+
+      final long backoffCheckDelayMillis = config.getMinHttpTimeoutMillis() / 5;
```
Comment (FrankChen021) [inline core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java:727]: I'm still confused. Why not keep the computed timeout in the exception object and wait for (config.getMinHttpTimeoutMillis - computed_timeout)?

Comment (jasonk000) [reply core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java:727]: It's a heuristic, I don't have a good reason for `/ 5` instead of 4, 3, etc.

WRT sleep timer - it's definitely possible to sleep for longer until the timeout expires, but the downside is we might wait a little longer than required for an opportunity to send if the computed timeout changes. For example, if the batch fills while we are still sleeping then we might keep sleeping. We could resolve this by introducing an interrupt or a wait/notify, etc.

WRT passing the time calculated, it adds more code to maintain a new custom Exception for (in my view) limited benefit. For what I assume are efficiency reasons the existing code [caches the Exception object here](https://github.com/apache/druid/blob/5ab9ec6bdcc06078d678b88903b4d53bff2c9d61/core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java#L478). To be honest I don't really see the benefit of caching the object, and would suggest an easier solution would be to recalculate the remaining timeout directly.

--

The main goal when I started was to avoid busy-spinning an entire CPU core as it was previously doing, a sleep allows this while still being response enough, and this is the minimum viable solution I came up with. 

IF we do a more comprehensive solution solution I think we completely split the logic between batch accumulation and flush / send pacing / backpressure. Also, that's substantially more code for what is limited real-world benefit.

Comment (jasonk000) [reply core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java:727]: Hi @FrankChen021 were you able to review / confirm suitability of the approach here?

CC @abhishekagarwal87

Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java:727]: Let me review the changes on this weekend. Thanks for the patience.

**Comment by jasonk000** [comment]
Adding some more background to this -- on clusters where we do not run this patch, we regularly see CPUs pinned in this code. 

This node has five cores dedicated to spinning in this loop, which plays havoc with our scaling policy and metrics.

image

Here is a flamegraph with `HttpPostEmitter` highlighted
image

--

A more serious edition, which I had to scroll down to capture, 25 CPUs pegged in this loop:

image
image

I've highlighted `HttpPostEmitter` here, totalling 98.4% of all samples:
image

**Review by maytasm — APPROVED** [review]
LGTM
