### PR TITLE
Fix invalid segment path when using hdfs as the intermediate deepstore

### LINKED ISSUE #14972: Invalid segment path when using HDFS as the intermediate deepstore
### Affected Version

Druid 27

#### The cluster is deployed on k8s with following features enabled
1. MM less feature
2. Use HDFS as deepstore
3. Set `druid_processing_intermediaryData_storage_type: "deepstore"`

#### Steps to reproduce the problem
1. Submit an `index_parallel` type batch task
2. Set `maxNumConcurrentSubTasks` > 1

#### Error logs
```
Caused by: java.lang.IllegalArgumentException: Pathname /user/druid/k8s/druid27-test/segments/shuffle-data/index_parallel_session_analysis_test_bkdhhedd_2023-09-08T03:18:21.121Z/2023-08-29T16:00:00.000Z/2023-08-29T17:00:00.000Z/0 from hdfs://R2/user/druid/k8s/druid27-test/segments/shuffle-data/index_parallel_session_analysis_test_bkdhhedd_2023-09-08T03:18:21.121Z/2023-08-29T16:00:00.000Z/2023-08-29T17:00:00.000Z/0 is not a valid DFS filename.
	at org.apache.hadoop.hdfs.DistributedFileSystem.getPathName(DistributedFileSystem.java:266) ~[?:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1558) ~[?:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem$29.doCall(DistributedFileSystem.java:1555) ~[?:?]
	at org.apache.hadoop.fs.FileSystemLinkResolver.resolve(FileSystemLinkResolver.java:81) ~[?:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.mkdirsInternal(DistributedFileSystem.java:1572) ~[?:?]
	at org.apache.hadoop.hdfs.DistributedFileSystem.mkdirs(DistributedFileSystem.java:1547) ~[?:?]
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2404) ~[?:?]
	at org.apache.druid.storage.hdfs.HdfsDataSegmentPusher.pushToPath(HdfsDataSegmentPusher.java:154) ~[?:?]
	at org.apache.druid.indexing.worker.shuffle.DeepStorageIntermediaryDataManager.addSegment(DeepStorageIntermediaryDataManager.java:78) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.worker.shuffle.ShuffleDataSegmentPusher.push(ShuffleDataSegmentPusher.java:66) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.lambda$mergeAndPush$4(AppenderatorImpl.java:956) ~[druid-server-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:129) ~[druid-processing-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:81) ~[druid-processing-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:163) ~[druid-processing-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:153) ~[druid-processing-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.mergeAndPush(AppenderatorImpl.java:952) ~[druid-server-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.segment.realtime.appenderator.AppenderatorImpl.lambda$push$1(AppenderatorImpl.java:784) ~[druid-server-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at com.google.common.util.concurrent.Futures$1.apply(Futures.java:713) ~[guava-16.0.1.jar:?]
	at com.google.common.util.concurrent.Futures$ChainingListenableFuture.run(Futures.java:861) ~[guava-16.0.1.jar:?]
	... 3 more
```

```
2023-09-08T07:07:32,491 ERROR [task-runner-0-priority-0] org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner - Exception while running task[AbstractTask{id='partial_index_generic_merge_session_analysis_test_lmhgjiib_2023-09-08T07:07:16.638Z', groupId='index_parallel_session_analysis_test_mohoklnj_2023-09-08T07:03:43.955Z', taskResource=TaskResource{availabilityGroup='partial_index_generic_merge_session_analysis_test_lmhgjiib_2023-09-08T07:07:16.638Z', requiredCapacity=1}, dataSource='session_analysis_test', context={forceTimeChunkLock=true, useLineageBasedSegmentAllocation=true}}]
java.io.IOException: org.apache.druid.segment.loading.SegmentLoadingException: Do not know how to handle file type at [hdfs://R2/user/druid/k8s/druid27-test/segments/shuffle-data/index_parallel_session_analysis_test_mohoklnj_2023-09-08T07_03_43.955Z/20230830T060000.000Z_20230830T070000.000Z/0/partial_index_generate_session_analysis_test_fgbidneh_2023-09-08T07_04_41.368Z]
	at org.apache.druid.indexing.common.task.batch.parallel.DeepStorageShuffleClient.fetchSegmentFile(DeepStorageShuffleClient.java:56) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.common.task.batch.parallel.DeepStorageShuffleClient.fetchSegmentFile(DeepStorageShuffleClient.java:33) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.common.task.batch.parallel.PartialSegmentMergeTask.fetchSegmentFiles(PartialSegmentMergeTask.java:228) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.common.task.batch.parallel.PartialSegmentMergeTask.runTask(PartialSegmentMergeTask.java:173) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.common.task.batch.parallel.PartialGenericSegmentMergeTask.runTask(PartialGenericSegmentMergeTask.java:46) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.common.task.AbstractTask.run(AbstractTask.java:173) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:477) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:449) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.apache.druid.segment.loading.SegmentLoadingException: Do not know how to handle file type at [hdfs://R2/user/druid/k8s/druid27-test/segments/shuffle-data/index_parallel_session_analysis_test_mohoklnj_2023-09-08T07_03_43.955Z/20230830T060000.000Z_20230830T070000.000Z/0/partial_index_generate_session_analysis_test_fgbidneh_2023-09-08T07_04_41.368Z]
	at org.apache.druid.storage.hdfs.HdfsDataSegmentPuller.getSegmentFiles(HdfsDataSegmentPuller.java:288) ~[?:?]
	at org.apache.druid.storage.hdfs.HdfsLoadSpec.loadSegment(HdfsLoadSpec.java:57) ~[?:?]
	at org.apache.druid.indexing.common.task.batch.parallel.DeepStorageShuffleClient.fetchSegmentFile(DeepStorageShuffleClient.java:52) ~[druid-indexing-service-27.0.0-SNAPSHOT.jar:27.0.0-SNAPSHOT]
	... 11 more
```

### RCA

The root cause of the issue is that we call method `pushToPath` passing a suffix dir
https://github.com/apache/druid/blob/286eecad7cfe02369157073fd4915a7a0b480ec1/indexing-service/src/main/java/org/apache/druid/indexing/worker/shuffle/DeepStorageIntermediaryDataManager.java#L78
While method [HdfsDataSegmentPusher#pushToPath](https://github.com/apache/druid/blob/23b78c0f955860d51add780178ef8a4526b334db/extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java#L119) treats parameter `storageDirSuffix` as output index fiilepath with "index.zip" suffix, see 
https://github.com/apache/druid/blob/23b78c0f955860d51add780178ef8a4526b334db/extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java#L128
https://github.com/apache/druid/blob/23b78c0f955860d51add780178ef8a4526b334db/extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java#L148-L156

### Solution

In method method [HdfsDataSegmentPusher#pushToPath], we should check if the parameter is a dir or a well-formatted segment file path.

To fix it, we can change this line
https://github.com/apache/druid/blob/23b78c0f955860d51add780178ef8a4526b334db/extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java#L128
to
```java
    final String outIndexFilePath;
    if (storageDirSuffix.endsWith("index.zip")) {
      outIndexFilePath = StringUtils.format("%s/%s", fullyQualifiedStorageDirectory.get(), storageDirSuffix);
    } else {
      outIndexFilePath = StringUtils.format(
          "%s/%s/%d_index.zip",
          fullyQualifiedStorageDirectory.get(),
          storageDirSuffix.replace(':', '_'),  // We don't want to include ':' characters in hdfs path
          segment.getShardSpec().getPartitionNum()
      );
    }
```

### PR DESCRIPTION
**Pull request by yuanlihan**
Fixes #14972.

### Description

This PR fixes the invalid segment path when enabling `druid_processing_intermediaryData_storage_type: "deepstore"` and using `hdfs` as the deep store. 

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `HdfsDataSegmentPusher`

<hr>

This PR has:

- [X] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java [hunk 1]
```diff
@@ -124,8 +124,18 @@ public DataSegment pushToPath(File inDir, DataSegment segment, String storageDir
         fullyQualifiedStorageDirectory.get(),
         storageDirSuffix
     );
-
-    final String storageDir = StringUtils.format("%s/%s", fullyQualifiedStorageDirectory.get(), storageDirSuffix);
+    
+    final String outIndexFilePath;
+    if (storageDirSuffix.endsWith("index.zip")) {
```
Comment (kfaraz) [inline extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java:129]: Could you please add some comments for both the if and else here? I am not sure why the `storageDirSuffix` would contain `index.zip` in it.

Comment (kfaraz) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java:129]: After taking a look at the linked issue #14972 , it seems that the method `pushToPath` is always being called with the directory name except in `DeepStorageIntermediaryDataManager` where it is called with the actual filename.

So the problem is not specific to `HdfsDataSegmentPusher` and might occur for other deep stores as well.

The right thing to do is either to fix up `DeepStorageIntermediaryDataManager` or add a new `push` method which takes the filename rather than directory.

Comment (yuanlihan) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java:129]: @kfaraz Thanks for looking into this! 

My first intuition was also trying to fix `DeepStorageIntermediaryDataManager` by passing a file path contains `index.zip` suffix here
https://github.com/apache/druid/blob/3ae5e978012e7a553e6ad3007eb210ab8da5b6fc/indexing-service/src/main/java/org/apache/druid/indexing/worker/shuffle/DeepStorageIntermediaryDataManager.java#L78

But after checking other implementations of `DataSegmentPusher`, I found they all call method [pushToPath](https://github.com/apache/druid/blob/3ae5e978012e7a553e6ad3007eb210ab8da5b6fc/processing/src/main/java/org/apache/druid/segment/loading/DataSegmentPusher.java#L71) in their [push](https://github.com/apache/druid/blob/3ae5e978012e7a553e6ad3007eb210ab8da5b6fc/processing/src/main/java/org/apache/druid/segment/loading/DataSegmentPusher.java#L69) method. Some of them format segment file path contains `index.zip` suffix and pass it by parameter `storageDirSuffix` to method `pushToPath`, see below
1. `AzureDataSegmentPusher`
https://github.com/apache/druid/blob/3ae5e978012e7a553e6ad3007eb210ab8da5b6fc/extensions-core/azure-extensions/src/main/java/org/apache/druid/storage/azure/AzureDataSegmentPusher.java#L124-L125
2. `HdfsDataSegmentPusher`
https://github.com/apache/druid/blob/279b3818f0e02f6a2ff389532f1e6118598a7c24/extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java#L108-L115

Other implementations format `storageDirSuffix` by calling [getStorageDir](https://github.com/apache/druid/blob/279b3818f0e02f6a2ff389532f1e6118598a7c24/processing/src/main/java/org/apache/druid/segment/loading/DataSegmentPusher.java#L89) in their `push` methods.

To fix the issue, I'd prefer to fix the inconsistent usages of `pushToPath` in method `AzureDataSegmentPusher#push` and `HdfsDataSegmentPusher#push`. We should always pass a dir to parameter `storageDirSuffix` of method `pushToPath` and format segment file path with suffix `index.zip` in method `pushToPath`. So, we don't need to change `DeepStorageIntermediaryDataManager` as it passes a dir to method `pushToPath`. Does it make sense to you?

Comment (yuanlihan) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java:129]: @kfaraz Friendly bump!

Comment (abhishekagarwal87) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java:129]: The function name is a bit confusing since storageDirSuffix is really a suffix to the filename. I looked at various implementations and this is what you can do to simplify the logic. Rather than `push` call `pushToPath` directly, both of these functions can call a separate third private function. `push` will create the right suffix by adding index.zip and so would `pushToPath`. `pushToPath` will add the suffix in the same way as org.apache.druid.storage.s3.S3Utils#constructSegmentPath

How does that sound?

Comment (yuanlihan) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java:129]: @abhishekagarwal87 Thanks for your comment!

> The function name is a bit confusing since storageDirSuffix is really a suffix to the filename.

I think `storageDirSuffix` shouldn't be the suffix to the filename but instead as the prefix dir of file `index.zip`.

I have concern that adding a third method will need to touch all implementations. I think it's ok to reuse `pushToPath` method inside `push` method as long as it complies with passing a storageDirSuffix not file path to method `pushToPath`.

Currently, only two implementations, `HdfsDataSegmentPusher` and `AzureDataSegmentPusher`, violate to pass file path  to their method `pushToPath` methods. Other implementations only format `storageDirSuffix` and reuse method `pushToPath` to format file path with `index.zip` file.

We can also enhance the method doc of `pushToPath`
https://github.com/apache/druid/blob/3ae5e978012e7a553e6ad3007eb210ab8da5b6fc/processing/src/main/java/org/apache/druid/segment/loading/DataSegmentPusher.java#L70-L75

Comment (abhishekagarwal87) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java:129]: Oh, I was suggesting refactoring just the HDFSDataSegmentPusher so you don't need to do that "endsWith" check in this class.

Comment (yuanlihan) [reply extensions-core/hdfs-storage/src/main/java/org/apache/druid/storage/hdfs/HdfsDataSegmentPusher.java]: @abhishekagarwal87 Oh I see. Updated.

**Review by asdf2014 — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
thank you for your contribution @yuanlihan
