### PR TITLE
fix vectorized query engine numeric filter matchers against null values

### LINKED ISSUE #9062: vectorized query engine numeric filter matchers do not correctly handle matching numeric null values
### Affected Version

0.16.0+

### Description

This functionality was not implemented, https://github.com/apache/incubator-druid/blob/master/processing/src/main/java/org/apache/druid/query/filter/vector/LongVectorValueMatcher.java#L44

### PR DESCRIPTION
**Pull request by clintropolis**
Fixes #9062.

### Description

This PR allows vector value matchers on numeric column when sql compatible null handling is enabled to match against null values instead of "optimizing" to always false.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by clintropolis** [comment]
this PR requires #9061 to be merged first since it uses the tests from that PR to test this PR

File: processing/src/main/java/org/apache/druid/query/filter/vector/VectorValueMatcherFactory.java [hunk 1]
```diff
@@ -28,4 +29,37 @@
...
+
+        for (int i = 0; i < mask.getSelectionSize(); i++) {
+          final int rowNum = mask.getSelection()[i];
+          if (nullVector[rowNum]) {
+            selection[numRows++] = rowNum;
+          }
+        }
+
+        match.setSelectionSize(numRows);
+        assert match.isValid(mask);
```
Comment (jon-wei) [inline processing/src/main/java/org/apache/druid/query/filter/vector/VectorValueMatcherFactory.java]: This assert looks like it's not that cheap to compute, I wonder if we should take it out
