### PR TITLE
Calcite tests remove expected exception

### LINKED ISSUE #15423: interpretation of cannotVectorize in tests may stop further  processing of the testcase
this testcase throws an exception uncoditionally; however it does not fail: as execution is stopped somewhere in `run()`
```
  @Test
  public void testX()
  {
    cannotVectorize();
    testBuilder()
        .sql(
            "SELECT "
                + " TIME_FLOOR(__time, 'P1D') as dayLvl,\n"
                + "  dim1,\n"
                + "  HLL_SKETCH_ESTIMATE(DS_HLL(hllsketch_dim1,18,'HLL_4'), true),\n"
                + "  1\n"
                + "FROM\n"
                + "  (select * from  druid.foo limit 10) ttt\n"
                + "  WHERE  __time >= '1903-08-02' AND __time <= '2033-08-07'\n"
                + "  and dim1 not like '%ikipedia' and l1 > -4\n"
                + "  group by 1,2"
        )
        .run();
    throw new RuntimeException("unreachable");
  }
```

### PR DESCRIPTION
**Pull request by kgyrtkirk**
* update testcases using `expectedException` to utilize `assertThrows` instead
* remove `BaseCalciteQueryTest#expectedException`
* fixes `cannotVectorize` so it doesn't anymore stops further processing
* `msqIncompatible` is not anymore toggles a boolean - its an `Assume` instead

Fixes #15423

This PR has:

- [x] been self-reviewed.

### CODE REVIEW

**Comment by kgyrtkirk** [comment]
failure of jdk11 static checks seem unrelated

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java [hunk 1]
```diff
@@ -589,32 +593,40 @@ public void testLongs()
...
+        )
     );
-    testQuery(
-        "SELECT COUNT(*)\n"
-        + "FROM druid.numfoo\n"
-        + "WHERE l1 > ?",
-        ImmutableList.of(),
-        ImmutableList.of(new Object[]{3L}),
-        ImmutableList.of()
+    assertThat(
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java:607]: The codeQL notice seems legit. Can we replace the deprecated method with `MatcherAssert.assertThat()`:
```suggestion
    MatcherAssert.assertThat(
```

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java [hunk 2]
```diff
@@ -589,32 +593,40 @@ public void testLongs()
...
+        )
     );
-    testQuery(
-        "SELECT COUNT(*)\n"
-        + "FROM druid.numfoo\n"
-        + "WHERE l1 > ? AND f1 = ?",
-        ImmutableList.of(),
-        ImmutableList.of(new Object[]{3L}),
-        ImmutableList.of(new SqlParameter(SqlType.BIGINT, 3L))
+    assertThat(
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java:627]:
```suggestion
    MatcherAssert.assertThat(
```

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java [hunk 3]
```diff
@@ -624,14 +636,19 @@ public void testPartiallyMissingParameterInTheMiddle()
...
+            params
+        )
     );
-    testQuery(
-        "SELECT 1 + ?, dim1 FROM foo LIMIT ?",
-        ImmutableList.of(),
-        ImmutableList.of(),
-        params
+
+    assertThat(
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java:649]:
```suggestion
    MatcherAssert.assertThat(
```

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java [hunk 4]
```diff
@@ -7581,47 +7573,48 @@ public void testAvgDailyCountDistinct()
...
+              + "FROM druid.numfoo\n"
+              + "WHERE dim6 IN (\n"
+              + "1,2,3\n"
+              + ")\n",
+          CalciteTests.REGULAR_USER_AUTH_RESULT,
+          ImmutableList.of(),
+          ImmutableList.of()
+      );
+    });
+    assertTrue(exception.getMessage().contains("The number of values in the IN clause for [dim6] in query exceeds configured maxNumericFilter limit of [2] for INs. Cast [3] values of IN clause to String"));
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java:7617]: nit: can you please break this up to accommodate smaller screen length?
Also, please use one consistently between MatcherAssert.assertThat and assertTrue (given assertThat is deprecated).

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java [hunk 5]
```diff
@@ -12319,61 +12308,64 @@ public void testRequireTimeConditionLogicalValuePositive()
...
+              + "  cnt FROM druid.foo\n"
+              + ") AS x\n"
+              + "GROUP BY gran\n"
+              + "ORDER BY gran",
+          CalciteTests.REGULAR_USER_AUTH_RESULT,
+          ImmutableList.of(),
+          ImmutableList.of()
+      );
+    });
+    assertTrue(exception.getMessage().contains("__time column"));
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java:12327]: ditto here and below

File: sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java [hunk 6]
```diff
@@ -1222,29 +1212,55 @@ public void assertResultsEquals(String sql, List<Object[]> expectedResults, List
     Assert.assertEquals(expectedResults.size(), results.size());
   }
 
-  public void testQueryThrows(final String sql, Consumer<ExpectedException> expectedExceptionInitializer)
+  public <T extends Throwable> void testQueryThrows(
+      final String sql,
+      final DruidExceptionMatcher exceptionMatcher)
+
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java:1218]:
```suggestion
      final DruidExceptionMatcher exceptionMatcher
  )
```

File: sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java [hunk 7]
```diff
@@ -1222,29 +1212,55 @@ public void assertResultsEquals(String sql, List<Object[]> expectedResults, List
...
+  {
+    testQueryThrows(sql, null, null, DruidException.class, exceptionMatcher);
+  }
+
+  public <T extends Exception> void testQueryThrows(
+      final String sql,
+      final Class<T> exceptionType,
+      final String exceptionMessage)
+
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java:1227]:
```suggestion
      final String exceptionMessage
  )
```

File: sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java [hunk 8]
```diff
@@ -1222,29 +1212,55 @@ public void assertResultsEquals(String sql, List<Object[]> expectedResults, List
...
-  {
-    testBuilder()
-        .sql(sql)
-        .queryContext(queryContext)
-        .expectedQueries(expectedQueries)
-        .expectedException(expectedExceptionInitializer)
-        .build()
-        .run();
+      final Class<T> exceptionType,
+      final Matcher<Throwable> exceptionMatcher)
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java:1252]:
```suggestion
      final Matcher<Throwable> exceptionMatcher
  )
```

**Review by abhishekrb19 — COMMENTED** [review]
Thanks @kgyrtkirk - nice cleanup overall. I left a few suggestions.

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java (hunk 2 above)
Comment (kgyrtkirk) [reply sql/src/test/java/org/apache/druid/sql/calcite/CalciteParameterQueryTest.java:627]: the ide have imported the wrong class...fixed it!

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java (hunk 4 above)
Comment (kgyrtkirk) [reply sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java:7617]: I think its better to use static imports than write out the class the actual assert/assume/etc comes from;
if the usecase would require to use 2 of those static imported methods from 2 different sources at the same time I would see differently - but if there is only one then I think it as something which reduces the readability with no added benefit

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteMultiValueStringQueryTest.java [hunk 9]
```diff
@@ -123,23 +124,25 @@ public void testMultiValueStringWorksLikeStringGroupBy()
   public void testMultiValueStringGroupByDoesNotWork()
   {
     // Cannot vectorize due to usage of expressions.
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteMultiValueStringQueryTest.java:126]: should the comment be removed as well?

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteSubqueryTest.java [hunk 10]
```diff
@@ -675,98 +678,112 @@ public void testEmptyGroupWithOffsetDoesntInfiniteLoop()
...
+      testMaxSubqueryRowsWithoutMemoryLimit();
+    } else {
+      testMaxSubQueryRowsWithLimit();
+    }
+  }
+
+  private void testMaxSubqueryRowsWithoutMemoryLimit()
+  {
+    Throwable exception = assertThrows(ResourceLimitExceededException.class, () -> {
       Map<String, Object> modifiedQueryContext = new HashMap<>(queryContext);
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteSubqueryTest.java:690]: It would be better to move all the test setup outside the `assertThrows` and narrow it down to the thing that we're expecting to throw an exception.

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java [hunk 11]
```diff
@@ -12319,61 +12313,64 @@ public void testRequireTimeConditionLogicalValuePositive()
   @Test
   public void testRequireTimeConditionSimpleQueryNegative()
   {
-    msqIncompatible();
-    expectedException.expect(CannotBuildQueryException.class);
-    expectedException.expectMessage("__time column");
+    Throwable exception = assertThrows(CannotBuildQueryException.class, () -> {
+      msqIncompatible();
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java:12317]: nit: Consider moving `msqIncompatible()` and any other test initialization outside `assertThrows`.
Same applies to the other tests

**Review by abhishekrb19 — APPROVED** [review]

File: sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java [hunk 12]
```diff
@@ -295,15 +298,11 @@ public static Map<String, Object> getTimeseriesContextWithFloorTime(
   public final SqlEngine engine0;
   final boolean useDefault = NullHandling.replaceWithDefault();
 
-  @Rule(order = 1)
-  public ExpectedException expectedException = ExpectedException.none();
-
   @Rule(order = 2)
```
Comment (abhishekrb19) [inline sql/src/test/java/org/apache/druid/sql/calcite/BaseCalciteQueryTest.java:301]: We can also remove the junit rule order or re-order the rules (same applies to `@Rule(order = 3) queryFrameworkRule`:
```suggestion
  @Rule
```

**Review by abhishekrb19 — APPROVED** [review]

**Comment by abhishekrb19** [comment]
The rule ordering cleanup changes can come in a later patch
