### PR TITLE
fix lookup nullable

### LINKED ISSUE #11038: sql LOOKUP() failure when filtering on a key value that is not present in the lookup
LOOKUP() bombs when you add a WHERE on the key, and you specify something that's not in the lookup table.

I have a small lookup, "myLookup", with this map:

```
{
  "#ar.wikipedia": "wikipedia lookup value"
}
```

and loaded wikipedia.  This query works (the channel in the WHERE exists in the lookup):

```
SELECT channel, LOOKUP(channel, 'myLookup')
FROM wikipedia
WHERE channel = '#ar.wikipedia'
```

This one gives an error (the channel in the WHERE does not exist in the lookup):

```
SELECT channel, LOOKUP(channel, 'myLookup')
FROM wikipedia
WHERE channel = 'test'
```

The error is:

```
javax.servlet.ServletException: java.lang.AssertionError: Cannot add expression of different type to set: set type is RecordType(VARCHAR channel, VARCHAR NOT NULL EXPR$1) NOT NULL expression type is RecordType(VARCHAR channel, VARCHAR EXPR$1) NOT NULL set is rel#6110:LogicalProject.NONE.[](input=HepRelVertex#6109,channel=$0,EXPR$1=LOOKUP($0, &apos;myLookup&apos;)) expression is LogicalProject(channel=[CAST(&apos;test&apos;:VARCHAR):VARCHAR], EXPR$1=[null:VARCHAR]) LogicalFilter(condition=[=($0, &apos;test&apos;)]) LogicalProject(channel=[$1]) LogicalTableScan(table=[[druid, wikipedia]])
```

The same logic will work as a JOIN, and properly return no results:

```
SELECT channel, v
FROM wikipedia
JOIN lookup.myLookup
ON channel = k
WHERE channel = 'test'
```

### PR DESCRIPTION
**Pull request by chenyuzhi459**
Fixes #11038.

### Description
When we use `lookup` func in sql, we will  return null value if we don't found. However, in `org.apache.druid.sql.calcite.expression.builtin.QueryLookupOperatorConversion`, it's returnType was defined as `returnTypeNonNull`, which casue a validation error in calcites.

### Solution
Change lookup func's return as nullable with `returnTypeNonNull`.

##### Key changed/added classes in this PR
 * `org.apache.druid.sql.calcite.expression.builtin.QueryLookupOperatorConversion`
<hr>

This PR has:
- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage]
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java [hunk 1]
```diff
@@ -17086,4 +17086,32 @@ public void testGroupingSetsWithLimitOrderByGran() throws Exception
...
+            .legacy(false)
+            .filters(new SelectorDimFilter("dim2", "", null))
+            .resultFormat(ScanQuery.ResultFormat.RESULT_FORMAT_COMPACTED_LIST)
+            .context(QUERY_CONTEXT_DEFAULT)
+            .build()
+        ),
+        ImmutableList.<Object[]>builder().add(
+            new Object[]{"", NULL_STRING},
+            new Object[]{"", NULL_STRING},
+            new Object[]{"", NULL_STRING}
```
Comment (clintropolis) [inline sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java:17113]: It looks like this is failing CI in SQL compatible null handling mode because the expected results are different, where there are only 2 null valued `dim2` rows instead of 3. The data for the 'foo' datasource is here: https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java#L368. In default mode (`druid.generic.useDefaultValueForNull=true`), the empty string is equivalent to null, so https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java#L390 is treated as null, but when `druid.generic.useDefaultValueForNull=false`, only https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java#L382 and https://github.com/apache/druid/blob/master/sql/src/test/java/org/apache/druid/sql/calcite/util/CalciteTests.java#L409 have null valued `dim2`. Additionally, `dim2` would be `null` instead of the empty string in the results.

Comment (chenyuzhi459) [reply sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java]: Thanks for reminding me. I have chang dimension `dim2` to `dim1` to solution this problem

Comment (clintropolis) [reply sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java]: I restarted CI for the failing test. Looking at the new test though, I'm not sure it tests the issue anymore since the input to the lookup is no longer null? I actually think maybe the old test was better, you just needed to adjust the expected output based on whether or not it is in default null handling mode or not.e.g 
```
List<Object[]> expected;
if (useDefault) {
  expected = ImmutableList.<Object[]>builder().add(
...
```
like some of the other tests are doing.

Comment (chenyuzhi459) [reply sql/src/test/java/org/apache/druid/sql/calcite/CalciteQueryTest.java]: ok, I think you are right , we should consider specail  situation.   
 I hava changed it to old test, and handled `null` case.

**Review by clintropolis — APPROVED** [review]
lgtm, thanks :+1:
