### PR TITLE
Empty partitionDimension has less rollup compared to when explicitly specified

### LINKED ISSUE #9846: Empty partitionDimension in Native Ingestion leads to lesser data rollup compared to explicit partitionDimension
### Affected Version

Druid v0.17.0 and v0.18.0

### Description

When you run a native ingestion spec without explicitly specifying partitionDimension, the data rollup observed is less than when you specify it explicitly. This behavior is contradictory to that observed in Hadoop and mentioned in the documentation.

### Steps to Reproduce

To generate data you can use this python script:

``` python
import json
import time
import random
import sys
n = 10
if len(sys.argv) == 2:
  n = int(sys.argv[1])
UNITS_IN_HOUR = 3600
now = int(time.time())
now -= now % UNITS_IN_HOUR
for i in range(n):
  obj = {"time" : now + random.randrange(UNITS_IN_HOUR)}
  for k in range(1, 7):
    obj["v" + str(k)] = i % (10 ** k)
  print(json.dumps(obj))
```
Create 3 files with n = 1000000
Ingest this data using the following spec
```
{
  "type": "index_parallel",
  "spec": {
    "ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "local",
        "filter": "*",
        "baseDir": "/path/to/data/"
      },
      "inputFormat": {
        "type": "json"
      }
    },
    "tuningConfig": {
      "type": "index_parallel",
      "partitionsSpec": {
        "type": "hashed",
        "numShards": 2,
        "partitionDimensions": [ "v1" ]
      },
      "forceGuaranteedRollup": true,
      "maxNumConcurrentSubTasks": 10
    },
    "dataSchema": {
      "dataSource": "1m_json_data",
      "granularitySpec": {
        "type": "uniform",
        "queryGranularity": "HOUR",
        "rollup": true,
        "intervals": [
          <change this range based on your time>
        ],
        "segmentGranularity": "DAY"
      },
      "timestampSpec": {
        "column": "time",
        "format": "posix"
      },
      "dimensionsSpec": {
        "dimensions": [
          {
            "type": "long",
            "name": "v1"
          }
        ]
      },
      "metricsSpec": [
        {
          "name": "count",
          "type": "count"
        },
        {
          "name": "sum_v2",
          "type": "longSum",
          "fieldName": "v2"
        },
        {
          "name": "sum_v3",
          "type": "longSum",
          "fieldName": "v3"
        },
        {
          "name": "sum_v4",
          "type": "longSum",
          "fieldName": "v4"
        },
        {
          "name": "sum_v5",
          "type": "longSum",
          "fieldName": "v5"
        },
        {
          "name": "sum_v6",
          "type": "longSum",
          "fieldName": "v6"
        }
      ]
    }
  }
}
```
You will find there are 10 rows being created once the ingestion complete.
Now remove the line `"partitionDimensions": [ "v1" ]`
You will find 20 rows getting created

### Problem Diagnosis

The problem arises in this piece of code: `src/main/java/org/apache/druid/timeline/partition/HashBasedNumberedShardSpec.java`

``` java
  @VisibleForTesting
  List<Object> getGroupKey(final long timestamp, final InputRow inputRow)
  {
    if (partitionDimensions.isEmpty()) {
      return Rows.toGroupKey(timestamp, inputRow);
    } else {
      return Lists.transform(partitionDimensions, inputRow::getDimension);
    }
  }
```
If `partitionDimension` is empty then we use `timestamp` as well as the `dimensions` to hash while we ignore the `timestamp` when we have an explicit `partitionDimension` present. I am not completely sure why that is the case but we can discuss.

That being said I found out this piece of code is also used for hadoop ingestion where we do not see this problem. The difference is in Hadoop we pass a constant timestamp by using something like this `rollupGran.bucketStart(inputRow.getTimestamp()).getMillis()`. This is missing in the native ingestion code path.

### Next Steps

I have both types of fixes implemented and tested. Hoping to hear your thoughts on this before moving ahead.

### PR DESCRIPTION
**Pull request by mghosh4**
Fixes #9846

### Description

Fixes the native ingestion issue where if you do not explicitly specify the partitionDimension, it leads to lesser rollup compared to the case when you do.

There are two possible solutions to the problem. More details in the original bug report. This implements one of the solution. 

The primary problem is when we hash a row during the generate phase, we use timestamp as part of the hashKey along with the dimensions in the dimensionSpec. When we explicitly specify partitionDimensions, we do not use timestamp. In the native ingestion path, using row timestamps messes up the bucket assignment for these rows and 2 rows with same dimension values can end up in different buckets. This leads to lesser rollup. More details in the bug report.

In this PR, I have made Native ingestion match what Hadoop does. Instead of sending the actual timestamp it sends the interval start corresponding to the interval bucket this timestamp falls in. 

#### Fixed the bug #9846 

<hr>

This PR has:
- [x] been self-reviewed.
- [ ] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

<hr>

### CODE REVIEW

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java [hunk 1]
```diff
@@ -1783,6 +1788,36 @@ public void testIndexTaskWithSingleDimPartitionsSpecThrowingException() throws E
...
+  @Test
+  public void testShardSpecSelectionWithNullPartitionDimension()
+  {
+    ShardSpec spec1 = new HashBasedNumberedShardSpec(0, 2, null, jsonMapper);
+    ShardSpec spec2 = new HashBasedNumberedShardSpec(1, 2, null, jsonMapper);
+
+    Map<Interval, List<ShardSpec>> shardSpecMap = new HashMap<>();
+    shardSpecMap.put(Intervals.of("2014-01-01T00:00:00.000Z/2014-01-02T00:00:00.000Z"), Lists.newArrayList(spec1, spec2));
+
+    IndexTask.ShardSpecs shardSpecs = new IndexTask.ShardSpecs(shardSpecMap, Granularity.fromString("HOUR"));
```
Comment (jihoonson) [inline indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java:1800]: nit: please use Granularities.HOUR.

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java [hunk 2]
```diff
@@ -1783,6 +1788,36 @@ public void testIndexTaskWithSingleDimPartitionsSpecThrowingException() throws E
...
+    String visitor_id = "visitor_id";
+    String client_type = "client_type";
```
Comment (jihoonson) [inline indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java:1802]: The Java convention is the camel case. Please rename these variables to `visitorId` and `clientType`.

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java [hunk 3]
```diff
@@ -1783,6 +1788,36 @@ public void testIndexTaskWithSingleDimPartitionsSpecThrowingException() throws E
...
+    long timestamp2 = DateTimes.of("2014-01-01T00:30:20.456Z").getMillis();
+    InputRow row2 = new MapBasedInputRow(timestamp2,
+        Lists.newArrayList(visitor_id, client_type),
+        ImmutableMap.of(visitor_id, "0", client_type, "iphone")
+    );
+
+    ShardSpec spec3 = shardSpecs.getShardSpec(Intervals.of("2014-01-01T00:00:00.000Z/2014-01-02T00:00:00.000Z"), row1);
+    ShardSpec spec4 = shardSpecs.getShardSpec(Intervals.of("2014-01-01T00:00:00.000Z/2014-01-02T00:00:00.000Z"), row2);
+
+    Assert.assertEquals(true, spec3 == spec4);
```
Comment (jihoonson) [inline indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java:1818]: Please use `Assert.assertSame()` instead.

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java [hunk 4]
```diff
@@ -1783,6 +1788,36 @@ public void testIndexTaskWithSingleDimPartitionsSpecThrowingException() throws E
...
+  }
```
Comment (jihoonson) [inline indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java:1819]: Could you please add a test that `shardSpecs.getShardSpec()` returns different shardSpecs for two rows when they have exactly same values but different timestamps?

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java [hunk 5]
```diff
@@ -1783,6 +1788,36 @@ public void testIndexTaskWithSingleDimPartitionsSpecThrowingException() throws E
     task.isReady(createActionClient(task));
   }
 
+  @Test
+  public void testShardSpecSelectionWithNullPartitionDimension()
```
Comment (jihoonson) [inline indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java:1792]: Thank you for adding a unit test! This test doesn't seem testing the `IndexTask` but testing `ShardSpecs`. Would you please move the `ShardSpecs` out of `IndexTask` and add a new class `ShardSpecsTest`? Then we can move this test to `ShardSpecsTest`.

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java (hunk 1 above)
Comment (mghosh4) [reply indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java]: Fixed

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java (hunk 2 above)
Comment (mghosh4) [reply indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java]: Fixed

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java (hunk 3 above)
Comment (mghosh4) [reply indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java]: Fixed

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java (hunk 5 above)
Comment (mghosh4) [reply indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java]: Fixed

File: indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java (hunk 4 above)
Comment (mghosh4) [reply indexing-service/src/test/java/org/apache/druid/indexing/common/task/IndexTaskTest.java]: Done

**Comment by RoseDaniel** [comment]
awesome work @mghosh4
