### PR TITLE
Initialize SettableByteEntityReader only when inputFormat is not null

### LINKED ISSUE #9728: NPE when using AvroStreamInputRowParser and Kafka
### Affected Version

0.18.0

### Description

This bug was added in #9625. Stack trace is

```java.lang.NullPointerException: inputFormatat com.google.common.base.Preconditions.checkNotNull(Preconditions.java:229) ~[guava-16.0.1.jar:?]at org.apache.druid.indexing.seekablestream.SettableByteEntityReader.<init>(SettableByteEntityReader.java:57) ~[druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.runInternal(SeekableStreamIndexTaskRunner.java:379) ~[druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTaskRunner.run(SeekableStreamIndexTaskRunner.java:276) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.seekablestream.SeekableStreamIndexTask.run(SeekableStreamIndexTask.java:164) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:421) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:393) [druid-indexing-service-0.18.0-iap3.jar:0.18.0-iap3]at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]```

### PR DESCRIPTION
**Pull request by jihoonson**
Fixes #9728 

### Description

`SettableByteEntityReader` has a null check in its constructor which throws NPE when `inputFormat` is null. This PR changes to creating it when `inputFormat` is not null.

<hr>

This PR has:
- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/licenses.yaml)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java [hunk 1]
```diff
@@ -38,20 +45,38 @@
...
+    ));
   }
 
   List<InputRow> parse(List<byte[]> streamChunk) throws IOException
   {
     if (parser != null) {
       return parseWithParser(parser, streamChunk);
     } else {
-      return parseWithInputFormat(byteEntityReader, streamChunk);
+      return parseWithInputFormat(lazyByteEntityReaderSupplier.get(), streamChunk);
```
Comment (clintropolis) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java:79]: Would it be better to prefer the inputFormat if it exists?

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java [hunk 2]
```diff
@@ -38,20 +45,38 @@
...
+      File indexingTmpDir
+  )
   {
+    if (parser == null && inputFormat == null) {
+      throw new IAE("Either parser or inputFormat shouldn't be set");
+    }
     this.parser = parser;
-    this.byteEntityReader = byteEntityReader;
+    // Create a lazy initializer since it will fail to create a SettableByteEntityReader if inputFormat is null
+    this.lazyByteEntityReaderSupplier = Suppliers.memoize(() -> new SettableByteEntityReader(
```
Comment (clintropolis) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java:66]: nit: Why a supplier instead of just making `byteEntityReader` `@Nullable`? it seems like it would not be used if `parser` is not null.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java [hunk 3]
```diff
@@ -38,20 +45,38 @@
...
+        inputFormat,
+        inputRowSchema,
+        transformSpec,
+        indexingTmpDir
+    ));
   }
 
   List<InputRow> parse(List<byte[]> streamChunk) throws IOException
   {
     if (parser != null) {
```
Comment (clintropolis) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java:76]: I know this isn't new, but why do we prefer the parser over the byteEntityReader if both are set?

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java [hunk 4]
```diff
@@ -38,20 +45,38 @@
...
+  StreamChunkParser(
+      @Nullable InputRowParser<ByteBuffer> parser,
+      @Nullable InputFormat inputFormat,
+      InputRowSchema inputRowSchema,
+      TransformSpec transformSpec,
+      File indexingTmpDir
+  )
   {
+    if (parser == null && inputFormat == null) {
+      throw new IAE("Either parser or inputFormat shouldn't be set");
```
[the remark this answers is not in the document]
Comment (jihoonson) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java]: Oops, thanks.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java (hunk 2 above)
Comment (jihoonson) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java]: Changed to nullable.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java (hunk 1 above)
Comment (jihoonson) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/StreamChunkParser.java]: Changed to prefer inputFormat.

File: core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java [hunk 5]
```diff
@@ -123,6 +124,12 @@ public int getSkipHeaderRows()
     );
   }
 
+  @Override
+  public InputFormat toInputFormat()
```
Comment (ccaominh) [inline core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java:128]: Where is the test that makes sure TSV is handled properly now? Also do we already have a similar test for CSV?

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java [hunk 6]
```diff
@@ -372,12 +373,10 @@ private TaskStatus runInternal(TaskToolbox toolbox) throws Exception
     // Now we can initialize StreamChunkReader with the given toolbox.
     final StreamChunkParser parser = new StreamChunkParser(
         this.parser,
-        new SettableByteEntityReader(
-            inputFormat,
-            inputRowSchema,
-            task.getDataSchema().getTransformSpec(),
-            toolbox.getIndexingTmpDir()
-        )
+        inputFormat,
```
Comment (ccaominh) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:376]: I think it would be good to add some tests for this class since it looks like the existing unit tests don't cover this class at all. For example, there's nothing ensuring that `parser` and `inputFormat` are both not `null` when they're passed to the `StreamChunkParser` constructor.

Also, it looks like we only have tests that ensure that real time ingestion works with JSON. We should add a tests to make sure real time ingestion never breaks in the future for Avro, TSV, etc.

File: indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/StreamChunkParserTest.java [hunk 7]
```diff
@@ -0,0 +1,183 @@
...
+        null,
+        null
+    );
+    final String json = "{\"timestamp\": \"2020-01-01\", \"dim\": \"val\", \"met\": \"val2\"}";
+    List<InputRow> parsedRows = chunkParser.parse(Collections.singletonList(json.getBytes(StringUtils.UTF8_STRING)));
+    Assert.assertEquals(1, parsedRows.size());
+    InputRow row = parsedRows.get(0);
+    Assert.assertEquals(DateTimes.of("2020-01-01"), row.getTimestamp());
+    Assert.assertEquals("val", Iterables.getOnlyElement(row.getDimension("dim")));
+    Assert.assertEquals("val2", Iterables.getOnlyElement(row.getDimension("met")));
```
Comment (ccaominh) [inline indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/StreamChunkParserTest.java:83]: This is repeated for two of the tests below, so may be worth factoring out.

File: core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java (hunk 5 above)
Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java:128]: What do you mean by "handling TSV properly"? This method does nothing useful for now. I think we should remove this method.

File: indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/StreamChunkParserTest.java (hunk 7 above)
Comment (jihoonson) [reply indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/StreamChunkParserTest.java]: Done.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java (hunk 6 above)
Comment (jihoonson) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:376]: > I think it would be good to add some tests for this class since it looks like the existing unit tests don't cover this class at all. For example, there's nothing ensuring that `parser` and `inputFormat` are both not `null` when they're passed to the `StreamChunkParser` constructor.

Hmm, I'm not sure I understood your comment. I believe this class is being tested in both `KafkaIndexTaskTest` and `KinesisIndexTaskTest`. Either `parser` or `inputFormat` can be set for kafka indexing service to work. If both are set, it prefers `inputFormat` over `parser.

> Also, it looks like we only have tests that ensure that real time ingestion works with JSON. We should add a tests to make sure real time ingestion never breaks in the future for Avro, TSV, etc.

Those tests seem useful, but I don't think adding them should be done in this PR since it's out of scope; the issue is creating a `SettableByteEntityReader` can fail with any parser in which `toInputFormat` is missing. I will add them in a follow-up PR.

**Comment by jihoonson** [comment]
I tested this PR by feeding Avro data into local Druid cluster.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java (hunk 6 above)
Comment (ccaominh) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:376]: Cool, I didn't look at the coverage from `KafkaIndexTaskTest` and `KinesisIndexTaskTest`, so my comment can be disregarded.

Adding the integration tests in a follow up PR sounds good to me since you manually verified your fix for the scenario that uncovered this bug.

File: core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java (hunk 5 above)
Comment (ccaominh) [reply core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java:128]: Sorry, my comment was more about adding integration tests for streaming ingestion with the various formats, which I believe we're missing. This can be addressed in a follow up PR that tackles the issue comprehensively.

Comment (jihoonson) [reply core/src/main/java/org/apache/druid/data/input/impl/DelimitedParseSpec.java:128]: Sounds good. I will add some tests with TSV in a follow-up PR.
