### PR TITLE
Fix classNotFoundException when connecting to secure LDAP

### LINKED ISSUE #9720: java.lang.ClassNotFoundException: org.apache.druid.security.basic.BasicSecuritySSLSocketFactory
When a druid is configured to authenticate against SSL enabled LDAP server Coordinator service throws `ClassNotFoundException`

**Exception trace from coordinator log:**

```
Caused by: java.lang.ClassNotFoundException: org.apache.druid.security.basic.BasicSecuritySSLSocketFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_242]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_242]
	at com.sun.jndi.ldap.VersionHelper12.loadClass(VersionHelper12.java:72) ~[?:1.8.0_242]
	at com.sun.jndi.ldap.Connection.createSocket(Connection.java:291) ~[?:1.8.0_242]
	at com.sun.jndi.ldap.Connection.<init>(Connection.java:213) ~[?:1.8.0_242]
	... 46 more
```

++++
**Steps to reproduce this issue:**
1) Configure druid to use SSL enabled LDAP authentication 
2) Start the master services. You can observe the exception in the coordinator log.

The issue can be quickly reproduced in micor start mode as well.
++++

**Few Interesting facts:**

1) Druid basic-security-extension is loaded and Verified that only one version of the druid-basic-security extension jar present into the druid security extension directory.

2)The coordinator log shows that the druid-basic-security extension jar being loaded.

3)Verified the druid-basic security extension jar and it has the BasicSecuritySSLSocketFactory.class

4) To extra confirm if BasicSecuritySSLSocketFactory class is loaded by coordinator JVM or not, Enabled verbose class loading and this confirms the BasicSecuritySSLSocketFactory class being loaded by the class loader, but still, coordinator throws `ClassNotFoundException`

`[Loaded org.apache.druid.security.basic.BasicSecuritySSLSocketFactory from file:<path to softeare>/druid-basic-security/druid-basic-security-0.17.1.jar:0.17.1]`

**Workaround:** – I placed druid-security-extension jar into the druid lib directory and restarted the server and this resolves the ClassNotFoundException.

It seems some jar dependency issues.

### PR DESCRIPTION
**Pull request by abhishekagarwal87**
Fixes #9720.
I have manually tested the fix. 

### Description

This PR fixes a problem where the `com.sun.jndi.ldap.Connection` tries to build `BasicSecuritySSLSocketFactory` when calling `LDAPCredentialsValidator.validateCredentials` since `BasicSecuritySSLSocketFactory` is in extension class loader and not visible to system classloader. 

<hr>

##### Key changed/added classes in this PR
 * `LDAPCredentialsValidator`

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authentication/validator/LDAPCredentialsValidator.java [hunk 1]
```diff
@@ -235,6 +245,7 @@ boolean validatePassword(BasicAuthLDAPConfig ldapConfig, LdapName userDn, char[]
         LOG.warn("Exception closing LDAP context");
         // ignored
       }
+      Thread.currentThread().setContextClassLoader(currentClassLoader);
```
Comment (LakshSingla) [inline extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authentication/validator/LDAPCredentialsValidator.java:248]: Should the classLoader be reset in a `finally` block? 
```suggestion
  finally {
      Thread.currentThread().setContextClassLoader(currentClassLoader);
  }
```

File: extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authentication/validator/LDAPCredentialsValidator.java [hunk 2]
```diff
@@ -213,8 +221,10 @@ SearchResult getLdapUserObject(BasicAuthLDAPConfig ldapConfig, DirContext contex
   boolean validatePassword(BasicAuthLDAPConfig ldapConfig, LdapName userDn, char[] password)
   {
     InitialDirContext context = null;
+    ClassLoader currentClassLoader = Thread.currentThread().getContextClassLoader();
```
Comment (cryptoe) [inline extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authentication/validator/LDAPCredentialsValidator.java:224]: nit: Can't we remove setting the classloader here ? 
Push the finally block after `validatePassword` and change the `validatePassword` scope to private ?

Comment (abhishekagarwal87) [reply extensions-core/druid-basic-security/src/main/java/org/apache/druid/security/basic/authentication/validator/LDAPCredentialsValidator.java:224]: The thought did cross my mind. I didn't want to tinker with the try/catch flow. I also don't know what the impact of opening `InitialDirContext` while one is already open, will be. Probably none. This change felt safer to do.

**Review by cryptoe — APPROVED** [review]

**Review by clintropolis — APPROVED** [review]
