### PR TITLE
Fix missing format strings in calls to DruidException.build 

### LINKED ISSUE #15055: Exception Eating duck in query failures flow
### Description
Found an exception eating duck in query failure slow ( esp segmentMetadata queries)

```
org.apache.druid.query.QueryInterruptedException: null
Caused by: java.lang.NullPointerException

org.apache.druid.error.DruidException: null
	at org.apache.druid.error.DruidException$DruidExceptionBuilder.build(DruidException.java:460) ~[druid-processing-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.error.QueryExceptionCompat.makeException(QueryExceptionCompat.java:50) ~[druid-processing-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.error.DruidException.fromFailure(DruidException.java:154) ~[druid-processing-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.server.QueryResultPusher.handleQueryException(QueryResultPusher.java:211) ~[druid-server-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.server.QueryResultPusher.push(QueryResultPusher.java:177) ~[druid-server-2023.09.0-iap.jar:2023.09.0-iap]
	at org.apache.druid.server.QueryResource.doPost(QueryResource.java:218) ~[druid-server-2023.09.0-iap.jar:2023.09.0-iap]
	at jdk.internal.reflect.GeneratedMethodAccessor252.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[jersey-server-1.19.4.jar:1.19.4]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[jersey-server-1.19.4.jar:1.19.4]

### PR DESCRIPTION
**Pull request by pranavbhole**
Fixes #15055 

### Description
PR fix exception eating duck and helps to surface the original exception, 
  
 `String.format(Locale.ENGLISH, null, 1); or  String.format(Locale.ENGLISH, null);`
    
throws NPE and I safeguarding the nonStrictFormat function with null check. 
    
```
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.Formatter.parse(Formatter.java:2547)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2981)
```
#### Added a forbidden-apis entry ...

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/java/util/common/StringUtils.java [hunk 1]
```diff
@@ -373,16 +373,24 @@ public static String nonStrictFormat(String message, Object... formatArgs)
     if (formatArgs == null || formatArgs.length == 0) {
       return message;
     }
+    if (message == null) {
```
Comment (kfaraz) [inline processing/src/main/java/org/apache/druid/java/util/common/StringUtils.java:376]: Instead of these changes, it would be simpler to just do a `Preconditions.notNull(message)` at the start of this method.

Comment (pranavbhole) [reply processing/src/main/java/org/apache/druid/java/util/common/StringUtils.java:376]: Preconditions check will throw an exception again.   Some of the exceptions are not having message at all and we are calling nonStrictFormat while making DruidException, esp exception from third party library. As the name says, expectation from nonStrictFormat in this case is that it should just give back some non null string. Best case effort is to append the args to string and give it back.

If we add precondition then we need to safeguard the invoker lines with not null.

**Comment by gianm** [comment]
Anything that is calling `StringUtils.nonStrictFormat` with a `null` format string is a bug. In the case of #15055, the bug is that `QueryExceptionCompat#makeException` calls `druidException.build(exception, exception.getMessage())`. The `build` method expects a format string in the second parameter. The call should instead be `.build(exception, "%s", exception.getMessage())`.

IMO, better to fix the above bug than to work around it in `StringUtils#nonStrictFormat`.

Btw, looking at other calls to `DruidException#build` I see a bunch of places that have the same problem, where they pass a regular string instead of a format string. Many of them should be changed from `build(e, s)` to `build(e, "%s", s)`.

**Review by kgyrtkirk — APPROVED** [review]
not sure how `null` could have been passed as `message` ; but maybe it would be good to mark that arg as `@NonNull`  in case something could process and uncover its source in the future

or possibly enable:
https://errorprone.info/api/latest/com/google/errorprone/annotations/FormatString.html
so that `-DstrictCompile` could possibly catch formatting issues
not sure if it that would have worked in this case...

File: processing/src/main/java/org/apache/druid/java/util/common/StringUtils.java (hunk 1 above)
Comment (pranavbhole) [reply processing/src/main/java/org/apache/druid/java/util/common/StringUtils.java]: Based on comments, I found the instances where we could potentially pass null as formatString. I fixed all of them I could find in this PR. I am still doubtful about adding precondition check to nonStrictFormat as it is used at tons of places. I removed the change here and fixing the invokers.

**Comment by pranavbhole** [comment]
> Anything that is calling `StringUtils.nonStrictFormat` with a `null` format string is a bug. In the case of #15055, the bug is that `QueryExceptionCompat#makeException` calls `druidException.build(exception, exception.getMessage())`. The `build` method expects a format string in the second parameter. The call should instead be `.build(exception, "%s", exception.getMessage())`.
> 
> IMO, better to fix the above bug than to work around it in `StringUtils#nonStrictFormat`.
> 
> Btw, looking at other calls to `DruidException#build` I see a bunch of places that have the same problem, where they pass a regular string instead of a format string. Many of them should be changed from `build(e, s)` to `build(e, "%s", s)`. We should fix these too. Even if `s` is not null, it is problematic if it contains `%` characters that will be interpreted in special ways by the formatter.

Thank you, I was able to find the potential null at multiple places, fixed all of them I could find. Added test to StringUtilsTest to ensure formatting with string containing `%` char.

**Comment by kgyrtkirk** [comment]
I've played around a bit with adding `@FormatMethod/@FormatString` annotations; it uncovers a few more real and theoretical issues - but it will take some time to address all of them in the whole project :)

https://github.com/kgyrtkirk/druid/tree/formatmethod-formatstring

**Comment by pranavbhole** [comment]
> I've played around a bit with adding `@FormatMethod/@FormatString` annotations; it uncovers a few more real and theoretical issues - but it will take some time to address all of them in the whole project :)
> 
> https://github.com/kgyrtkirk/druid/tree/formatmethod-formatstring

great, it would be helpful to open another followup PR after this with annotation.

**Comment by pranavbhole** [comment]
@gianm @kfaraz 
Addressed comments, please review again.
Thank you

**Review by somu-imply — APPROVED** [review]
Nice find ! LGTM

**Comment by gianm** [comment]
> I've played around a bit with adding `@FormatMethod/@FormatString` annotations; it uncovers a few more real and theoretical issues - but it will take some time to address all of them in the whole project :)

Neat, nice idea!

**Review by gianm — COMMENTED** [review]
Changes LGTM, although the title of the PR is no longer correct. Please update it to something like "Fix missing format strings in calls to DruidException.build"

File: processing/src/test/java/org/apache/druid/java/util/common/StringUtilsTest.java [hunk 2]
```diff
@@ -386,4 +386,19 @@ public void testJavaStringCompare()
       }
     }
   }
+
+  @Test(expected = NullPointerException.class)
```
Comment (clintropolis) [inline processing/src/test/java/org/apache/druid/java/util/common/StringUtilsTest.java:390]: nit: maybe use `Assert.assertThrows` instead of expected exceptions

**Review by clintropolis — APPROVED** [review]

File: processing/src/test/java/org/apache/druid/java/util/common/StringUtilsTest.java (hunk 2 above)
Comment (pranavbhole) [reply processing/src/test/java/org/apache/druid/java/util/common/StringUtilsTest.java]: fixed

**Review by gianm — APPROVED** [review]
