### PR TITLE
[Issue 10331] Fresh Docker install results in "Uh... I have no servers. Not assigning anything...

### LINKED ISSUE #10331: Fresh Docker install results in "Uh... I have no servers. Not assigning anything... "
I have a fresh VM running Ubuntu 18.04 LTS configured with 4 CPUs and 4 GB of RAM. I've installed Docker and downloaded the Druid archive from github. 

After the command `docker-compose -f distribution/docker/docker-compose.yml up` the system starts loading and the container boots up. The Druid console is accessible at http://localhost:8888/. Configuring the data source to load the tutorial data goes as expected. After submitting the data spec, an error is displayed in the Ingestion window: _HTML Error: org.apache.druid.java.util.common.ISE: No default server found!_. Similarly, no data sources are shown in the Datasources window.
In the console of the Docker container there is frequent the message _Uh... I have no servers. Not assigning anything..._

### Affected Version

Latest-n-greatest: Druid-0.19.0

### Console snippet
`coordinator      | 2020-08-28T11:35:13,805 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] used segments.
coordinator      | 2020-08-28T11:35:13,805 WARN [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorRuleRunner - Uh... I have no servers. Not assigning anything...
coordinator      | 2020-08-28T11:35:13,805 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
coordinator      | 2020-08-28T11:35:18,809 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] used segments.
coordinator      | 2020-08-28T11:35:18,809 WARN [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorRuleRunner - Uh... I have no servers. Not assigning anything...
coordinator      | 2020-08-28T11:35:18,809 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
coordinator      | 2020-08-28T11:35:21,278 DEBUG [qtp23218037-120] org.apache.druid.jetty.RequestLog - 172.18.0.8 GET //172.18.0.4:8081/druid/coordinator/v1/rules HTTP/1.1
coordinator      | 2020-08-28T11:35:22,064 INFO [DatabaseRuleManager-Exec--0] org.apache.druid.metadata.SQLMetadataRuleManager - Polled and found 1 rule(s) for 1 datasource(s)
coordinator      | 2020-08-28T11:35:22,518 INFO [org.apache.druid.metadata.SQLMetadataSegmentManager-Exec--0] org.apache.druid.metadata.SQLMetadataSegmentManager - No segments found in the database!
coordinator      | 2020-08-28T11:35:22,877 INFO [TaskQueue-StorageSync] org.apache.druid.indexing.overlord.TaskQueue - Synced 0 tasks from storage (0 tasks added, 0 tasks removed).
coordinator      | 2020-08-28T11:35:23,811 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] used segments.
coordinator      | 2020-08-28T11:35:23,811 WARN [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorRuleRunner - Uh... I have no servers. Not assigning anything...
coordinator      | 2020-08-28T11:35:23,811 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
coordinator      | 2020-08-28T11:35:28,814 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] used segments.
coordinator      | 2020-08-28T11:35:28,815 WARN [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorRuleRunner - Uh... I have no servers. Not assigning anything...
coordinator      | 2020-08-28T11:35:28,815 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
coordinator      | 2020-08-28T11:35:33,817 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] used segments.
coordinator      | 2020-08-28T11:35:33,818 WARN [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorRuleRunner - Uh... I have no servers. Not assigning anything...
coordinator      | 2020-08-28T11:35:33,818 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
coordinator      | 2020-08-28T11:35:38,821 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorSegmentInfoLoader - Found [0] used segments.
coordinator      | 2020-08-28T11:35:38,821 WARN [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorRuleRunner - Uh... I have no servers. Not assigning anything...
coordinator      | 2020-08-28T11:35:38,822 INFO [Coordinator-Exec--0] org.apache.druid.server.coordinator.helper.DruidCoordinatorLogger - Load Queues:
router           | 2020-08-28T11:35:40,046 ERROR [qtp1151370725-68] org.apache.druid.server.router.QueryHostFinder - WTF?! No server found for serviceName[druid/broker]. Using backup
router           | 2020-08-28T11:35:40,047 ERROR [qtp1151370725-68] org.apache.druid.server.router.QueryHostFinder - WTF?! No backup found for serviceName[druid/broker]. Using default[druid/broker]
router           | 2020-08-28T11:35:40,047 ERROR [qtp1151370725-68] org.apache.druid.server.router.QueryHostFinder - Catastrophic failure! No servers found at all! Failing request!: {class=org.apache.druid.server.router.QueryHostFinder}
router           | 2020-08-28T11:35:40,047 WARN [qtp1151370725-68] org.eclipse.jetty.server.HttpChannel - /druid/v2/sql
router           | org.apache.druid.java.util.common.ISE: No default server found!
router           |      at org.apache.druid.server.router.QueryHostFinder.pickDefaultServer(QueryHostFinder.java:119) ~[druid-server-0.17.0.jar:0.17.0]
router           |      at org.apache.druid.server.AsyncQueryForwardingServlet.service(AsyncQueryForwardingServlet.java:271) ~[druid-server-0.17.0.jar:0.17.0]
router           |      at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) ~[javax.servlet-api-3.1.0.jar:3.1.0]
router           |      at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
router           |      at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655) ~[jetty-servlet-9.4.12.v20180830.jar:9.4.12.v20180830]
`

### PR DESCRIPTION
**Pull request by wiquan**
### Description
The docker-compose.yml file uses hardcoded 'conf/druid/single-server' configurations. 
This results in OOM killed broker as described in [Issue#10331](https://github.com/apache/druid/issues/10331). 

The suggestion was:
> Maybe we should update the docker-compose settings to use either the "nano" or "micro" settings from https://druid.apache.org/docs/latest/operations/single-server.html. (Or have two docker-compose config bundles, one for "nano" and one for "micro".) That would probably help. A PR to do that would be great.

This was the goal of this PR.

The change was to include a new env var **DRUID_SINGLE_NODE_CONF** that takes a value from the list:
- large 
- medium
- micro-quickstart
- nano-quickstart 
- small
- xlarge

This would get injected into the container via docker-compose env vars.
Since I use this on my Mac M1, I have modified environment file to specify 'DRUID_SINGLE_NODE_CONF=micro-quickstart' .

An example modified environment file is part of this PR.

#### Fixed the bug 
Since docker-compose files are typically for local development it made sense to use the smaller memory profiles. 

I also create a multi-arch Docker image with buildx for my Mac M1 with support for:
- linux/amd64
- linux/arm64

This can be provided if needed.

##### Key changed/added classes in this PR
 * `druid.sh` new shell functions for conf path resolution

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: distribution/docker/druid.sh [hunk 1]
```diff
@@ -50,6 +51,27 @@ test -d /tmp/conf/druid && rm -r /tmp/conf/druid
...
+    cluster_conf_base=/tmp/conf/druid/single-server
+    case "$1" in
+    _common) echo $cluster_conf_base/$DRUID_SINGLE_NODE_CONF/_common ;;
+    historical) echo $cluster_conf_base/$DRUID_SINGLE_NODE_CONF/historical ;;
+    middleManager) echo $cluster_conf_base/$DRUID_SINGLE_NODE_CONF/middleManager ;;
+#    indexer) echo $cluster_conf_base/data/indexer ;;
+    coordinator | overlord) echo $cluster_conf_base/$DRUID_SINGLE_NODE_CONF/coordinator-overlord ;;
+    broker) echo $cluster_conf_base/$DRUID_SINGLE_NODE_CONF/broker ;;
+    router) echo $cluster_conf_base/$DRUID_SINGLE_NODE_CONF/router ;;
+    *) echo $cluster_conf_base/misc/$1 ;;
```
Comment (abhishekagarwal87) [inline distribution/docker/druid.sh:71]: nit:
```suggestion
    single_node_conf_base=/tmp/conf/druid/single-server/$DRUID_SINGLE_NODE_CONF
    case "$1" in
    _common) echo $single_node_conf_base/_common ;;
    historical) echo $single_node_conf_base/historical ;;
    middleManager) echo $single_node_conf_base/middleManager ;;
    coordinator | overlord) echo $single_node_conf_base/coordinator-overlord ;;
    broker) echo $single_node_conf_base/broker ;;
    router) echo $single_node_conf_base/router ;;
    *) echo $single_node_conf_base/misc/$1 ;;
```

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
Thank you for your contribution @wiquan. I have merged your PR since my comment was more of a nit.
