### PR TITLE
Pull up literals in InputAccessor

### LINKED ISSUE #15353: Not able to set literal arguments for sketch functions processing subquery results
Sketch aggregator creation fails; because the argument doesn't [look like a literal](https://github.com/apache/druid/blob/895e53555cf69cce992ee54d8523624fe1150214/extensions-core/datasketches/src/main/java/org/apache/druid/query/aggregation/datasketches/hll/sql/HllSketchBaseSqlAggregator.java#L90)

queries like `DS_HLL(dim2, 18)` may fail; however `DS_HLL(dim2)` could still be used (but it will use defaults)

### Affected Version

current master for sure...possibly introduced earlier; will update the ticket

### Description

the query plan has an inputref instead of a literal:
```
LogicalAggregate(group=[{0, 1}], val=[APPROX_COUNT_DISTINCT_DS_HLL($1, $2)]): rowcount = 1.0, cumulative cost = {217.125 rows, 673.6669492803463 cpu, 0.0 io}, id = 157
  LogicalProject(d1=[$0], dim2=[$2], $f2=[18]): rowcount = 3.0, cumulative cost = {216.0 rows, 673.6669492803463 cpu, 0.0 io}, id = 155
    LogicalSort(sort0=[$1], dir0=[ASC], fetch=[3]): rowcount = 3.0, cumulative cost = {213.0 rows, 664.6669492803463 cpu, 0.0 io}, id = 153
      LogicalAggregate(group=[{0, 1, 2}]): rowcount = 10.0, cumulative cost = {210.0 rows, 401.0 cpu, 0.0 io}, id = 151
        LogicalProject(d1=[$7], dim1=[$1], dim2=[$2]): rowcount = 100.0, cumulative cost = {200.0 rows, 401.0 cpu, 0.0 io}, id = 149
          LogicalTableScan(table=[[druid, foo]]): rowcount = 100.0, cumulative cost = {100.0 rows, 101.0 cpu, 0.0 io}, id = 125
```

testcase for `HllSketchSqlAggregatorTest`:
```
  @Test
  public void testDsHllGroupingWithWindow()
  {
    testBuilder()
        .queryContext(ImmutableMap.of(QueryContexts.ENABLE_DEBUG, true))
        .sql(
            "SELECT d1,dim2,APPROX_COUNT_DISTINCT_DS_HLL(dim2, 18) as val"
                + " FROM (select d1,dim1,dim2 from druid.foo group by d1,dim1,dim2 order by dim1 limit 3) t "
                + " group by 1,2"
        )
        .run();
  }
```

### PR DESCRIPTION
**Pull request by kgyrtkirk**
* pull up literals in `InputAccessor`
* remove the need to pass `constants` of `Window`  operator

Fixes #15353

This PR has:

- [x] been self-reviewed.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.

### CODE REVIEW

File: extensions-core/datasketches/src/test/java/org/apache/druid/query/aggregation/datasketches/hll/sql/HllSketchSqlAggregatorTest.java [hunk 1]
```diff
@@ -1318,6 +1320,20 @@ public void testFloatAndDoubleAreConsideredTheSame()
     );
   }
 
+  @Test
+  public void testDsHllOnTopOfNested()
+  {
+    // this query was not planable: https://github.com/apache/druid/issues/15353
+    testBuilder()
+        .queryContext(ImmutableMap.of(QueryContexts.ENABLE_DEBUG, true))
```
Comment (soumyava) [inline extensions-core/datasketches/src/test/java/org/apache/druid/query/aggregation/datasketches/hll/sql/HllSketchSqlAggregatorTest.java:1328]: Probably just use QUERY_CONTEXT_DEFAULT here and not  introduce debug mode for a test case

File: extensions-core/datasketches/src/test/java/org/apache/druid/query/aggregation/datasketches/hll/sql/HllSketchSqlAggregatorTest.java [hunk 2]
```diff
@@ -1318,6 +1320,20 @@ public void testFloatAndDoubleAreConsideredTheSame()
...
+        .sql(
+            "SELECT d1,dim2,APPROX_COUNT_DISTINCT_DS_HLL(dim2, 18) as val"
+                + " FROM (select d1,dim1,dim2 from druid.foo group by d1,dim1,dim2 order by dim1 limit 3) t "
+                + " group by 1,2"
+        )
+        .run();
```
Comment (soumyava) [inline extensions-core/datasketches/src/test/java/org/apache/druid/query/aggregation/datasketches/hll/sql/HllSketchSqlAggregatorTest.java:1334]: We should add the expected results of this query as well to make sure the results do not change later down the line

Comment (kgyrtkirk) [reply extensions-core/datasketches/src/test/java/org/apache/druid/query/aggregation/datasketches/hll/sql/HllSketchSqlAggregatorTest.java:1339]: yeah - I've added it! :)
thank you for taking a look!
