### PR TITLE
Web console: show segment sizes in rows not bytes

### LINKED ISSUE #10507: Web console datasources screen is broken when there are datasources with no loaded segments (ArithmeticException)
### Affected Version

0.20.0

### Description

When there is a datasource with no loaded segments, the Datasources screen on the Web Console fails to load.
This can be reproduced if all the historical nodes are shutdown.

The error is being caused by a division by zero:
```
Error: Unknown exception

/ by zero

java.lang.ArithmeticException
```

image

image

The issue seems to be related with the recently added `avg_row_size` column:
https://github.com/apache/druid/blob/567e38170500d3649cbfaa28cf7aa6f5275d02e7/web-console/src/views/datasource-view/datasource-view.tsx#L241-L244

Commenting the code for this column allows the query to run:

image

### PR DESCRIPTION
**Pull request by vogievetsky**
This PR addresses the feedback from the recent work on the new segment distribution in the console. Segment sizes should be in rows not megabytes to fit with the new Druid documentation https://github.com/apache/druid/blob/master/docs/operations/segment-optimization.md

Old:

image

New:

image

This PR also cleans up some types and adds a nice little error action hint for 3 of the most common SQL query errors (see bottom of screenshot):

image

Also fixes #10507

### CODE REVIEW

File: web-console/src/utils/druid-query.ts [hunk 1]
```diff
@@ -92,12 +97,55 @@ export class DruidError extends Error {
...
+        label: `Replace "${literalString}" with '${literalString}'`,
+        fn: str => {
+          if (!str.includes(`"${literalString}"`)) return;
+          return str.replace(`"${literalString}"`, `'${literalString}'`);
+        },
+      };
+    }
+
+    // , before FROM
+    const mc = errorMessage.match(/Encountered "(FROM)" at/i);
```
Comment (suneet-s) [inline web-console/src/utils/druid-query.ts:126]: what does `mq` and `mc` stand for?

File: web-console/src/utils/druid-query.ts [hunk 2]
```diff
@@ -92,12 +97,55 @@ export class DruidError extends Error {
...
   }
 
+  static getSuggestion(errorMessage: string): QuerySuggestion | undefined {
+    // == is used instead of =
+    if (errorMessage.includes('Encountered "= =" at')) {
+      return {
+        label: `Replace == with =`,
+        fn: str => {
+          if (!str.includes('==')) return;
+          return str.replace(/==/g, '=');
```
Comment (suneet-s) [inline web-console/src/utils/druid-query.ts:107]: what if `==` is part of a literal? Does `str#replace` replace all instances of the regex in the string?

File: web-console/src/views/datasource-view/datasource-view.tsx [hunk 3]
```diff
@@ -1011,11 +1006,11 @@ GROUP BY 1`;
               ),
             },
             {
-              Header: twoLines('Segment size (MB)', 'min / avg / max'),
+              Header: twoLines('Segment size (rows)', 'minimum / average / maximum'),
               show: hiddenColumns.exists('Segment size'),
               accessor: 'avg_segment_size',
               filterable: false,
-              width: 150,
+              width: 220,
```
Comment (suneet-s) [inline web-console/src/views/datasource-view/datasource-view.tsx:1013]: Is this wide enough to handle 7 digits for min, avg and max?

From the doc linked in this PR `it's generally recommended for each segment to have around 5 million rows`
Do you think it's users would want to see a rounded number instead - something like `2.1M` instead of `2,105,248`
^ just a thought

**Comment by abhishekagarwal87** [comment]
is the segment size in bytes not going to be shown anywhere in the UI?

File: web-console/src/utils/druid-query.ts (hunk 2 above)
Comment (vogievetsky) [reply web-console/src/utils/druid-query.ts:107]: yeah it is pretty blunt, just replaces all the `==` with `=`... Maybe it should be aware of the line markers in the error text

File: web-console/src/views/datasource-view/datasource-view.tsx (hunk 3 above)
Comment (suneet-s) [reply web-console/src/views/datasource-view/datasource-view.tsx:1013]: I don't have a strong opinion on this, and will defer to your judgement.

The risk with rounding to millions is that for smaller datasources, it could always show `0.000 M`

I wonder if the UI could use the largest rounding per datasource. So you could have something like

```
DS1    5.343 M, 0.004 M, 0.000 M
DS2    0.320 k, 0.120 k, 321.1 k
``` 

^ even in this example, I'm really confused about how to pick whether to keep it as `321.1 k` or `0.321 M`

Number formatting isn't my forte 🙃

Comment (vogievetsky) [reply web-console/src/views/datasource-view/datasource-view.tsx:1013]: What do you think about

image

The only numbers that would be rendered as `0.000 M` would be numbers `<= 500` so we could display them directly.
Side note: There is a style pass happening on a different branch that would change the font to one that has monospaced numbers

**Comment by vogievetsky** [comment]
> is the segment size in bytes not going to be shown anywhere in the UI?

I was thinking to only show one... maybe we could add all the details in the ... detail view

Another tab in this dialog

File: web-console/src/views/datasource-view/datasource-view.tsx (hunk 3 above)
Comment (suneet-s) [reply web-console/src/views/datasource-view/datasource-view.tsx:1014]: 👍

**Comment by abhishekagarwal87** [comment]
> is the segment size in bytes not going to be shown anywhere in the UI?
> 
> I was thinking to only show one... maybe we could add all the details in the ... detail view
> 
> Another tab in this dialog
Thanks. The `segments` tab has all the details so that suffices.

File: web-console/src/views/datasource-view/datasource-view.tsx [hunk 4]
```diff
@@ -144,42 +144,41 @@ function progress(done: number, awaiting: number): number {
...
+  readonly datasource: string;
+  readonly num_segments: number;
+  readonly num_available_segments: number;
+  readonly num_segments_to_load: number;
+  readonly num_segments_to_drop: number;
+  readonly total_data_size: number;
+  readonly replicated_size: number;
+  readonly min_segment_size: number;
+  readonly avg_segment_size: number;
+  readonly max_segment_size: number;
```
Comment (suneet-s) [inline web-console/src/views/datasource-view/datasource-view.tsx:157]: nit: should this be `min_segment_rows` ... instead of size?

**Review by suneet-s — COMMENTED** [review]
LGTM with 1 question

**Comment by vogievetsky** [comment]
I thought that size could be measured in rows... will rename

**Review by suneet-s — APPROVED** [review]

**Comment by suneet-s** [comment]
> I thought that size could be measured in rows... will rename

Marked the change as Approved. I see `avg_row_size` is in MB which is what made me think about the difference between that and `min_segment_size`

File: web-console/src/views/datasource-view/datasource-view.tsx (hunk 4 above)
Comment (vogievetsky) [reply web-console/src/views/datasource-view/datasource-view.tsx]: fixed

**Review by suneet-s — APPROVED** [review]
LGTM 👍
