### PR TITLE
Fix missing temp dir for native single_dim

### LINKED ISSUE #9467: Ingestion fails on 'Connection reset by peer' when using native parallel ingestion
### Affected Version
druid 0.17
### Description
When running native ingestion with "index_parallel" on druid 0.17. 
I receive the following error:
`java.io.IOException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.io.IOException: Connection reset by peer 
at org.apache.druid.java.util.common.FileUtils.copyLarge(FileUtils.java:311) ~[druid-core-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.common.task.batch.parallel.PartialSegmentMergeTask.fetchSegmentFile(PartialSegmentMergeTask.java:261) ~[druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.common.task.batch.parallel.PartialSegmentMergeTask.fetchSegmentFiles(PartialSegmentMergeTask.java:236) ~[druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.common.task.batch.parallel.PartialSegmentMergeTask.runTask(PartialSegmentMergeTask.java:178) ~[druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.common.task.batch.parallel.PartialGenericSegmentMergeTask.runTask(PartialGenericSegmentMergeTask.java:44) ~[druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.common.task.AbstractBatchIndexTask.run(AbstractBatchIndexTask.java:138) ~[druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:419) [druid-indexing-service-0.17.0.jar:0.17.0]
	at org.apache.druid.indexing.overlord.SingleTaskBackgroundRunner$SingleTaskBackgroundRunnerCallable.call(SingleTaskBackgroundRunner.java:391) [druid-indexing-service-0.17.0.jar:0.17.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]`

I am sending the following task to overlord:
`{
  "type" : "index_parallel",
  "spec" : {
    "ioConfig" : {
      "type": "index_parallel",
      "inputSource": {
        "type": "s3",
        "prefixes": ["s3://filePAth"]
      },
      "inputFormat": {
        "type": "json"
      }
    },
    "dataSchema" : {
      "dataSource" : "test_batch",
      "granularitySpec" : {
        "type" : "uniform",
        "segmentGranularity" : "HOUR",
        "queryGranularity" : "HOUR",
        "intervals" : ["2018-10-06/2018-10-07"]
      },
      "dimensionsSpec" : {
        "dimensions" : [
          "filed1","field2","field3"
        ]
        },
        "timestampSpec" : {
            "format" : "auto",
            "column" : "timestamp"
        },
    },
    "tuningConfig" : {
      "type": "index_parallel",
      "maxNumConcurrentSubTasks": 2,
      "partitionsSpec" : {
       "type": "single_dim",
       "targetRowsPerSegment": 100000,
       "partitionDimension": "field1"
      }
    }
  }
}

`
The strange thing is that when removing the "partitionSpec" everything works well.
Thanks.

### PR DESCRIPTION
**Pull request by morrifeldman**
Fixes #9467 .

### Description

Native single dim indexing throws a file not found exception from
InputEntityIteratingReader.java:81.

This PR moves the temporary directory creation step into `TaskTookBox.getIndexingTmpDir` so that the directory will be automatically created.  It also removes directory creation code from other callers `TaskTookBox.getIndexingTmpDir` since they no longer need to create the directory themselves.

The change was tested on a Druid cluster.  After installing the change native single_dim indexing
completes successfully.

<hr>

This PR has:
- [x] been self-reviewed.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

<hr>

##### Key changed/added classes in this PR
 * `PartialDimensionDistributionTask`

### CODE REVIEW

File: indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTask.java [hunk 1]
```diff
@@ -200,6 +202,10 @@ public TaskStatus runTask(TaskToolbox toolbox) throws Exception
     Preconditions.checkNotNull(partitionDimension, "partitionDimension required in partitionsSpec");
     boolean isAssumeGrouped = partitionsSpec.isAssumeGrouped();
 
+    final File tmpDir = toolbox.getIndexingTmpDir();
+    // Temporary directory is automatically removed when this IndexTask completes.
+    FileUtils.forceMkdir(tmpDir);
```
Comment (jihoonson) [inline indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTask.java:207]: How about pushing this code into `TaskToolbox.getIndexingTmpDir()`? We can check if the directory exists first and then create one.

Comment (morrifeldman) [reply indexing-service/src/main/java/org/apache/druid/indexing/common/task/batch/parallel/PartialDimensionDistributionTask.java]: Good idea.  `forceMkdir` has guards to check if the directory already exists and is actually a directory rather than a file, so I didn't add any extra guards in TaskToolbox.
