### PR TITLE
Handle unknown complex types

### LINKED ISSUE #9421: Unknown complex types break Druid SQL
### Affected Version

0.16.0

### Description

After upgrading our clusters to 0.16.0, we noticed that the Druid SQL wasn't working because the metadata updates in DruidSchema were failing because of unknown aggregators in the segment metadata.

Turns out, in 0.16.0, I made a backward incompatible change in t-digest aggregator extension where I removed the aggregator types `buildTDigestSketch` and `mergeTDigestSketch` and replaced it with a single aggregator `tDigestSketch`. 

We had some users ingest their data using the `buildTDigestSketch` aggregator. However, when the 0.16.0 cluster was deployed, it wasn't able to deserialize the aggregator metadata as they were removed. This caused problems for the Druid SQL metadata cache as SegmentMetadataRequests started failing which in turn completely broke the Druid SQL functionality on the cluster. 

I think we should fix this and prevent future cases of someone making incompatible changes, especially in extensions-contrib modules, from breaking a core Druid functionality.

### PR DESCRIPTION
**Pull request by samarthjain**
Fixes #9421 

This PR has:
- [X ] been self-reviewed.
   - [X ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ X] added documentation for new or modified features or behaviors.
- [ X] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [X ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [X ] been tested in a test Druid cluster.

##### Key changed/added classes in this PR
 * UnknownTypeComplexColumn.java

### CODE REVIEW

**Comment by samarthjain** [comment]
@gianm - appreciate if you can take a look. I tested it out on our cluster and I see the DruidSchema cache is working fine again since the SegmentMetadata queries are no longer failing with NPE when encountering unknown aggregators.

**Comment by samarthjain** [comment]
Pushed a commit to add test that breaks without this patch.

**Comment by samarthjain** [comment]
Thanks for reviewing, @jihoonson . Will merge after CI passes.

File: processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java [hunk 1]
```diff
@@ -0,0 +1,99 @@
...
+  @Override
+  public void close()
+  {
+
+  }
+
+  @Override
+  public ColumnValueSelector<?> makeColumnValueSelector(ReadableOffset offset)
+  {
+    return NilColumnValueSelector.instance();
```
Comment (clintropolis) [inline processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:91]: should this method and `makeVectorObjectSelector` maybe log.warn to provide evidence that this is happening? Or do you expect that would be too noisy?

File: processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+  }
+
+  @Override
+  public VectorObjectSelector makeVectorObjectSelector(ReadableVectorOffset offset)
+  {
+    return NIL_VECTOR_SELECTOR_INSTANCE;
```
Comment (clintropolis) [inline processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:97]: This should I think be making a `NilVectorSelector` from the `offset` so that max vector size is set correctly

Comment (jihoonson) [reply processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:97]: Oops, good point. @samarthjain could you please fix this?

Comment (samarthjain) [reply processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:97]: @clintropolis - can you provide me a snippet of what needs to be done. I don't see a method available in `NilVectorSelector` that would taking in `ReadableVectorOffset`

Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:97]: `ReadableVectorOffset` is a `VectorSizeInspector`, so I think `return NilVectorSelector.create(offset);` is all you need to do.

File: processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java (hunk 1 above)
Comment (samarthjain) [reply processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:91]: I thought about it. While it wouldn't be too noisy, it made me think will it give us enough information to understand which column is actually invalid now?

File: processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java (hunk 2 above)
Comment (samarthjain) [reply processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:97]: Thanks!

File: processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java (hunk 1 above)
Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:91]: Yeah, it wouldn't really tell us which column is invalid, just that it is happening I think. Up to you if you want to add the log, I'm not totally sure its useful was just thinking out loud.

Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/segment/column/UnknownTypeComplexColumn.java:91]: Thinking more about it though, I do think we should log somewhere so the operator can know that an aggregator isn't loaded so a complex column can't be read. Maybe the `SimpleColumnHolder` would be more appropriate of a place?
