### PR TITLE
Remove incorrect utf8 conversion of ResultCache keys

### LINKED ISSUE #16552: Result level cache key collisions from utf8 encoding
The `ResultLevelCachingQueryRunner` does this when it computes the cache key for a query:

```
final String cacheKeyStr = StringUtils.fromUtf8(strategy.computeResultLevelCacheKey(query));
```

This is bad because not all byte arrays can be represented as Java Strings. For example, the byte arrays `[63, -48, 0, 0, 0, 0, 0, 0]` and `[63, -24, 0, 0, 0, 0, 0, 0]` have the same representation when converted to Strings. Both have an invalid second character, which both get mapped to the replacement character. These byte arrays are the representations of doubles `0.25` and `0.75` respectively, which is how this was originally noticed (two queries had a cache key collision when they differed only in that one used `0.25` and one used `0.75` as a quantile parameter).

To fix this we need to always use `byte[]`, never `String`, when dealing with cache keys.

### PR DESCRIPTION
**Pull request by kgyrtkirk**
* remove the incorrect call to read the byte[] as utf8
* not sure about its origin - but this will push the contract for `Cache` implementations to handle the `byte[]` in `NamedKey` - its already a `byte[]` - so they shouldn't expect any better than that...
* use `Cache.NamedKey` instead of passing `byte[]` and creating the key at multiple places
* added some test to ensure that cache implementations are able to accept such keys

Fixes #16552

### CODE REVIEW

File: server/src/main/java/org/apache/druid/client/CacheUtil.java [hunk 1]
```diff
@@ -34,6 +34,8 @@
 
 public class CacheUtil
 {
+  private static final String RESULT_CACHE_NS = "ResultCacheNS";
```
Comment (clintropolis) [inline server/src/main/java/org/apache/druid/client/CacheUtil.java:37]: nit: maybe make a version of `NamedKey` for result cache where the `nsBytes` is already computed so we don't have to call `StringUtils.toUtf8` on the constant everytime. Also could probably use a smaller string since the segment level cache uses segment identifiers for the namespace, so unlikely to have any collisions.

**Review by clintropolis — COMMENTED** [review]
lgtm :+1:

File: server/src/main/java/org/apache/druid/client/CacheUtil.java (hunk 1 above)
Comment (kgyrtkirk) [reply server/src/main/java/org/apache/druid/client/CacheUtil.java:37]: I've changed the resultcache namespace to `RES`

the `toUtf8` stuff is a bit more complicated:
* I wanted to push out the `String/byte[]` conversion from the `NamedKey` and change the namespace to use `byte[]`;
   * however: the `MapCache` directly accesses the [namespace](https://github.com/apache/druid/blob/fee509df2ebade0d6a17f96ee0637a27acedb45d/server/src/main/java/org/apache/druid/client/cache/MapCache.java#L86) field of the `NamedKey` class 
      *  since its being used as a key in a `Map` it must provide a valid `equals` - this could be addressed with a small refactor around there to use `ByteBuffer` 
   * the `namespace` also appears as an argument to [Cache#close](https://github.com/apache/druid/blob/fee509df2ebade0d6a17f96ee0637a27acedb45d/server/src/main/java/org/apache/druid/client/cache/Cache.java#L48) - so this will kinda force that to change as well
      *  this could force changes in the segment cache key generation stuff
   * ...so this path leads to refactor(s)
* I could store the `byte[]` next to the `String` by passing that as well in the constructor - but I would rather not do that unless there are measurable benefits of doing so
* status quo also have some pros: the  `toByteArray` is not used in all cache implementations  - so the `toUtf8` might not be even called 

I think for now it would be best to just leave this alone; not passing the full cachekey as the namespace have kinda reduced the key sizes to around half

Comment (clintropolis) [reply server/src/main/java/org/apache/druid/client/CacheUtil.java:37]: cool, re complicated stuff i guess i was imagining just subclassing it or something so parts could be constant, but if its complicated then seems fine to skip

**Review by clintropolis — APPROVED** [review]
