### PR TITLE
Fix an exception when using redis cluster as cache

### LINKED ISSUE #10753: Redis cluster connection error while trying to use as cache
`WARN [ForkJoinPool-1-worker-22] org.apache.druid.client.cache.AbstractRedisCache - Exception pushing item to cache
redis.clients.jedis.exceptions.JedisNoReachableClusterNodeException: No reachable node in cluster
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnection(JedisSlotBasedConnectionHandler.java:57) ~[jedis-2.9.0.jar:?]
        at redis.clients.jedis.JedisSlotBasedConnectionHandler.getConnectionFromSlot(JedisSlotBasedConnectionHandler.java:74) ~[jedis-2.9.0.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runWithRetries(JedisClusterCommand.java:116) ~[jedis-2.9.0.jar:?]
        at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:60) ~[jedis-2.9.0.jar:?]
        at redis.clients.jedis.BinaryJedisCluster.setex(BinaryJedisCluster.java:268) ~[jedis-2.9.0.jar:?]
        at org.apache.druid.client.cache.RedisClusterCache.putToRedis(RedisClusterCache.java:46) ~[druid-redis-cache-0.20.0.jar:0.20.0]
        at org.apache.druid.client.cache.AbstractRedisCache.put(AbstractRedisCache.java:84) [druid-redis-cache-0.20.0.jar:0.20.0]
        at org.apache.druid.client.cache.ForegroundCachePopulator$1.after(ForegroundCachePopulator.java:114) [druid-server-0.20.0.jar:0.20.0]
        at org.apache.druid.java.util.common.guava.WrappingYielder.close(WrappingYielder.java:98) [druid-core-0.20.0.jar:0.20.0]
        at org.apache.druid.java.util.common.guava.MergeSequence.makeYielder(MergeSequence.java:146) [druid-core-0.20.0.jar:0.20.0]
        at org.apache.druid.java.util.common.guava.MergeSequence.toYielder(MergeSequence.java:105) [druid-core-0.20.0.jar:0.20.0]
        at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$ResultBatch.fromSequence(ParallelMergeCombiningSequence.java:869) [druid-core-0.20.0.jar:0.20.0]
        at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$SequenceBatcher.block(ParallelMergeCombiningSequence.java:920) [druid-core-0.20.0.jar:0.20.0]
        at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3313) [?:1.8.0_121]
        at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$SequenceBatcher.getBatchYielder(ParallelMergeCombiningSequence.java:909) [druid-core-0.20.0.jar:0.20.0]
        at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$YielderBatchedResultsCursor.initialize(ParallelMergeCombiningSequence.java:1017) [druid-core-0.20.0.jar:0.20.0]
        at org.apache.druid.java.util.common.guava.ParallelMergeCombiningSequence$PrepareMergeCombineInputsAction.compute(ParallelMergeCombiningSequence.java:721) [druid-core-0.20.0.jar:0.20.0]
        at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189) [?:1.8.0_121]
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_121]
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_121]
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_121]
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_121]`

### PR DESCRIPTION
**Pull request by FrankChen021**
Fixes #10753

### Description

When using redis cluster as cache, there will be warning logs which print exception stack as below

```
2021-01-15T22:06:13,611 WARN [DruidSchema-Cache-0] org.apache.druid.client.cache.AbstractRedisCache - Exception pulling items from cache
redis.clients.jedis.exceptions.JedisClusterException: No way to dispatch this command to Redis Cluster because keys have different slots.
	at redis.clients.jedis.JedisClusterCommand.runBinary(JedisClusterCommand.java:75) ~[?:?]
	at redis.clients.jedis.BinaryJedisCluster.mget(BinaryJedisCluster.java:1362) ~[?:?]
	at org.apache.druid.client.cache.RedisClusterCache.mgetFromRedis(RedisClusterCache.java:52) ~[?:?]
	at org.apache.druid.client.cache.AbstractRedisCache.getBulk(AbstractRedisCache.java:102) ~[?:?]
	at org.apache.druid.client.CachingClusteredClient$SpecificQueryRunnable.computeCachedValues(CachingClusteredClient.java:586) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.client.CachingClusteredClient$SpecificQueryRunnable.pruneSegmentsWithCachedResults(CachingClusteredClient.java:546) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.client.CachingClusteredClient$SpecificQueryRunnable.run(CachingClusteredClient.java:359) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.client.CachingClusteredClient.run(CachingClusteredClient.java:196) ~[druid-server-0.20.0.jar:0.20.0]
	at org.apache.druid.client.CachingClusteredClient.access$100(CachingClusteredClient.java:111) ~[druid-server-0.20.0.jar:0.20.0]
```

This exception occurs when querying a data source containing multiple segments. The exception comes out because Jedis, current redis driver used by `redis-cache` extension, DOES NOT support MGET operation among different redis nodes. This is NOT a constraint of redis cluster, but an implementation limit imposed by Jedis.

This PR simply implements a widely used workaround: grouping keys by pre-calculated redis slot to ensure keys in one group maps to a same redis node , and then MGET keys one group by group. 

A better way is to use Lettuce driver to replace Jedis, MGET on redis cluster is supported natively by Lettuce. But since this is a community extension, I don't think it's worthy of refactoring this extension from its core right now.

### Key changed/added classes in this PR
- Implementation of `AbstractRedisCache#getBulk` is pushed down to `RedisClusterCache#mgetFromRedis` and `RedisStandaloneCache#mgetFromRedis`.

- In `RedisClusterCache#mgetFromRedis`, it first groups keys by their slots and then executes MGET command one group by group.

<hr>

This PR has:
- [X] been self-reviewed.
   - [X] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [X] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [X] been tested in a test Druid cluster.

### CODE REVIEW

File: extensions-contrib/redis-cache/src/main/java/org/apache/druid/client/cache/AbstractRedisCache.java [hunk 1]
```diff
@@ -93,21 +91,12 @@ public void put(NamedKey key, byte[] value)
...
-      for (int i = 0; i < byteValues.size(); ++i) {
-        if (byteValues.get(i) != null) {
-          results.put(namedKeys.get(i), byteValues.get(i));
-        }
-      }
+      Map<NamedKey, byte[]> results = this.mgetFromRedis(keys);
 
       hitCount.addAndGet(results.size());
-      missCount.addAndGet(namedKeys.size() - results.size());
+      missCount.addAndGet(Stream.of(keys).count() - results.size());
```
Comment (clintropolis) [inline extensions-contrib/redis-cache/src/main/java/org/apache/druid/client/cache/AbstractRedisCache.java:98]: nit: it seems like we could potentially precompute the number of keys in `mgetFromRedis` when it iterates them, returning some composite type that contains the count instead of returning `Map<NamedKey, byte[]>` directly.

Not sure if there are enough keys to make this worth doing or not

**Review by clintropolis — APPROVED** [review]
sorry for the delay, had to do some reading to understand this change; if i understand correctly, it seems that the 'bulk' commands only operate on keys that belong to a single node, so this breaks it up to issue multiple bulk commands grouping by which node the keys belong to, which i think makes sense.

:+1:

**Review by clintropolis — APPROVED** [review]
