### PR TITLE
Fix regression introduced by #11008

### LINKED ISSUE #11012: Fix regression introduced by #11008
#11008 incorrectly got rid of the need to examine all the resources when the `AllowAllAuthorizer` is configured. The loop is still needed to de-dupe the entries.

### PR DESCRIPTION
**Pull request by samarthjain**
Fixes #11012 .

This PR has:
- [X ] been self-reviewed.
   - [X ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [X] been tested in a test Druid cluster.

### CODE REVIEW

File: server/src/main/java/org/apache/druid/server/security/AuthorizationUtils.java [hunk 1]
```diff
@@ -263,10 +263,6 @@ public static Access authorizeAllResourceActions(
       throw new ISE("No authorizer found with name: [%s].", authenticationResult.getAuthorizerName());
     }
 
-    if (authorizer instanceof AllowAllAuthorizer) {
-      return resources;
-    }
-
```
Comment (suneet-s) [inline server/src/main/java/org/apache/druid/server/security/AuthorizationUtils.java:269]: Could we add a test to prevent someone accidentally making this addition in the future. I read the previous patch and thought this was a good optimization too.

Comment (samarthjain) [reply server/src/main/java/org/apache/druid/server/security/AuthorizationUtils.java:269]: Good call, @suneet-s . I added a unit test in the new commit and in the process  I found that we can still skip authorizing the resources when AllowAllAuthorizer is configured.

**Review by suneet-s — APPROVED** [review]
Nice! LGTM

Maybe we should wait for @abhishekagarwal87 to take a look too, since he spotted the regression in the previous patch.

**Review by abhishekagarwal87 — APPROVED** [review]

**Comment by abhishekagarwal87** [comment]
LGTM
