### PR TITLE
Handle intermediate change of status in pause method

### LINKED ISSUE #17722: Task Fails on pause request due to intermediate change in task status
### Description

* After upgrading to Druid-30, One task is occasionally failing per day.
* Task fails with the following exception:
```
Can't pause, task is not in a pausable state (state: [PAUSED])
```
* Logs were added to debug the issue: https://github.com/confluentinc/druid/pull/304
* Logs when the task failed:
```
Feb 12, 2025 @ 15:21:08.165	Pausing the task with state: [READING]

Feb 12, 2025 @ 15:21:08.165	Returning 409 conflict for task with state: [PAUSED]
```
* As per the above logs, `status` is changing during the evaluation of the `if` statement.

### PR DESCRIPTION
**Pull request by suraj-goel**
Fixes #17722.

#### Fixed the bug 

* After upgrading to Druid-30, One task is occasionally failing per day.
* Task fails with the following exception:
```
Can't pause, task is not in a pausable state (state: [PAUSED])
```
* Logs were added to debug the issue: https://github.com/confluentinc/druid/pull/304
* Logs when the task failed:
```
Feb 12, 2025 @ 15:21:08.165	Pausing the task with state: [READING]

Feb 12, 2025 @ 15:21:08.165	Returning 409 conflict for task with state: [PAUSED]
```
* As per the above logs, `status` is changing during the evaluation of the `if` statement.

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `SeekableStreamIndexTaskRunner.java`

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java [hunk 1]
```diff
@@ -1887,10 +1887,12 @@ public Response pauseHTTP(
   @VisibleForTesting
   public Response pause() throws InterruptedException
   {
-    if (!(status == Status.PAUSED || status == Status.READING)) {
+    Status currentStatus = status;
+    if (!(currentStatus == Status.PAUSED || currentStatus == Status.READING)) {
```
Comment (kfaraz) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1891]: I am not sure but it feels that this will only end up suppressing the real root cause here.

The problem is that once we have entered this `if` block, the status actually changes to `PAUSED`.
But why did that change happen? Either `pause()` had already been called or something else happened that caused the runner thread to pause the task.

The `volatile` business is making things complicated. We should perhaps consider adding some locking around the `status` field.

**Review by kfaraz — COMMENTED** [review]
Thanks for the PR, @suraj-goel !
I have left some thoughts. Let me know what you think.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java (hunk 1 above)
Comment (suraj-goel) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1891]: The root cause lies in [possiblyPause](https://github.com/apache/druid/blob/e200eee1012e7f222afe9809993588e97872a1bb/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java#L1372) method.
In this method `status` field is synchronized using `pauseLock`.

The same lock is used in `pause` method as well but after the `if` condition. 
I can move the pauseLock before the `if` statement so that status field remains atomic between these 2 methods.

Let me know your thoughts. I can test it in a Druid cluster if this sounds good to you.

Comment (suraj-goel) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java]: @kfaraz , I have updated the code and tested the changes in a dev cluster.
If the change looks good to you, I will test in the same cluster where the tasks were failing.
P.S. With the previous commit, there are not issues related to task failures anymore.

Comment (kfaraz) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java]: Hmm. @suraj-goel , I don't think the latest change will help either since the `status` may still be changed by a thread that has not even acquired the `pauseLock`. Apparently, changing the `status` requires the `statusLock` and I am not sure if it would be wise to acquire both `statusLock` and `pauseLock` together in the `pause()` method.

`SeekableStreamIndexTaskRunner` seems to be in need of a serious overhaul as there are far too many locks and conditions floating around. I don't want to make hasty changes that make things even more complicated.

Comment (kfaraz) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java]: > P.S. With the previous commit, there are not issues related to task failures anymore.

Do you mean the change where you had copied over the value of `status` into `currentStatus`?

Comment (suraj-goel) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java]: > SeekableStreamIndexTaskRunner seems to be in need of a serious overhaul as there are far too many locks and conditions floating around

Agree @kfaraz !

IMO, This solution should work because in this particular case, the race condition is between threads running `possiblyPause` and `pause` methods.

> Do you mean the change where you had copied over the value of status into currentStatus?

Yes! No issues related to this bug from the past 2 days.


Assigning to local variable seems to be a safe and non breaking solution for this bug. We can refactor this class separately to use the locks in the right way.

Comment (kfaraz) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java]: > Yes! No issues related to this bug from the past 2 days.
> Assigning to local variable seems to be a safe and non breaking solution for this bug. We can refactor this class separately to use the locks in the right way.

Okay, in that case, please revert to that commit, because it can definitely not break anything else.
We will deal with the lock stuff separately.

Comment (suraj-goel) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1891]: @kfaraz Done!

Comment (kfaraz) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1891]: Thanks, @suraj-goel !
Would it be possible for you to test out this change on the cluster where you saw the task pause failures?

Also, I think there is another thing we can do for cleaner handling.
We should just put this entire `if` block inside the `statusLock`. What do you think?

Comment (suraj-goel) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1891]: @kfaraz,

> Would it be possible for you to test out this change on the cluster where you saw the task pause failures?

There has been no failures in the cluster since this patch is deployed. It's been 3 days since the deployment.

> We should just put this entire if block inside the statusLock. What do you think?

This won't help. As mentioned before, `possiblyPause`  method will still be able to change the status as it doesn't have any usage of `statusLock`.
We can use the `pauseLock` in `pause` method (previous commit) or add a `statusLock` in `possiblyPause` method.


Right now, I think the current commit seems to be the safest way to resolve this bug.

Comment (kfaraz) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1891]: > There has been no failures in the cluster since this patch is deployed. It's been 3 days since the deployment.

Great!

> This won't help. As mentioned before, possiblyPause method will still be able to change the status as it doesn't have any usage of statusLock.

Ah, right.

Let's just proceed with this commit then.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java [hunk 2]
```diff
@@ -1887,10 +1887,12 @@ public Response pauseHTTP(
   @VisibleForTesting
   public Response pause() throws InterruptedException
   {
-    if (!(status == Status.PAUSED || status == Status.READING)) {
+    Status currentStatus = status;
```
Comment (kfaraz) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1890]:
```suggestion
    // Read the volatile status into a variable so that its value does not change while the condition is evaluated
    final Status currentStatus = status;
```

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java [hunk 3]
```diff
@@ -1887,10 +1887,12 @@ public Response pauseHTTP(
...
+    if (!(currentStatus == Status.PAUSED || currentStatus == Status.READING)) {
+      log.debug("Returning 409 conflict for task [%s] with currentState: [%s], volatileState: [%s]", task.getId(), currentStatus, status);
       return Response.status(Response.Status.CONFLICT)
                      .type(MediaType.TEXT_PLAIN)
-                     .entity(StringUtils.format("Can't pause, task is not in a pausable state (state: [%s])", status))
+                     .entity(StringUtils.format("Can't pause, task is not in a pausable state (currentState: [%s], volatileState: [%s])", currentStatus, status))
```
Comment (kfaraz) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1895]: Simplified the error message a bit.
We need not include the volatile status in the error message as it is not used in the if block.
```suggestion
                     .entity(StringUtils.format("Cannot pause task as it is currently in state[%s]", currentStatus))
```

**Review by kfaraz — COMMENTED** [review]
Changes look good to me.
Left some minor suggestions.

**Comment by suraj-goel** [comment]
> Changes look good to me. Left some minor suggestions.

@kfaraz , I have addressed the comments.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java [hunk 4]
```diff
@@ -1887,10 +1887,13 @@ public Response pauseHTTP(
   @VisibleForTesting
   public Response pause() throws InterruptedException
   {
-    if (!(status == Status.PAUSED || status == Status.READING)) {
+    // Read the volatile status into a variable so that its value does not change while the condition is evaluated
+    final Status currentStatus = status;
+    if (!(currentStatus == Status.PAUSED || currentStatus == Status.READING)) {
+      log.error("Cannot pause task: [%s] as it is currently in state: [%s]", task.getId(), currentStatus);
```
Comment (kfaraz) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1893]: Updated the log to match Druid style
```suggestion
      log.error("Cannot pause task[%s] as it is currently in state[%s]", task.getId(), currentStatus);
```

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java [hunk 5]
```diff
@@ -1887,10 +1887,13 @@ public Response pauseHTTP(
...
       return Response.status(Response.Status.CONFLICT)
                      .type(MediaType.TEXT_PLAIN)
-                     .entity(StringUtils.format("Can't pause, task is not in a pausable state (state: [%s])", status))
+                     .entity(StringUtils.format("Cannot pause task as it is currently in state: [%s]", currentStatus))
```
Comment (kfaraz) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1896]: Updated the message to match Druid interpolation style
```suggestion
                     .entity(StringUtils.format("Cannot pause task as it is currently in state[%s]", currentStatus))
```

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java [hunk 6]
```diff
@@ -1887,10 +1887,13 @@ public Response pauseHTTP(
   @VisibleForTesting
   public Response pause() throws InterruptedException
   {
-    if (!(status == Status.PAUSED || status == Status.READING)) {
+    // Read the volatile status into a variable so that its value does not change while the condition is evaluated
+    final Status currentStatus = status;
+    if (!(currentStatus == Status.PAUSED || currentStatus == Status.READING)) {
```
Comment (cryptoe) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1892]: TBH: 1890 does not add a lot of value :). 

I think the valid state transitions should reside int the status class. That way we have one central way of controlling the transitions instead of having the logic spread all over the place. 

Can be a follow up PR as well .

**Review by cryptoe — APPROVED** [review]

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java (hunk 6 above)
Comment (kfaraz) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1892]: Yeah, we need to revisit this class in earnest.

Comment (kfaraz) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java:1892]: > TBH: 1890 does not add a lot of value

Do you mean the comment?

**Review by kfaraz — APPROVED** [review]
