### PR TITLE
Fix RejectExecutionHandler of Blocking Single Threaded executor

### LINKED ISSUE #16783: Druid indexer tasks gets stuck in PUBLISHING state
Druid indexer tasks sometimes get stuck in PUBLISHING state, due to executors are not shut down properly.

### Affected Version

Druid 25.0.0

### Description
We are running Kafka supervisor ingestion task, with task replication as two. 
- Task [A1, A2] are replica tasks of same TaskGroup. After task rollover happens, it creates new set of tasks[B1, B2] to start ingesting, and TaskGroup [A1, A2] is added to pending completion task group.
- Task A1 was completed with a SUCESS and it send stop signal to both A1, A2. Async Stop request is send to task A2, which returns 200, and indexer start stopping the task Gracefully. But task A2 got forever stuck in PUBLISHING state on indexer.
- Overlord detects A2 active task, which is neither in ActivelyReadingTaskGroup nor PendingCompletionTaskGroup. So It creates a NEW PendingCompletionTaskGroup with only A2 Task.
- Task A2 was stuck in PUBLISHING state on indexer. After a timeout period of `PendingCompletionTimeout` minutes, this task is forcefully killed. Since overlord sees Task group completion timeout is passed, and task is not sucess. So it **KILLS ACTIVELY READING TASKS.** 

### Why Task A2 got stuck in PUBLISHING state? 
I did some debugging which is the probable cause of task getting stuck.
- When Task A2 got a Stop signal, the main thread was interrupted Immediately. A2 task was handing off the segments at the time and had completed publishing.
- From logs, we can Indexer was handing off 3 segments. But it sends the Dropped segment log for only one segment.
```
2 Jul 2024 @ 03:05:55.583 UTC	Segment[S0] successfully handed off, dropping.	indexer-pod	coordinator_handoff_scheduled_0
2 Jul 2024 @ 03:05:55.585 UTC	Segment[S1] successfully handed off, dropping.	indexer-pod	coordinator_handoff_scheduled_0
2 Jul 2024 @ 03:05:55.587 UTC	Segment[S2] successfully handed off, dropping.	indexer-pod	coordinator_handoff_scheduled_0
2 Jul 2024 @ 03:05:56.223 UTC	Stopping gracefully (status: [PUBLISHING])	indexer-pod	thread
2 Jul 2024 @ 03:05:56.223 UTC	Closing reporter org.apache.kafka.common.metrics.JmxReporter	indexer-pod	[task_id]-threading-task-runner-executor-0

2 Jul 2024 @ 03:05:56.224 UTC	Shutting down immediately...	indexer-pod main thread
2 Jul 2024 @ 03:05:56.258 UTC	Dropped segment[S0].	indexer-pod	[task_id]-appenderator-persist

```
- ~The task seem to get stuck, waiting for the persist executor to shut down. As we can see, last log line the main thread printed was `Shutting down immediately...` . After that we [shut down executors](https://github.com/apache/druid/blob/master/server/src/main/java/org/apache/druid/segment/realtime/appenderator/StreamAppenderator.java#L1081) and wait for the them to shut down, **with a timeout of 365 Days**~
**EDIT**: From thread dumps added below, the executor which is not able to terminate is `intermediateTempExecutor`
```
Preconditions.checkState(
          persistExecutor == null || persistExecutor.awaitTermination(365, TimeUnit.DAYS),
          "persistExecutor not terminated"
      );
```
- After `PendingCompletionTimeout` minutes, this task is forcefully killed and marked as FAILED. And is stopped again, which again interrupts the main ingestion thread. We get this ERROR log line
```
2 Jul 2024 @ 03:40:01.670 UTC	Exception caught during execution	indexer-pod	threading-task-runner-executor-0
  	java.lang.RuntimeException: org.apache.druid.java.util.common.RE: Current thread is interrupted after [0] tries
	at org.apache.druid.storage.s3.S3TaskLogs.pushTaskFile(S3TaskLogs.java:156)
	at org.apache.druid.storage.s3.S3TaskLogs.pushTaskReports(S3TaskLogs.java:141)
	at org.apache.druid.indexing.overlord.ThreadingTaskRunner$1.call(ThreadingTaskRunner.java:223)
	at org.apache.druid.indexing.overlord.ThreadingTaskRunner$1.call(ThreadingTaskRunner.java:152)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: org.apache.druid.java.util.common.RE: Current thread is interrupted after [0] tries
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:148)
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:81)
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:163)
	at org.apache.druid.java.util.common.RetryUtils.retry(RetryUtils.java:153)
	at org.apache.druid.storage.s3.S3Utils.retryS3Operation(S3Utils.java:101)
	at org.apache.druid.storage.s3.S3TaskLogs.pushTaskFile(S3TaskLogs.java:147)
	... 7 more
```
After this exception, the main thread to go to [finally](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java#L910) { [thread] block and remove chat handlers and stopping other task tools.

### PR DESCRIPTION
**Pull request by hardikbajaj**
Fixes #16783.

### Description

As discussed in issue https://github.com/apache/druid/issues/16783 ,  there are times when intermediateTempExecutor thread get stuck in `WAITING` state and the executor is not able to terminate. This causes the main task to get stuck in `PUBLISHING` state forever, until we kill it or pendingCompletionTimeout interrupts the thread.

The underlying cause of this issue is that this intermediateTempExecutor is implemented using newBlockingSingleThreaded, which created a thread pool executor with maxCoreSize: 1 and a [SynchronousQueue](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/SynchronousQueue.html). 
The `rejectedExecutionHandler` of this ThreadExecutor should not add tasks when it's in shutDown state because, a SynchronousQueue is used and if a task is `put()` in it in ShutDown state, it will forever stuck in WAITING state as executor will not `take()` the task to schedule it. In a `SynchronousQueue` there should always be a `take()` WAITING for every `put()` operation and vice-versa. 

In the [issue](https://github.com/apache/druid/issues/16783), I have added thread dumps too that confirm tasks being stuck during `rejectedExecution()` when task is added in queue during a shutDown state. The Unit test confirms the thread getting stuck. 
In `StreamAppenderator`, it happens when  there is a race condition [here](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java#L879-L883)
```
        Futures.allAsList(publishWaitList).cancel(true);
        Futures.allAsList(handOffWaitList).cancel(true);
        if (appenderator != null) {
          appenderator.closeNow();
        }
```
We don't wait for appenderator.drop() to be interrupted in handOffWaitList and appenderator.closeNow() shuts down the exeuctors. Thus a new task is sometimes added in intermediateTempExecutor through appenderator.drop() while executor is already shutDown.

#### Fixed the bug ...
https://github.com/apache/druid/issues/16783
#### Release note

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java [hunk 1]
```diff
@@ -118,6 +122,38 @@ public void run()
...
+    // as executor will not take() the task to schedule it.
+    final ListeningExecutorService intermediateTempExecutor = MoreExecutors.listeningDecorator(
+        Execs.newBlockingSingleThreaded("[TASK_ID]-appenderator-abandon", 0)
+    );
+    Callable<Void> task = () -> {
+      try {
+        Thread.sleep(1000); // Simulate long-running task
+      }
+      catch (InterruptedException e) {
+        Thread.sleep(1500);
```
Comment (ravisharm) [inline processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:139]: why do we need sleep() under catch?

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java [hunk 2]
```diff
@@ -118,6 +122,38 @@ public void run()
...
+    // Submit multiple tasks together
+    intermediateTempExecutor.submit(task);
+    intermediateTempExecutor.submit(task);
+    intermediateTempExecutor.submit(task);
+
+    intermediateTempExecutor.shutdownNow();
+    // Submit task after shutDown / shutDownNow should not be added in queue
+    intermediateTempExecutor.submit(task);
+    intermediateTempExecutor.awaitTermination(10, TimeUnit.SECONDS);
+    Assert.assertTrue(intermediateTempExecutor.isShutdown());
```
Comment (ravisharm) [inline processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:154]: if you remove the fix to the product code and run this test, does line 152 get stuck forever?

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 1 above)
Comment (ravisharm) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:139]: If we remove catch (InterruptedException e) do we lose anything?

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 2 above)
Comment (hardikbajaj) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:154]: Yes

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 1 above)
Comment (hardikbajaj) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:139]: Yes, even if we remove this, even then the thread get stuck as the main problem is Task being added to the queue, without it being taken to execute. I did this to simulate RUNNING thread still being blocked at the time of adding another task being added. But it is not required

**Review by cryptoe — APPROVED** [review]

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java [hunk 3]
```diff
@@ -118,6 +123,37 @@ public void run()
...
+        Thread.sleep(500); // Simulate long-running task
+      }
+      catch (InterruptedException e) {
+        Thread.currentThread().interrupt(); // Restore interrupted status
+      }
+      return null;
+    };
+
+    // Submit multiple tasks together
+    ListenableFuture<Void> unused = intermediateTempExecutor.submit(task);
```
Comment (kfaraz) [inline processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:146]: If you don't plan to use the return value, you need not assign it to anything. Having a variable named `unused` is confusing.

File: processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java [hunk 4]
```diff
@@ -159,6 +162,10 @@ public static ExecutorService newBlockingThreaded(
           @Override
           public void rejectedExecution(Runnable r, ThreadPoolExecutor executor)
           {
+            if (executor.isShutdown()) {
+              log.debug("Executor is shutdown, rejecting task");
```
Comment (kfaraz) [inline processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java:166]: Is this really needed?

File: processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java [hunk 5]
```diff
@@ -159,6 +162,10 @@ public static ExecutorService newBlockingThreaded(
...
+              return;
```
Comment (kfaraz) [inline processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java:167]: Since this is an unexpected scenario i.e. submitting a task after shutdown, it would be better to throw an exception rather than return silently.

Maybe just do `throw new RejectedExecutionException("Executor has already been shutdown");`

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java [hunk 6]
```diff
@@ -118,6 +123,37 @@ public void run()
     producer.shutdown();
   }
 
+  @Test
+  public void testSynchronousQueueSingleThreadedExecutor() throws Exception
```
Comment (kfaraz) [inline processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:127]: What does this test verify?

**Review by kfaraz — CHANGES_REQUESTED** [review]

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 3 above)
Comment (hardikbajaj) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:146]: I did it like this. Got these errors on tests
```
Error:  COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
Error:  /home/runner/work/druid/druid/processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:[146,35] error: [CheckReturnValue] The result of `submit(...)` must be used
  If you really don't want to use the result, then assign it to a variable: `var unused = ...`.
  
  If callers of `submit(...)` shouldn't be required to use its result, then annotate it with `@CanIgnoreReturnValue`.
  
    (see https://errorprone.info/bugpattern/CheckReturnValue)
  Did you mean 'var unused = intermediateTempExecutor.submit(task);' or to remove this line?
Error:  /home/runner/work/druid/druid/processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:[147,35] error: [CheckReturnValue] The result of `submit(...)` must be used
```
Any idea how can I fix this?

File: processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java (hunk 5 above)
Comment (hardikbajaj) [reply processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java:167]: I can do that, will it be a safe operation? I was worried it don't give unusual errors on a process like ingestion task, that is supposed to succeed

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 6 above)
Comment (hardikbajaj) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:127]: This test verifies, that if after `shutDownNow()` is called on executor service, a task is submitted. It will not stop the executor service from shutting down. If we remove the fix in Execs, this will get STUCK in waiting state. 
I can improve this test if wanted

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 3 above)
Comment (kfaraz) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:146]: You could perform an assertion on the return value, like it is non null and the future is not complete yet.

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 6 above)
Comment (kfaraz) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:127]: No, the test should be fine. Maybe try to update the test name to reflect what it verifies.

File: processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java (hunk 5 above)
Comment (kfaraz) [reply processing/src/main/java/org/apache/druid/java/util/common/concurrent/Execs.java:167]: If the executor has been shut down, no more tasks should be submitted to it.
If we were throwing an exception, the case that you are trying to solve (executor stuck in WAITING) would have been caught sooner.

Please do some cluster testing after making the changes.

**Comment by hardikbajaj** [comment]
@kfaraz . Thanks for the review. I've addressed all your comments

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java [hunk 7]
```diff
@@ -118,6 +122,36 @@ public void run()
     producer.shutdown();
   }
 
+  @Test
+  public void testTaskAddedToShutDownSynchronousQueueSingleThreadedExecutor() throws Exception
```
Comment (kfaraz) [inline processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java:126]: Nit: 
```suggestion
  public void testTaskAddedToShutdownExecutorThrowsException() throws Exception
```

**Review by kfaraz — APPROVED** [review]

File: processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java (hunk 7 above)
Comment (hardikbajaj) [reply processing/src/test/java/org/apache/druid/concurrent/ExecsTest.java]: Fixed

**Comment by hardikbajaj** [comment]
Hey @kfaraz, 1 compaction-integration test and 1 perfect-rollup-parallel-batch-index integration test failing with same error.
Are the changes related? Looks like a flaky test to me. Can we re-run these two checks?

```
org.apache.druid.java.util.common.ISE: Error while making request to indexer [404 Not Found No task reports were found for this task. The task may not exist, or it may not have completed yet.]
	at org.apache.druid.tests.coordinator.duty.ITAutoCompactionTest.testAutoCompactionDutyCanUpdateCompactionConfig(ITAutoCompactionTest.java:716)
```

```
org.apache.druid.java.util.common.ISE: Error while making request to indexer [404 Not Found No task reports were found for this task. The task may not exist, or it may not have completed yet.]
	at org.apache.druid.tests.indexer.ITPerfectRollupParallelIndexTest.testIndexData(ITPerfectRollupParallelIndexTest.java:127)
```

**Comment by hardikbajaj** [comment]
@kfaraz Thanks! Can we merge this now?
