### PR TITLE
Fix expression result writing of arrays in Hadoop Ingestion

### LINKED ISSUE #15100: Strange for the results of executing the index_hadoop task with transformSpec including expression for "array dimension"
### Affected Version

Druid 26.0.0
not affected at version 0.21.0, but problem founded at version 26.0.0

### Description

- Cluster size
  - about 100 hosts
- Configurations in use
  - not related to configuration
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
  - There aren't error message

- Steps to reproduce the problem & Any debugging that you have already done

I tested inline, kafka indexing, and index_hadoop, but only index_hadoop had problems.
#### Example dataset below
```json
{"timestamp": 1696470307397, "dim": ["n", "b", "q", "b"]}
{"timestamp": 1696470307398, "dim": ["a", "w"]}
{"timestamp": 1696470307398, "dim": ["d", "m", "a", "o", "e", "i", "c", "d"]}
{"timestamp": 1696470307399, "dim": ["q", "i", "a", "p", "a", "o"]}
...
```
#### transformSpec
```json
"transformSpec": {
  "transforms": [
    {
      "type": "expression",
      "name": "dim",
      "expression": "if(array_length(dim) <= 5, dim, array_slice(dim, 0, 5))"
    }
  ]
}
```
#### Result (26.0.0)
스크린샷 2023-10-06 오전 11 43 53  

I guess it has something to do with this PR (https://github.com/apache/druid/pull/13947)
```java
@Test
public void testTransformWithExpr()
{
  final Transformer transformer = new Transformer(
      new TransformSpec(
          null,
          ImmutableList.of(new ExpressionTransform("dim", "array_slice(dim, 0, 5)", TestExprMacroTable.INSTANCE))
      )
  );
  final InputRow row = new MapBasedInputRow(
      DateTimes.nowUtc(),
      ImmutableList.of("dim"),
      ImmutableMap.of("dim", ImmutableList.of("a", "b", "c", "d", "e", "f", "g"))
  );
  System.out.println(row.getDimension("dim"));
  System.out.println(row.getRaw("dim"));

  final InputRow actual = transformer.transform(row);
  System.out.println(actual.getDimension("dim"));
  System.out.println(actual.getRaw("dim"));
}
```
```
// 26.0.0

[a, b, c, d, e, f, g]
[a, b, c, d, e, f, g]
[a, b, c, d, e]
[Ljava.lang.Object;@147a5d08 <-- here
```
```
// 0.21.0

[a, b, c, d, e, f, g]
[a, b, c, d, e, f, g]
[a, b, c, d, e]
[a, b, c, d, e]
```

### PR DESCRIPTION
**Pull request by pranavbhole**
Fixes #15100.

### Description
This PR fixes the bug in Hadoop ingestion which writes arrays as objects.toString as result of transform expressions. Found the case that we were not handing the expression results correctly when we get result as Array from array_slice expression. 

Also found another bug while testing this that Complex /json column ingestion does not work with index_hadoop. 

 ```
       "transforms": [
          {
            "type": "expression",
            "name": "dimT",
            "expression": "array_slice(dim2, 0, 2)"
          }
        ]
```

Screenshot 2023-10-12 at 1 54 25 PM

verified the change with local hadoop ingestion, 
Fixed: 
Screenshot 2023-10-12 at 1 57 45 PM

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [x] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/data/input/Rows.java [hunk 1]
```diff
@@ -70,6 +71,8 @@ public static List<String> objectToStrings(final Object inputValue)
     } else if (inputValue instanceof byte[]) {
       // convert byte[] to base64 encoded string
       return Collections.singletonList(StringUtils.encodeBase64String((byte[]) inputValue));
+    } else if (inputValue instanceof Object[]) {
+      return Arrays.stream((Object[]) inputValue).map(String::valueOf).collect(Collectors.toList());
```
Comment (clintropolis) [inline processing/src/main/java/org/apache/druid/data/input/Rows.java:75]: use `Evals::asString` instead of `String::valueOf` since the latter will translate `null` into `"null"` which isn't cool

File: processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java [hunk 2]
```diff
@@ -100,7 +100,11 @@ static class ExpressionRowFunction implements RowFunction
     public Object eval(final Row row)
     {
       try {
-        return expr.eval(InputBindings.forRow(row)).valueOrDefault();
+        Object result = expr.eval(InputBindings.forRow(row)).valueOrDefault();
+        if (result != null && result.getClass().isArray()) {
+          return Rows.objectToStrings(result);
+        }
+        return result;
```
Comment (clintropolis) [inline processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java:107]: this should not change, we want ARRAY functions to output arrays, the proper place to change is  https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java#L115 which no longer needs to call `ExpressionSelectors.coerceEvalToObjectOrList`

Comment (pranavbhole) [reply processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java]: we dont really need this change. Removed it.

File: processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java [hunk 3]
```diff
@@ -385,7 +389,7 @@ public void testTransformWithArrayLongInputs()
     Assert.assertNotNull(actual);
     Assert.assertEquals(ImmutableList.of("dim"), actual.getDimensions());
     Assert.assertArrayEquals(new Object[]{1L, 2L, null, 3L}, (Object[]) actual.getRaw("dim"));
-    Assert.assertEquals(Arrays.asList("1", "2", "null", "3"), actual.getDimension("dim"));
+    Assert.assertArrayEquals(new String[]{"1", "2", null, "3"}, actual.getDimension("dim").toArray());
```
Comment (clintropolis) [inline processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java:392]: nit: any reason to convert to array? I think `Arrays.asList` works with nulls, it was probably a bug earlier that this was being converting `null` to `"null"`

**Review by clintropolis — APPROVED** [review]
:+1:

File: processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java (hunk 3 above)
Comment (pranavbhole) [reply processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java:392]: assertEquals found it as other reference of ArrayList and failed with assertion 
```
java.lang.AssertionError: expected: java.util.Arrays$ArrayList<[1.2000000476837158, 2.299999952316284, null, 3.4000000953674316]> but was: java.util.ArrayList<[1.2000000476837158, 2.299999952316284, null, 3.4000000953674316]>
Expected :java.util.Arrays$ArrayList<[1.2000000476837158, 2.299999952316284, null, 3.4000000953674316]>
Actual   :java.util.ArrayList<[1.2000000476837158, 2.299999952316284, null, 3.4000000953674316]>
```

**Comment by pranavbhole** [comment]
rebased with master to fix unrelated MSQ test

File: processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java [hunk 4]
```diff
@@ -441,7 +445,74 @@ public void testTransformWithArrayDoubleInputs()
...
+    );
+    final List<String> dimList = ImmutableList.of("a", "b", "c", "d", "e", "f", "g");
+    final MapBasedRow row = new MapBasedRow(
+        DateTimes.nowUtc(),
+        ImmutableMap.of("dim", dimList)
+    );
+    Assert.assertEquals(row.getDimension("dim"), dimList);
+    Assert.assertEquals(row.getRaw("dim"), dimList);
+
+    final InputRow actualTranformedRow = transformer.transform(new InputRow()
```
Comment (kgyrtkirk) [inline processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java:469]: I wonder if its necessary to use an inline `new InputRow()` here - do you need to retain the `row` in that type for some reason ?

you could make public/move outside/etc [this metod](https://github.com/apache/druid/blob/f0a70fe3c4533c889b6185774f104c0265a0c37e/indexing-hadoop/src/main/java/org/apache/druid/indexer/IndexGeneratorJob.java#L494)

...or probably try to use [MapBasedInputRow](https://github.com/apache/druid/blob/f0a70fe3c4533c889b6185774f104c0265a0c37e/processing/src/main/java/org/apache/druid/data/input/MapBasedInputRow.java#L38) ?

File: processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java [hunk 5]
```diff
@@ -111,9 +110,7 @@ public Object eval(final Row row)
     public List<String> evalDimension(Row row)
     {
       try {
-        return Rows.objectToStrings(
```
Comment (kgyrtkirk) [inline processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java:114]: note: removal of `coerceEvalToObjectOrList` will have a sideeffect that it will not anymore turn `[singleVal]` into just `singleVal` - I don't know if that's important or not - but I wonder how `array_slice(dim, 0, 1)` is handled before/after the patch; might worth a quick check

Comment (pranavbhole) [reply processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java:114]: it is handled correctly in the serializer/deserializer.  Also added test to make sure that we are getting array with 1 value from transform in the single value case.

File: processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java (hunk 4 above)
Comment (pranavbhole) [reply processing/src/test/java/org/apache/druid/segment/transform/TransformerTest.java:472]: yeah, I wanted to use the same flow that is being used in Hadoop indexer, thus created a inline InputRow in this test.

File: processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java (hunk 5 above)
Comment (clintropolis) [reply processing/src/main/java/org/apache/druid/segment/transform/ExpressionTransform.java:114]: yea, this change is ok in this case because `Rows.objectToStrings` is translating anything into `List<String>`, this method was just previously re-using the method used by the expression dimension selector on the query side to which itself matches https://github.com/apache/druid/blob/master/processing/src/main/java/org/apache/druid/segment/DimensionSelector.java#L141, but since in this transform it was wrapped in Rows.objectToStrings, that part of the behavior wasn't important, just the converting an array to a list of strings part.

**Review by clintropolis — APPROVED** [review]
