### PR TITLE
Addressing 2 Coordinators Elected As Leader (#16411)

### LINKED ISSUE #16411: 2 Coordinators Elected Leader
Please provide a detailed title (e.g. "Broker crashes when using TopN query with Bound filter" instead of just "Broker crashes").

### Affected Version

28.0.1 (also observed in v25)
ZK version 3.7

### Description

During patching of our underlying EKS nodes, we observe a condition wherein 2 coordinators are elected leader. When we encounter this condition, we see multiple task failures across different data sources.

image

### PR DESCRIPTION
**Pull request by razinbouzar**
Fixes #16411 .

### Description

Introduces a new private method handleConnectionStateChanged to handle connection state changes, which recreates the leader latch if the connection state is SUSPENDED or LOST.

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by razinbouzar** [comment]
@kfaraz I took an attempt at resolving this if you can take a look and provide feedback it would be appreciated! Thank you!

**Comment by kfaraz** [comment]
Thanks a lot, @razinbouzar ! You beat me to it. 🙂 

I have been doing some investigation on this. Overall, your solution makes sense to me. But I am still going to try it out in my local setup that I have been using for testing.

One important thing that I have noticed is that the `isLeader()` method may be called on the leader latch listener even after the latch has been closed. So we would need to make sure that if this method is called on a closed latch, we just ignore that event.

I will share more details here in a bit.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 1]
```diff
@@ -65,11 +63,10 @@ public CuratorDruidLeaderSelector(CuratorFramework curator, @Self DruidNode self
     this.curator = curator;
     this.self = self;
     this.latchPath = latchPath;
-
-    // Creating a LeaderLatch here allows us to query for the current leader. We will not be considered for leadership
-    // election until LeaderLatch.start() is called in registerListener(). This allows clients to observe the current
-    // leader without being involved in the election.
     this.leaderLatch.set(createNewLeaderLatch());
+
+    // Adding ConnectionStateListener to handle session changes using a method reference
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:68]: this comment is not needed, the code is self explanatory.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 2]
```diff
@@ -80,66 +77,62 @@ private LeaderLatch createNewLeaderLatch()
...
-    );
+
+          leader = false;
+          listener.stopBeingLeader();
+        }
+        catch (Exception ex) {
+          log.makeAlert(ex, "listener.stopBeingLeader() failed. Unable to stopBeingLeader").emit();
+        }
+      }
+    }, listenerExecutor);
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:135]: This seems like only a formatting change, please revert this.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 3]
```diff
@@ -215,4 +208,37 @@ public void unregisterListener()
     CloseableUtils.closeAndSuppressExceptions(leaderLatch.get(), e -> log.warn(e, "Failed to close LeaderLatch."));
     listenerExecutor.shutdownNow();
   }
+
+  // Method to handle connection state changes
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:212]:
```suggestion
  /**
   * Handles connection state changes. Recreates the leader latch if connection to zookeeper is lost.
   */
```

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 4]
```diff
@@ -215,4 +208,37 @@ public void unregisterListener()
...
+    }
+  }
+
+  private void recreateLeaderLatch()
+  {
+    // Close existing leader latch
+    CloseableUtils.closeAndSuppressExceptions(leaderLatch.get(), e -> log.warn(e, "Failed to close LeaderLatch."));
+
+    // Create and start a new leader latch
+    LeaderLatch newLeaderLatch = createNewLeaderLatchWithListener();
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:235]: The latch returned by `createNewLeaderLatchWithListener()` is actually the old latch.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 5]
```diff
@@ -215,4 +208,37 @@ public void unregisterListener()
...
+    try {
+      newLeaderLatch.start();
+    }
+    catch (Exception ex) {
+      throw new RuntimeException("Failed to start new LeaderLatch after session change", ex);
+    }
+    leaderLatch.set(newLeaderLatch);
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:242]: Please take a look at these lines in the code:
https://github.com/apache/druid/blob/b53d75758fd5b8d30cbd3836bfa0a954f01ced84/server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java#L103-L120

The new method `recreateLeaderLatch()` needs to do exactly this.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 6]
```diff
@@ -80,66 +77,62 @@ private LeaderLatch createNewLeaderLatch()
...
-              listener.stopBeingLeader();
-            }
-            catch (Exception ex) {
-              log.makeAlert(ex, "listener.stopBeingLeader() failed. Unable to stopBeingLeader").emit();
-            }
+      @Override
+      public void notLeader()
+      {
+        try {
+          if (!leader) {
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:123]: When connection is lost, the `notLeader()` method is also called. So I wonder if we even need to have a state change listener or if we should just recreate the latch in this method.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 7]
```diff
@@ -80,66 +77,62 @@ private LeaderLatch createNewLeaderLatch()
   private LeaderLatch createNewLeaderLatchWithListener()
   {
     final LeaderLatch newLeaderLatch = createNewLeaderLatch();
+    newLeaderLatch.addListener(new LeaderLatchListener()
+    {
+      @Override
+      public void isLeader()
+      {
+        try {
+          if (leader) {
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:86]: We need to handle the case where this method is called with `newLeaderLatch.getState() == CLOSED`.

**Review by kfaraz — COMMENTED** [review]
I have left some suggestions. Overall approach makes sense to me.

I still need to test out the changes in my local setup.
An alternative solution I was thinking of was just to recreate the latch in `notLeader()` method. We would need to evaluate if one is better than the other.

**Comment by kfaraz** [comment]
> One important thing that I have noticed is that the isLeader() method may be called on the leader latch listener even after the latch has been closed. So we would need to make sure that if this method is called on a closed latch, we just ignore that event.

For more information, I encountered this in my local testing when I was trying to recreate the latch in `notLeader()`.

Timeline:
-[curator-thread] Leader loses connection
- Leader gets notified with `notLeader()`
-[curator-thread] Connection is re-established
- Create new latch, close old one. This immediately causes some other node to become leader.
- Start new latch after a delay to allow other nodes to become leader.
- `isLeader()` is called on old latch which is already closed. (This leads to double leaders if not properly handled.)

An example sequence of events that I observed
```
2024-05-30T14:19:11,556 WARN [main-SendThread(localhost:2181)] org.apache.zookeeper.ClientCnxn - Session 0x1002399b0fc0000 for server localhost/127.0.0.1:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
2024-05-30T14:19:11,670 INFO [LeaderSelector[/druid/overlord/_OVERLORD]] org.apache.druid.curator.discovery.CuratorDruidLeaderSelector - [http://localhost:8081][1] Giving up leadership
2024-05-30T14:19:11,754 INFO [main-SendThread(localhost:2183)] org.apache.zookeeper.ClientCnxn - Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2183, session id = 0x1002399b0fc0000, negotiated timeout = 30000
2024-05-30T14:19:11,766 INFO [LeaderSelector[/druid/overlord/_OVERLORD]] org.apache.druid.curator.discovery.CuratorDruidLeaderSelector - [http://localhost:8081][1] Recreating leader latch to allow other nodes to become leader.
2024-05-30T14:19:13,379 INFO [LeaderSelector[/druid/overlord/_OVERLORD]] org.apache.druid.curator.discovery.CuratorDruidLeaderSelector - [http://localhost:8081][1] Now starting the latch
2024-05-30T14:19:13,379 INFO [LeaderSelector[/druid/overlord/_OVERLORD]] org.apache.druid.curator.discovery.CuratorDruidLeaderSelector - [http://localhost:8081][1] I am now the leader. Latch state[CLOSED]
```

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java (hunk 6 above)
Comment (razinbouzar) [reply server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:123]: This would significantly reduce complexity. Something like...?

`leader = false;
listener.stopBeingLeader();

// Recreate the leader latch when connection is lost or the node stops being the leader
recreateLeaderLatch();`

Comment (kfaraz) [reply server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:123]: Yes, this is what I have been trying out locally. But let me try out having a state listener too.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 8]
```diff
@@ -65,11 +63,10 @@ public CuratorDruidLeaderSelector(CuratorFramework curator, @Self DruidNode self
     this.curator = curator;
     this.self = self;
     this.latchPath = latchPath;
-
-    // Creating a LeaderLatch here allows us to query for the current leader. We will not be considered for leadership
-    // election until LeaderLatch.start() is called in registerListener(). This allows clients to observe the current
-    // leader without being involved in the election.
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:71]: Why has this comment been removed?

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java (hunk 6 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:123]: I double checked the `LeaderLatch` code. As expected, it already has a `ConnectionStateListener` which calls `notLeader` if connection is lost or gets suspended.

https://github.com/apache/curator/blob/5af54047d3a1d85a8c08fae097b7bc1329f2a55c/curator-recipes/src/main/java/org/apache/curator/framework/recipes/leader/LeaderLatch.java#L638-L648

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java (hunk 2 above)
Comment (razinbouzar) [reply server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java]: This has been reverted.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java (hunk 8 above)
Comment (razinbouzar) [reply server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java]: This was by mistake. Added back with the latest commit.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java (hunk 4 above)
Comment (razinbouzar) [reply server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java]: Re-wrote the method per feedback [here](https://github.com/apache/druid/pull/16528#discussion_r1622747033)

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java (hunk 2 above)
Comment (kfaraz) [reply server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java]: Thanks!

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 9]
```diff
@@ -70,6 +71,8 @@ public CuratorDruidLeaderSelector(CuratorFramework curator, @Self DruidNode self
     // election until LeaderLatch.start() is called in registerListener(). This allows clients to observe the current
     // leader without being involved in the election.
     this.leaderLatch.set(createNewLeaderLatch());
+
+    curator.getConnectionStateListenable().addListener(this::handleConnectionStateChanged);
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:75]: I don't think we need this now since we are already recreating the latch when `notLeader` is called.
See https://github.com/apache/druid/pull/16528#discussion_r1623237401 for reference.

File: server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java [hunk 10]
```diff
@@ -215,4 +219,45 @@ public void unregisterListener()
...
+      case RECONNECTED:
+        // Connection reestablished, no action needed here
+        break;
+      default:
+        // Do nothing for other states
+        break;
+    }
+  }
+
+  private void recreateLeaderLatch()
```
Comment (kfaraz) [inline server/src/main/java/org/apache/druid/curator/discovery/CuratorDruidLeaderSelector.java:242]: Please use this method in line 107 as well instead of duplicating the code there.

**Review by kfaraz — COMMENTED** [review]
Please add a unit test that verifies the new behaviour.
Also the case `state = CLOSED` still needs to be handled in the `isLeader()` method of the listener.

**Review by kfaraz — APPROVED** [review]
I have done some basic testing changes with these changes and they look good.
I have a follow up PR #16544 to this where I intend to add tests to verify the behaviour and fix other race conditions.

Thanks a lot for the changes, @razinbouzar !
