### PR TITLE
Fix broken sampler for re-indexing

### LINKED ISSUE #10197: Re-indexing a Druid datasource from the web console is broken
### Affected Version

0.19.0

### Description

If a user tries to re-index a Druid datasource from the web console, it fails with the following exception

```
Error: Missing type id when trying to resolve subtype of [simple type, class org.apache.druid.data.input.InputFormat]: missing type id property 'type' (for POJO property 'inputFormat') at [Source: (org.eclipse.jetty.server.HttpInputOverHTTP); line: 1, column: 195] (through reference chain: org.apache.druid.indexing.overlord.sampler.IndexTaskSamplerSpec["spec"]>org.apache.druid.indexing.common.task.IndexTask$IndexIngestionSpec["ioConfig"]>org.apache.druid.indexing.common.task.IndexTask$IndexIOConfig["inputFormat"])
```

This is because the type of the inputFormat is not set for the sampler request that the web console sends. Submitting a re-index job without using the web console continues to work as expected.

Screen Shot 2020-07-16 at 10 04 56 AM

### PR DESCRIPTION
**Pull request by suneet-s**
Fixes  #10197 

### Description

When re-indexing a Druid datasource, the web-console would generate an invalid inputFormat 
since the type is not specified. The DruidInputSource does not need an InputFormat, so this change
skips adding an inputFormat to the provided spec.

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: web-console/src/utils/sampler.ts [hunk 1]
```diff
@@ -202,7 +203,10 @@ function makeSamplerIoConfig(
     ioConfig = deepSet(ioConfig, 'useEarliestSequenceNumber', sampleStrategy === 'start');
   }
   // In order to prevent potential data loss null columns should be kept by the sampler and shown in the ingestion flow
-  ioConfig = deepSet(ioConfig, 'inputFormat.keepNullColumns', true);
+  const reingestMode = isDruidSourceFromInputSource(deepGet(ioConfig, 'inputSource'));
+  if (!reingestMode) {
+    ioConfig = deepSet(ioConfig, 'inputFormat.keepNullColumns', true);
```
Comment (vogievetsky) [inline web-console/src/utils/sampler.ts:208]: the issue is that `ioConfig = deepSet(ioConfig, 'inputFormat.keepNullColumns', true);` creates the `ioConfig.inputFormat` object even if it is not there. Right?
I think the fix is to change:

```
ioConfig = deepSet(ioConfig, 'inputFormat.keepNullColumns', true);
```

to:

```
if (ioConfig.inputFormat) {
  ioConfig = deepSet(ioConfig, 'inputFormat.keepNullColumns', true);
}
```

And not worry about the `reingestMode` here (we want to set `keepNullColumns` even if we are not re-ingesting)

Comment (suneet-s) [reply web-console/src/utils/sampler.ts:208]: Done

**Comment by vogievetsky** [comment]
it would also be great to throw a unit test around these functions that you are modifying to ensure that `keepNullColumns` is not set if `inputFormat` does not exist

**Comment by vogievetsky** [comment]
`applyCache` already has some tests... maybe add to them?

**Comment by vogievetsky** [comment]
Thank you for the fix!

**Comment by suneet-s** [comment]
Sorry for the delay in adding the tests... I got pulled in to some other things, I'll have the tests up this week :)
