### PR TITLE
#12912 Fix KafkaEmitter not emitting queryType for a native query

### LINKED ISSUE #12912: KafkaEmitter for request emitting does not emit "queryType" for native queries
### Affected Version

The Druid version where the problem was encountered: `0.22.x`, `0.23.x`

### Description

When setting up a request emitter to use KafkaEmitter the `queryType` property is not serialized to a JSON. The problem is located in the method: `public void emit(final Event event)` of `KafkaEmitter.java`.

The problem is that the rendering of the JSON string is done on the `Map<String, Object>`. The Jackson ignores the polymorphic annotation on the Query class with `queryType` if the query is serialized as a part of the map (see: `DefaultRequestLogEvent` for explanation). If we serialize the query independently then the polymorphic annotation is respected.

### Proposed solution

The simples solution is to serialize an object to JsonNode first. If the `query` is present, then serialize it independently and replace the non-polymorphic version in the JsonNode.

### PR DESCRIPTION
**Pull request by BartMiki**
Fixes #12912.

### Description

Fixes KafkaEmitter not emitting `queryType` for a native query. The Event to JSON serialization was extracted to the external class: `EventToJsonSerializer`. This was done to simplify the testing logic for the serialization as well as extract the responsibility of serialization to the separate class.

The logic builds `ObjectNode` incrementally based on the event `.toMap` method. Parsing each entry individually ensures that the Jackson polymorphic annotations are respected. Not respecting these annotation caused the missing of the `queryType` from output event.

<hr>

##### Key changed/added classes in this PR
 * `KafkaEmitter` - modified
 * `EventToJsonSerializer` - added

<hr>

This PR has:
- [x] been self-reviewed.
- [x] added documentation for new or modified features or behaviors.
- [x] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

**Comment by FrankChen021** [comment]
`toMap` is a public interface that could be used anywhere, seems that all callers have to use the same way as `EventToJsonSerializer` to serialize the map object.

I don't know if there's any better idea that callers should not care about handling the serialization in a special way.

Another point is this test case `DefaultRequestLogEventTest#testDefaultrequestLogEventSerde` should cover the serialization of `toMap` method.

**Comment by BartMiki** [comment]
@FrankChen021 Thank you for the comment!

Yes, the serialization of the event is very simple, all implementations are Jackson aware, so serialization of Event to JSON is as simple as [in this test](https://github.com/apache/druid/blob/7fb1153bba73bbb1ae245a8acc7bf605463ed725/server/src/test/java/org/apache/druid/server/log/DefaultRequestLogEventTest.java#L72) or in the [HttpPostEmitter](https://github.com/apache/druid/blob/7fb1153bba73bbb1ae245a8acc7bf605463ed725/core/src/main/java/org/apache/druid/java/util/emitter/core/HttpPostEmitter.java#L272):
```java
objectMapper.writeValueAsString(event)
```
There are [tests](https://github.com/apache/druid/blob/7fb1153bba73bbb1ae245a8acc7bf605463ed725/server/src/test/java/org/apache/druid/server/log/DefaultRequestLogEventTest.java#L83) for checking the `.toMap`, but they only cover `.toMap` and compare it against other map (they do not serialize it further).

However, the problem is that the original KafkaEmitter requires to pass additional property to the output event, which is `clusterName` (if present). That is why we cannot serialize using simple POJO: 
```java
objectMapper.writeValueAsString(event)
```
The original author [created new map](https://github.com/apache/druid/blob/7fb1153bba73bbb1ae245a8acc7bf605463ed725/extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java#L169-L176) based on the `.toMap` and this optional `clusterName` property.
This is the problem, as there are no polymorphism-aware maps and lists (see [Jackson ticket](https://github.com/FasterXML/jackson-databind/issues/699#issuecomment-73382972)).

The only other solution that comes to my mind is to do:
1. If additional properties map is empty, then just return `objectMapper.writeValueAsString(event)`
2. If not empty, then:
  a) serialize event to `ObjectNode` using `objectMapper.valueToTree(event)` (serialize whole object in one go)
  b) add all KV pairs from additional parameters to the ObjectNode
  c) return serialized `ObjectNode` as a string

We won't use `.toMap` at any stage as we will be using the same simple implementation of Event -> JSON as other Emitters.
What do you think @FrankChen021 ?

**Comment by FrankChen021** [comment]
@BartMiki Thank you for the updated information. 

> This is the problem, as there are no polymorphism-aware maps and lists (see https://github.com/FasterXML/jackson-databind/issues/699#issuecomment-73382972).

Yes, this is the root cause. and seems that there's no way to deal with this problem without user-awareness.

Since all changes in this PR are in Kafka extension, it makes senses to me.

**Comment by BartMiki** [comment]
@FrankChen021 I will update the logic to use these steps (I think it is a bit more elegant):

> 1. If additional properties map is empty, then just return objectMapper.writeValueAsString(event)
> 2. If not empty, then:
> a) serialize event to ObjectNode using objectMapper.valueToTree(event) (serialize whole object in one go)
> b) add all KV pairs from additional parameters to the ObjectNode
> c) return serialized ObjectNode as a string

**Comment by BartMiki** [comment]
@FrankChen021 I have new findings and I would like your comment on this. If we serialize the map as I've implemented it before, then the output is the same as the previous KafkaEmitter (of course with the `queryType`). So for native query parameters `sql` and `sqlQueryCtx` are absent from the output JSON.

If we serialize the whole event to JSON first then for the native query the `sql` and `sqlQueryCtx` are set to `null` and `{}` respectively in the output JSON. Now the question is about backward compatibility.

If I use the second implementation then the output will be different from the original implementation. This may lead to errors in the consumers of the emitted stream. If consumer code distinguishes the SQL from native queries solely by the presence of `native` or `sql`, then it will no longer work because both entries are present. Of course, corresponding fields are null, but previously they were totally absent from the output JSON. This is because `.toMap` removes null entries of "query" and "sql" from the resulting map.

Example consumer in Python:
```python
event = json.loads(rawEvent)
if "query" in event:
    # do stuff with Native Query
elif "sql" in event:
    # do stuff with SQL Query
```
If I leave my implementation as is right now, then the above code would work correctly (backward compatible with the original KafkaEmitter logic). 
However, if I update the code as described here: https://github.com/apache/druid/pull/12915#issuecomment-1219221809 then the above snippet will always execute first `if` branch as "query" is always present. 
 
Should I leave the fixed implementation as is right now to maintain this compatibility or should I go with (the perhaps braking) approach of serializing the whole event at once? My take is to leave fix as is to have backward compatibility. What do you think @FrankChen021 ?

**Comment by FrankChen021** [comment]
I think you can keep the implementation as is right now, because in current case, the additional property map is always not empty, the 2nd implementation seems no gain.

**Review by FrankChen021 — APPROVED** [review]

**Comment by FrankChen021** [comment]
Failed CI task has been re-trigger. I believe it has nothing to do with changes in this PR

**Comment by BartMiki** [comment]
Thank you! Ultimately I can rebase from master and push if the check keeps failing. 

I have also another question @FrankChen021 : Can I backport this fix to the stable branch? How can I do it? What is the best way to address backporting?

**Comment by FrankChen021** [comment]
Usually issues, such as severe security issues, will be backported. And as I know, currently there's no plan for version like 0.23.x

File: extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java [hunk 1]
```diff
@@ -0,0 +1,269 @@
...
+import org.apache.druid.query.spec.MultipleIntervalSegmentSpec;
+import org.apache.druid.query.timeseries.TimeseriesQuery;
+import org.apache.druid.segment.VirtualColumns;
+import org.apache.druid.server.QueryStats;
+import org.apache.druid.server.RequestLogLine;
+import org.apache.druid.server.log.DefaultRequestLogEventBuilderFactory;
+
+import java.util.Collections;
+
+public class EventToJsonSerializerTest extends TestCase
```
Comment (FrankChen021) [inline extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java:45]:
```suggestion
public class EventToJsonSerializerTest
```

Druid uses '@Test' annotation on each test method to mark it as a test case instead of declaring a whole class as a subclass of `TestCase`.

**Comment by FrankChen021** [comment]
@BartMiki Thank you for the updating. The change generally LGTM with some minor comments.

File: extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java (hunk 1 above)
Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java:45]: Sure, I'll change that. TestCase was actually autogenerated by IntelliJ

Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java]: Fixed

**Comment by FrankChen021** [comment]
@rohangarg Would you like to review this change?

**Comment by FrankChen021** [comment]
@BartMiki The checkstyle task  in CI fails to run. Could you fix it?

File: core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+
+import com.fasterxml.jackson.databind.annotation.JsonSerialize;
+
+import java.util.HashMap;
+import java.util.Map;
+
+/**
+ * EventMap can be safely serialzed to JSON using Jackson serializer as it respects the polymorphic annotations
+ * on entires (unlike standard Map). The example of polymorphic class is a query interface, where different native
+ * query types are resolved by additional field called "queryType". This implementation esures that the annotation on
```
Comment (rohangarg) [inline core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java:30]: `This implementation *ensures*`

File: extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java [hunk 3]
```diff
@@ -166,14 +169,14 @@ private void sendToKafka(final String topic, MemoryBoundLinkedBlockingQueue<Stri
...
-      if (config.getClusterName() != null) {
-        resultBuilder.put("clusterName", config.getClusterName());
-      }
-      Map<String, Object> result = resultBuilder.build();
-
       try {
-        String resultJson = jsonMapper.writeValueAsString(result);
+        EventMap map = event.toMap();
+        if (config.getClusterName() != null) {
+          map.put("clusterName", config.getClusterName());
```
Comment (rohangarg) [inline extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java:175]: the map should be copied to a new structure before modification - it is better to not expect the object to be mutable

File: extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java [hunk 4]
```diff
@@ -0,0 +1,276 @@
...
+import org.apache.druid.server.QueryStats;
+import org.apache.druid.server.RequestLogLine;
+import org.apache.druid.server.log.DefaultRequestLogEventBuilderFactory;
+import org.junit.Assert;
+import org.junit.Test;
+
+import java.util.Collections;
+
+
+public class EventToJsonSerializerTest
```
Comment (rohangarg) [inline extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java:47]: doubt : I couldn't understand why this change is kept in kafka-emitter extension and not core. is there a reason for it?

File: server/src/main/java/org/apache/druid/server/log/DefaultRequestLogEvent.java [hunk 5]
```diff
@@ -55,23 +55,26 @@ public final class DefaultRequestLogEvent implements RequestLogEvent
...
-      map.put("sqlQueryContext", getSqlQueryContext());
+      builder.put("sql", getSql())
+             .put("sqlQueryContext", getSqlQueryContext());
     }
-    map.put("remoteAddr", getRemoteAddr());
-    map.put("queryStats", getQueryStats());
-    return map;
+
+    builder
+        .put("remoteAddr", getRemoteAddr())
```
Comment (rohangarg) [inline server/src/main/java/org/apache/druid/server/log/DefaultRequestLogEvent.java:74]: the indentation seems a bit weird. The first put can be on the same line

**Review by rohangarg — APPROVED** [review]
Thanks for the changes @BartMiki !
LGTM % comments

**Comment by rohangarg** [comment]
> @rohangarg Would you like to review this change?

@FrankChen021 : Yes, apologies for the delayed response - got caught up in something else meanwhile. I have posted a small review, should be good from my side once that is done. Thanks for the reminder! :+1:

**Comment by BartMiki** [comment]
> @BartMiki The checkstyle task in CI fails to run. Could you fix it?

Sure, I'm on it

File: extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java (hunk 3 above)
Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java:175]: I can replace EventMap to extend the ImmutableMap instead of HashMap, what do you think? Then it will be always immutable on the output.

File: extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java (hunk 4 above)
Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java:47]: This is a good catch @rohangarg . Previously I have a class that belongs to the kafka-emitter and these were the test for this class. We replace that with EventMap later. One problem with moving the test to the core: DefaultRequestLogEvent is not part of the core, but part of the server.
But I can split the test logic to the corresponding packages and remove this class altogether.

File: server/src/main/java/org/apache/druid/server/log/DefaultRequestLogEvent.java (hunk 5 above)
Comment (BartMiki) [reply server/src/main/java/org/apache/druid/server/log/DefaultRequestLogEvent.java:74]: Right, I'll fix that

File: extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java (hunk 3 above)
Comment (rohangarg) [reply extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java:175]: If that works, I think that'll be ok. But I'm not sure if it will expose all methods which `HashMap` does. Maybe, can also return an `ImmutableMap` object from the builder's build. Immutability would also require making the default constructor private so that we don't create a mutable map from there.

File: extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java (hunk 4 above)
Comment (rohangarg) [reply extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java:47]: Thanks! Yes, the `DefaultRequestLogEvent` test can go in `DefaultRequestLogEventTest` class. It already contains a test for the object serde. probably the tests for other events could also go in their respective test classes.

File: extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java (hunk 3 above)
Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java:175]: If we return ImmutableMap then we get back to the serialization problem with Map and polymorphic types in Jackson. `build` needs to return EventMap in this case.

Comment (rohangarg) [reply extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java:175]: Ah, yes you're right. In that case, maybe you need to create an `EventMap` copy here and put additional attributes in it.

File: extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java (hunk 4 above)
Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/test/java/org/apache/druid/emitter/kafka/EventToJsonSerializerTest.java:47]: I moved the tests to druid-server (as we need access to the DefaultObjectMapper which is not available in Core) and split it into corresponding classes.

File: extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java (hunk 3 above)
Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java:175]: Extending ImmutableMap is tricky (and IMO not worth it). I just added this:
```java
  /**
   * Convert this EventMap to a builder. Performs copy of the whole EventMap.
   */
  public Builder asBuilder() {return new Builder().putAll(this);}
```
So you can get a builder out of the existing EventMap and modify the copy.

Comment (BartMiki) [reply extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java:175]: And then we can use it like this:
```java
        EventMap map = event.toMap()
                            .asBuilder()
                            .putNonNull("clusterName", config.getClusterName())
                            .build();
```
or this (we avoid copying if we don't need to modify the map): 
```java
        EventMap map = event.toMap();
        if (config.getClusterName() != null) {
          map = map.asBuilder()
                   .put("clusterName", config.getClusterName())
                   .build();
        }
```

Comment (rohangarg) [reply extensions-contrib/kafka-emitter/src/main/java/org/apache/druid/emitter/kafka/KafkaEmitter.java]: good idea! :+1:

File: server/src/test/java/org/apache/druid/server/log/AlertMetricServiceTest.java [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+import org.apache.druid.jackson.DefaultObjectMapper;
+import org.apache.druid.java.util.common.DateTimes;
+import org.apache.druid.java.util.emitter.core.Event;
+import org.apache.druid.java.util.emitter.service.AlertEvent;
+import org.junit.Assert;
+import org.junit.Test;
+
+import java.util.Collections;
+
+public class AlertMetricServiceTest
```
Comment (rohangarg) [inline server/src/test/java/org/apache/druid/server/log/AlertMetricServiceTest.java:33]: should it be `AlertMetricSerdeTest`?

Comment (BartMiki) [reply server/src/test/java/org/apache/druid/server/log/AlertMetricServiceTest.java]: Fixed

File: core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java [hunk 7]
```diff
@@ -0,0 +1,109 @@
...
+import java.util.Map;
+
+/**
+ * EventMap is a hash map implementation. It can be safely serialzed to JSON using Jackson serializer as it
+ * respects the polymorphic annotations on entires (unlike standard Map). The example of polymorphic class is a query
+ * interface, where different native query types are resolved by additional field called "queryType".
+ * This implementation ensures that the annotation on the values are respected during serialization.
+ */
+@JsonSerialize(using = EventMapSerializer.class)
+public class EventMap extends HashMap<String, Object>
```
Comment (rohangarg) [inline core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java:34]: @BartMiki @FrankChen021 : I just noticed that we're extending `HashMap` instead of a `Map`. This would mean that any of the consumers extending `PublicApi` like `AlertEvent`, `RequestLogEvent` or `ServiceMetricEvent` can't use any other forms of `Map` in their implementations other than `HashMap`.
Further, even if someone is using `HashMap<String, Object>` already, they would need to cast the map to an `EventMap` which I don't think is correct.
So, the correct solution for the developers would be to change their implementation to use `EventMap` itself which again break compatibility. Are we ok with doing this change?

**Review by rohangarg — CHANGES_REQUESTED** [review]

File: core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java (hunk 7 above)
Comment (rohangarg) [reply core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java:34]: I followed the GH issue thread and there is seems that this was discussed and we're ok with this change (https://github.com/apache/druid/issues/12912#issuecomment-1221918198). will wait for confirmatiom from Frank

Comment (FrankChen021) [reply core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java:34]: @rohangarg Since we have changed the signature of `toMap()` in the `Event` interface and all its implementations in this PR, I think there won't be compatibility problems.

Comment (rohangarg) [reply core/src/main/java/org/apache/druid/java/util/emitter/core/EventMap.java:34]: Thanks for the explanations Bart and Frank! I agree that it won't break compatibility since the callers of the `Event` impls. can still cast the `EventMap` returned by `toMap()` to a `Map<String, Object>` and that's the only contract for `PublicApi` annotated interfaces.

**Review by rohangarg — APPROVED** [review]
LGTM after the CI passes.
Thanks a lot for the changes @BartMiki

**Comment by BartMiki** [comment]
Thank you @FrankChen021 and @rohangarg for your support and engaging discussion! It was a pleasure to work on this with you :+1:

**Comment by abhishekagarwal87** [comment]
Thank you @BartMiki for your contribution.
