### PR TITLE
Fix is null selector returning incorrect value for Long data type

### LINKED ISSUE #10073: "is null" returns null for row with null instead of true for numeric column with druid.generic.useDefaultValueForNull=false
### Affected Version

Tested in version 0.18.1

### Description

While investigating the correctness of druid's null handling by setting `druid.generic.useDefaultValueForNull=false` I noticed that in sql `is null` returns `null` when the value of the column is `null`.
### Steps to reproduce

1) set `druid.generic.useDefaultValueForNull=false` in common.runtime.properties, i used the the micro quick start to test this (./bin/start-micro-quickstart)

2) Load the example data from the ingestion spec below, this is an inline datasource. the data looks like this:

```
{"id":1,"duration":null}
{"id":2,"duration":null}
{"id":3,"duration":98}
{"id":4,"duration":6}
{"id":5,"duration":73}
{"id":6,"duration":1}
{"id":7,"duration":56}
{"id":8,"duration":null}
{"id":9,"duration":null}
{"id":10,"duration":null}
```

3) run the following query 

```
select duration, duration is null as "duration_is_null" from just_duration
```

**Actual result :**

```
{"duration":null,"duration_is_null":null}
{"duration":null,"duration_is_null":null}
{"duration":98,"duration_is_null":false}
{"duration":6,"duration_is_null":false}
{"duration":73,"duration_is_null":false}
{"duration":1,"duration_is_null":false}
{"duration":56,"duration_is_null":false}
{"duration":null,"duration_is_null":null}
{"duration":null,"duration_is_null":null}
{"duration":null,"duration_is_null":null}
```

**Expected result:** `duration_is_null` should be `true` when `duration` is null.

### Example ingestion spec

```
{
  "type": "index_parallel",
  "spec": {
    "ioConfig": {
      "type": "index_parallel",
      "inputSource": {
        "type": "inline",
        "data": "{\"id\":1,\"duration\":null}\n{\"id\":2,\"duration\":null}\n{\"id\":3,\"duration\":98}\n{\"id\":4,\"duration\":6}\n{\"id\":5,\"duration\":73}\n{\"id\":6,\"duration\":1}\n{\"id\":7,\"duration\":56}\n{\"id\":8,\"duration\":null}\n{\"id\":9,\"duration\":null}\n{\"id\":10,\"duration\":null}"
      },
      "inputFormat": {
        "type": "json"
      }
    },
    "tuningConfig": {
      "type": "index_parallel",
      "partitionsSpec": {
        "type": "dynamic"
      }
    },
    "dataSchema": {
      "dataSource": "just_duration",
      "granularitySpec": {
        "type": "uniform",
        "queryGranularity": "NONE",
        "rollup": false,
        "segmentGranularity": "YEAR"
      },
      "timestampSpec": {
        "column": "id",
        "format": "posix"
      },
      "dimensionsSpec": {
        "dimensions": [
          {
            "type": "long",
            "name": "duration"
          }
        ]
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by mSitkovets**
Fixes #10073.

#### Fixed the bug:
After setting `druid.generic.useDefaultValueForNull=false`, it was discovered that for columns of type `Long` the sql `is null` selector returns `null` if the input is `null` but that behavior is incorrect for the `is null` function.

To fix the issue I have set the `bindings` variable to `null` so that if the selector is `is null`and the value is `null` then it will be evaluated to `true` as expected from this selector. This solution lets the expression handle the behavior for `null` by sending the value of `bindings` to be evaluated in the `eval` function. 

If the previous input value was also `null` then the computation will be skipped and the cached value for `lastOutput` will be returned to improve performance.

I have also added a test to the `CalciteQuery` suite to ensure that this case is handled correctly.

#### Other options considered:
We can hardcode this special case into `SingleLongInputCachingExpressionColumnValueSelector.java` by checking if the expression `is null` and then returning `true` within that function. This is not the best solution and changing the logic within this function might affect other areas of the code that we don’t know about.
We could use a different selector for `is null` expressions but this seemed more complicated to implement and is not done for any of the other data types.

<hr>

##### Key changed/added classes in this PR
 * New unit test `testLongPredicateIsNull`
 * Extra logic for returning `true` instead of `null` in `SingleLongInputCachingExpressionColumnValueSelector.java`

<hr>

This PR has:
- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: processing/src/main/java/org/apache/druid/segment/virtual/SingleLongInputCachingExpressionColumnValueSelector.java [hunk 1]
```diff
@@ -99,7 +99,8 @@ public ExprEval getObject()
   {
     // things can still call this even when underlying selector is null (e.g. ExpressionColumnValueSelector#isNull)
     if (selector.isNull()) {
-      return ExprEval.ofLong(null);
+      bindings.set(null);
+      return expression.eval(bindings);
```
Comment (gianm) [inline processing/src/main/java/org/apache/druid/segment/virtual/SingleLongInputCachingExpressionColumnValueSelector.java:103]: Hmm, we should cache the result of `expression.eval(bindings)` for null too. (The purpose of this selector is to cache expression evaluations, and there might be a lot of nulls in a column, so it might be very useful to do that!)

I'd suggest adding a `lastInputIsNull` boolean and adjusting the logic of getObject accordingly: set it to true when we encounter a null, set it to false when we encounter nonnull.

**Review by gianm — COMMENTED** [review]
Good catch! Probably, the original thought was that exprs on null should themselves return null. It's true somewhat often but not always.

File: processing/src/main/java/org/apache/druid/segment/virtual/SingleLongInputCachingExpressionColumnValueSelector.java [hunk 2]
```diff
@@ -46,7 +47,8 @@
   private final LruEvalCache lruEvalCache;
 
   // Last read input value.
-  private long lastInput;
+  @Nullable
+  private Long lastInput;
```
[the remark this answers is not in the document]
Comment (mSitkovets) [reply processing/src/main/java/org/apache/druid/segment/virtual/SingleLongInputCachingExpressionColumnValueSelector.java:51]: Yup that makes sense. I'll try that out!

**Comment by mSitkovets** [comment]
I added new variables `cachedIsNull` and `outputForNull` so that once we have cached the output for null once then any other time we see null as input we can use our cached value. The original code was only caching the value if the nulls were consecutive.

**Comment by mSitkovets** [comment]
@gianm do you have any thoughts on this?

File: processing/src/main/java/org/apache/druid/segment/virtual/SingleLongInputCachingExpressionColumnValueSelector.java [hunk 3]
```diff
@@ -97,26 +104,30 @@ public long getLong()
...
   {
-    // things can still call this even when underlying selector is null (e.g. ExpressionColumnValueSelector#isNull)
+    boolean cached;
+    boolean currentInputIsNull = false;
     if (selector.isNull()) {
-      return ExprEval.ofLong(null);
+      cached = cachedIsNull;
+      currentInputIsNull = true;
+    } else {
+      cached = selector.getLong() == lastInput && lastOutput != null;
```
Comment (clintropolis) [inline processing/src/main/java/org/apache/druid/segment/virtual/SingleLongInputCachingExpressionColumnValueSelector.java:113]: This seems a bit over complicated to me, and isn't fully taking of advantage of the cached null expression evaluation you've added. What about if we instead did something like what you've got so far, where we are always saving a special cached value for null, but maybe annotated slightly differently to indicate its behavior:

```java
  @MonotonicNonNull
  private ExprEval nullOutput;
```

and then this block looks like:

```java
    if (selector.isNull()) {
      if (nullOutput == null) {
        bindings.set(null);
        nullOutput = expression.eval(bindings);
      }
      return nullOutput;
    }
```

and none of the logic after the `selector.isNull()` check has to change at all because there isn't really a need to go through the remaining logic if the underlying selector is null. I tested this and the test you've added still passes, and I think it would make the logic a bit clearer to follow. What do you think?

Comment (mSitkovets) [reply processing/src/main/java/org/apache/druid/segment/virtual/SingleLongInputCachingExpressionColumnValueSelector.java]: YES this is much cleaner and less complicated than my solution. Thank you for your help!

**Review by clintropolis — APPROVED** [review]
lgtm :+1: 

CI cannot possibly pass the coverage check for the processing module, which cannot be satisfied when `druid.generic.useDefaultValueForNull=true` because the changed code-path only affects sql compatible null handling mode, so i think we can ignore it.

I've triggered the integration tests to run anyway, but think we can merge after they finish up.

**Review by gianm — APPROVED** [review]
Apologies for the delay. Your latest patch looks good to me! It's nice and simpler than what I was suggesting — I guess there's no reason for `lastInputIsNull` since it doesn't really hurt to cache the null output forever. Thanks for this & for the test case.

**Comment by gianm** [comment]
> CI cannot possibly pass the coverage check for the processing module, which cannot be satisfied when druid.generic.useDefaultValueForNull=true because the changed code-path only affects sql compatible null handling mode, so i think we can ignore it.

The two processing module tests are failed due to coverage checks, but as you point out, they can't possibly pass coverage. I checked and the unit tests actually did pass, so I think we're ok to override the coverage check.

> I've triggered the integration tests to run anyway, but think we can merge after they finish up.

They just finished, except for "(Compile=openjdk8, Run=openjdk11, ZK=3.4) leadership and high availability integration tests", which failed. I retriggered it. I can't see how this patch would affect it, though, so I'll override this one too.
