### PR TITLE
Fix Concurrent Task Insertion in pendingCompletionTaskGroups

### LINKED ISSUE #16727: Actively Reading tasks fails even though Pending completion tasks are a success
### Affected Version
Druid 25.0.0

### Description

We are facing a bug in [SeekableStreamSupervisor.java](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L2067) .
We are running a Kafka Ingestion Supervisor, with task replication 2. Task group [3] consuming from partition [P1, P2] contains two tasks `[A1, A2]`  , each one consuming from same partitions (Replica tasks) . When we submit the supervisor config, [A1, A2] are to be added in `PendingCompletionTaskgroup` , as `{ groupId:3, [ TaskGroup[A1, A2] ]  }` . But what we observed from some logs like
1 . Creating new pending completion task group [3] for discovered task [A1]	overlord-0
2 .	Creating new pending completion task group [3] for discovered task [A2]	overlord-0
3 .	Added discovered task [A2] to existing pending task group [3]
Which makes the state of PendingCompletionTaskGroup as `{ groupId:3, [ TaskGroup[A1, A2], TaskGroup[A2] ] }` . We have seen the logs from sequence `1` and `2` are from two different process threads, and probably due to some Synchronisation issues in `CopyOnWriteArrayList` , we are getting two task groups with duplicate taskIds, instead of one in a taskGroup.
We have further Rootcaused this issue due to `forEach` loop [here](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L2067), which instead of calling `addDiscoveredTaskToPendingCompletionTaskGroups` for A1, A2 , permutes it with partitions too, and calls for `A1_P1, A2_P1,  A1_P2, A2_P2` , causing these multiple task groups to be created in a lot of cases. (Almost 17% of cases)
The problem that arises due to this is, as we have `[ TaskGroup[A1, A2], TaskGroup[A2] ]` in PendingCompletionGroup for a GroupId. We see in rare cases where even if A1 passes, and A2 fails . It can mark  [entireTaskGroupFailed = true](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L3491) . and not only kill [A1,A2] but kill all the[ actively running tasks](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L3540) which are running, causing ingestion lags.
We wanted to have a discussion on a potential fix for this issue, as this bug can cause ingestion lag incidents when we submit supervisor. On that, I also wanted a clarity on is having task group like `[ TaskGroup[A1, A2], TaskGroup[A2] ]`  in pendingCompletionGroup is an expected behaviour ? Should the taskId not be permuted with partitions Or we should add some synchronisation locks on preventing two replica tasks to be added in two different groups for a single groupId. Or is it a case to be considered in  [void checkPendingCompletionTasks()](https://github.com/apache/druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L3450) to avoid killing Actively running tasks.
Any help on understanding it better would be appreciated.

Please include as much detailed information about the problem as possible. 
I have included everything I can in the issue description, if any more logs or debugging is required, I can add in comments on ad-hoq requests
- Cluster size
- Configurations in use
- Steps to reproduce the problem
- The error message or stack traces encountered. Providing more context, such as nearby log messages or even entire logs, can be helpful.
- Any debugging that you have already done

### PR DESCRIPTION
**Pull request by hardikbajaj**
Fix Concurrent Task Insertion in pendingCompletionTaskGroups

Fixes #16727

### Description
Fixed thread synchronisation issue in [addDiscoveredTaskToPendingCompletionTaskGroups](https://github.com/apache/druid/blob/954aaafe0c85c1f4967bdb5798c17d4dc813ddd4/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L2485) so the pendingCompletionTaskGroup is properly locked while initialising.

As multiple threads with different task ids are hitting this function, they read a stale copy of concurrent hash map and create new pending completion task groups for tasks with same group id, which ideally should be added in a single TaskGroup.
To properly syncrhonize pendingCompletionTaskGroup across multiple threads, we need to do all updates inside the `compute` block as it locks the `Map[key]` and performs a write based on a locked read. This synchronises the value across all running threads

#### Fixed the bug ... 
#16727
[addDiscoveredTaskToPendingCompletionTaskGroups](https://github.com/apache/druid/blob/954aaafe0c85c1f4967bdb5798c17d4dc813ddd4/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java#L2485) is not properly Thread Synchronized and updates to it are made on the basis of a stale copy of reads. When we submit supervisor config, there are cases  where instead of adding all tasks in same TaskGroup, it can create Multiple copies of TaskGroups. For ex, if A1,A2 are consuming from same partition and are in same group, then
```
ideal_behavior: pendingCompletionTaskGroup[P] = { TaskGroup{A1,A2}  }
behavior_seen: pendingCompletionTaskGroup[P] = { TaskGroup{A1}, TaskGroup{A2} }
```
This is because, while initialising a new TaskGroup, the threads rely on a stale copy of read and multiple threads executing simultaneously, adding tasks to pendingCompletionTaskGroup can create new task groups instead of being added to existing ones. This behaviour defeats the purpose of Task replication as these single task taskgroup if gets failed for some reason, than Overlord sees it as entire task group is failed, and kill actively reading tasks too, to resume ingestion from last published segment.

#### Release note

<hr>

##### Key changed/added classes in this PR
 * `MyFoo`
 * `OurBar`
 * `TheirBaz`

<hr>

This PR has:

- [x] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [x] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [x] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [x] added integration tests.
- [x] been tested in a test Druid cluster.

### CODE REVIEW

File: indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorStateTest.java [hunk 1]
```diff
@@ -281,6 +287,110 @@ public void testRunningStreamGetSequenceNumberReturnsNull()
...
+    EasyMock.expect(recordSupplier.getPartitionIds(STREAM)).andReturn(ImmutableSet.of(SHARD_ID)).anyTimes();
+    EasyMock.expect(taskStorage.getActiveTasksByDatasource(DATASOURCE)).andReturn(ImmutableList.of()).anyTimes();
+    EasyMock.expect(taskQueue.add(EasyMock.anyObject())).andReturn(true).anyTimes();
+
+    replayAll();
+    ExecutorService threadExecutor = Execs.multiThreaded(3, "my-thread-pool-%d");
+
+    SeekableStreamSupervisor supervisor = new TestSeekableStreamSupervisor();
+    Map<String, String> startingPartiions = new HashMap<>();
+    startingPartiions.put("partition", "offset");
```
Comment (rbankar7) [inline indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorStateTest.java:303]: startingPartiions -> startingPartitions

Comment (hardikbajaj) [reply indexing-service/src/test/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisorStateTest.java:303]: Thanks, fixed it. i'll commit them with other reviews I get.

**Comment by AmatyaAvadhanula** [comment]
I think the logic may be incorrect.

We should expect the following test (that I have written) to pass with the current logic and it does.
However, the changes in this patch cause a failure.
```

  @Test
  public void testAddDiscoveredTaskToPendingCompletionTaskGroupsSync()
  {
    EasyMock.expect(spec.isSuspended()).andReturn(false).anyTimes();
    EasyMock.expect(recordSupplier.getPartitionIds(STREAM)).andReturn(ImmutableSet.of(SHARD_ID)).anyTimes();
    EasyMock.expect(taskStorage.getActiveTasksByDatasource(DATASOURCE)).andReturn(ImmutableList.of()).anyTimes();
    EasyMock.expect(taskQueue.add(EasyMock.anyObject())).andReturn(true).anyTimes();

    replayAll();

    SeekableStreamSupervisor supervisor = new TestSeekableStreamSupervisor();
    Map<String, String> startingPartiions = new HashMap<>();
    startingPartiions.put("partition", "offset");

    Map<String, String> startingPartiions1 = new HashMap<>();
    startingPartiions.put("partition", "offset1");

    supervisor.addDiscoveredTaskToPendingCompletionTaskGroups(0, "task_1", startingPartiions);
    supervisor.addDiscoveredTaskToPendingCompletionTaskGroups(0, "task_2", startingPartiions);
    supervisor.addDiscoveredTaskToPendingCompletionTaskGroups(0, "task_3", startingPartiions);

    supervisor.addDiscoveredTaskToPendingCompletionTaskGroups(0, "task_7", startingPartiions1);
    supervisor.addDiscoveredTaskToPendingCompletionTaskGroups(0, "task_8", startingPartiions1);
    supervisor.addDiscoveredTaskToPendingCompletionTaskGroups(0, "task_9", startingPartiions1);


    CopyOnWriteArrayList<SeekableStreamSupervisor.TaskGroup> taskGroups = supervisor.getPendingCompletionTaskGroups(0);
    Assert.assertEquals(2, taskGroups.size());
    Assert.assertEquals(3, taskGroups.get(0).tasks.size());
    Assert.assertEquals(3, taskGroups.get(1).tasks.size());
  }
```

I think it is because you're handling the task group but not the start offsets as part of your logic.

**Comment by AmatyaAvadhanula** [comment]
It might be helpful if you can also add comments explaining what this method does and why concurrent insertion was previously failing and why changing the order of steps would help.

**Comment by hardikbajaj** [comment]
Hey @AmatyaAvadhanula , thanks for identifying this case which I missed. 
I have improved the logic to handle this case.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java [hunk 2]
```diff
@@ -2482,43 +2482,72 @@ private void verifyAndMergeCheckpoints(final TaskGroup taskGroup)
...
       Map<PartitionIdType, SequenceOffsetType> startingPartitions
   )
   {
-    final CopyOnWriteArrayList<TaskGroup> taskGroupList = pendingCompletionTaskGroups.computeIfAbsent(
+    final CopyOnWriteArrayList<TaskGroup> taskGroupList = pendingCompletionTaskGroups.compute(
         groupId,
-        k -> new CopyOnWriteArrayList<>()
+        (k, val) -> {
+          // Creating new pending completion task groups while compute so that read and writes are locked.
+          // To ensure synchronisatoin across threads, we need to do updates in compute so that we get only one task group for all replica tasks
```
Comment (AmatyaAvadhanula) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java:2496]: Thanks for the comment

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java [hunk 3]
```diff
@@ -2482,43 +2482,72 @@ private void verifyAndMergeCheckpoints(final TaskGroup taskGroup)
...
-        Optional.absent(),
-        null
-    );
-
-    newTaskGroup.tasks.put(taskId, new TaskData());
-    newTaskGroup.completionTimeout = DateTimes.nowUtc().plus(ioConfig.getCompletionTimeout());
-
-    taskGroupList.add(newTaskGroup);
+  @VisibleForTesting
+  protected CopyOnWriteArrayList<TaskGroup> getPendingCompletionTaskGroups(int group_id)
```
Comment (AmatyaAvadhanula) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java:2548]: I wonder if there's a way we can do this without adding this test-only method.
Also please use `groupId` instead of `group_id`.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java [hunk 4]
```diff
@@ -2482,43 +2482,72 @@ private void verifyAndMergeCheckpoints(final TaskGroup taskGroup)
...
+        }
     );
+
     for (TaskGroup taskGroup : taskGroupList) {
       if (taskGroup.startingSequences.equals(startingPartitions)) {
         if (taskGroup.tasks.putIfAbsent(taskId, new TaskData()) == null) {
-          log.info("Added discovered task [%s] to existing pending task group [%s]", taskId, groupId);
+          log.info(
+              "Added discovered task [%s] to existing pending completion task group [%s]. PendingCompletionTaskGroup: %s",
+              taskId,
```
Comment (AmatyaAvadhanula) [inline indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java:2537]: Nit: The arguments after the log: taskId, groupId etc can be in a single line. I think this is permitted only for logging.

**Review by AmatyaAvadhanula — COMMENTED** [review]
Thanks for the fix, and the changes @hardikbajaj!

I was just wondering if we could somehow test this without adding a test-only method. LGTM otherwise.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java (hunk 3 above)
Comment (hardikbajaj) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java:2548]: Since `pendingCompletionTaskGroups` is a private variable, I created this read-only method. I can't read it in the child classes which we use for testing too, without changing it to protected.
I'll change the groupId.

File: indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java (hunk 4 above)
Comment (hardikbajaj) [reply indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/supervisor/SeekableStreamSupervisor.java:2537]: Thanks, will do that. I just went ahead with what CheckStyle formatted.

**Review by AmatyaAvadhanula — APPROVED** [review]
LGTM! Thank you, @hardikbajaj
