### PR TITLE
fix issue with jetty graceful shutdown of data servers when druid.serverview.type=http

### LINKED ISSUE #10600: Stream ingest Error when set coordiantor 'druid.serverview.type=http'
Set coordiantor `druid.serverview.type=http` and Stream Ingest Task will report ERROR when stopping.

### Affected Version
0.17.1

### Description
```
2020-11-24T02:42:42,769 ERROR [main] org.apache.druid.server.initialization.jetty.JettyServerModule - Jetty lifecycle event failed [class org.eclipse.jetty.server.Server]
java.util.concurrent.TimeoutException: null
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:129) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandlerContainer.doShutdown(AbstractHandlerContainer.java:181) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStop(Server.java:439) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) [jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.druid.server.initialization.jetty.JettyServerModule$2.stop(JettyServerModule.java:443) [druid-server-0.17.1.jar:0.17.1]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.stop(Lifecycle.java:368) [druid-core-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.CliPeon.run(CliPeon.java:299) [druid-services-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.17.1.jar:0.17.1]
2020-11-24T02:42:42,776 WARN [main] org.apache.druid.server.initialization.jetty.JettyServerModule - Unable to stop Jetty server.
java.util.concurrent.TimeoutException: null
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:129) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.FutureCallback.get(FutureCallback.java:30) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.handler.AbstractHandlerContainer.doShutdown(AbstractHandlerContainer.java:181) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.server.Server.doStop(Server.java:439) ~[jetty-server-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:89) ~[jetty-util-9.4.12.v20180830.jar:9.4.12.v20180830]
	at org.apache.druid.server.initialization.jetty.JettyServerModule$2.stop(JettyServerModule.java:443) [druid-server-0.17.1.jar:0.17.1]
	at org.apache.druid.java.util.common.lifecycle.Lifecycle.stop(Lifecycle.java:368) [druid-core-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.CliPeon.run(CliPeon.java:299) [druid-services-0.17.1.jar:0.17.1]
	at org.apache.druid.cli.Main.main(Main.java:113) [druid-services-0.17.1.jar:0.17.1]
2020-11-24T02:42:42,777 INFO [main] org.apache.druid.java.util.common.lifecycle.Lifecycle - Stopping lifecycle [module] stage [NORMAL]
```

### PR DESCRIPTION
**Pull request by clintropolis**
Fixes #10600.

### Description
This PR fixes an issue when `druid.serverview.type=http` is set, the mechanics of which use “long polling” to keep track of which servers have which segments, which interferes with the data node “graceful” shutdown of the Jetty server (the period is controlled by `druid.server.http.gracefulShutdownTimeout`). The default timeout for the long polling requests is 4 minutes, which is much longer than the 30s default request timeout, so the requests never finish, the jetty server blocks for the entire `gracefulShutdownTimeout`, and leaves an ugly error about `TimeoutException` for the request that was not completed within the timeout.

This happens consistently with both realtime streaming tasks and historical servers.

The solution is to make `ChangeRequestHistory` which is the historical side mechanism that serves the segment changes to brokers and coordinators be tied into the ‘announcement’ phase of the lifecycle, so that the futures can be resolved and the executor shutdown before we begin shutting down jetty, which will ensure that these requests do not tie up the jetty threads for something that isn’t going to happen.

This PR has:

- [ ] been self-reviewed.
   - [ ] using the [concurrency checklist](https://github.com/apache/druid/blob/master/dev/code-review/concurrency.md) (Remove this item if the PR doesn't have any relation to concurrency.)
- [ ] added documentation for new or modified features or behaviors.
- [ ] a release note entry in the PR description.
- [ ] added Javadocs for most classes and all non-trivial methods. Linked related entities via Javadoc links.
- [ ] added or updated version, license, or notice information in [licenses.yaml](https://github.com/apache/druid/blob/master/dev/license.md)
- [ ] added comments explaining the "why" and the intent of the code wherever would not be obvious for an unfamiliar reader.
- [ ] added unit tests or modified existing tests to cover new code paths, ensuring the threshold for [code coverage](https://github.com/apache/druid/blob/master/dev/code-review/code-coverage.md) is met.
- [ ] added integration tests.
- [ ] been tested in a test Druid cluster.

### CODE REVIEW

File: server/src/main/java/org/apache/druid/server/coordination/ChangeRequestsSnapshot.java [hunk 1]
```diff
@@ -43,6 +43,11 @@ public static <T> ChangeRequestsSnapshot<T> fail(String resetCause)
     return new ChangeRequestsSnapshot<>(true, resetCause, null, null);
   }
 
+  public static <T> ChangeRequestsSnapshot<T> shutdown(String resetCause)
```
Comment (rohangarg) [inline server/src/main/java/org/apache/druid/server/coordination/ChangeRequestsSnapshot.java:46]: this seems unused - did you decide to send ISE directly instead of this due to some reason?

File: server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java [hunk 2]
```diff
@@ -74,11 +76,24 @@ public ChangeRequestHistory(int maxSize)
...
+      theFuture.setException(new IllegalStateException("Server is shutting down."));
+    }
+  }
+
   /**
    * Add batch of segment changes update.
    */
   public synchronized void addChangeRequests(List<T> requests)
   {
+    if (singleThreadedExecutor.isShutdown()) {
```
Comment (rohangarg) [inline server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java:94]: should this also throw an exception - since otherwise the caller might never know that the operation is illegal

File: server/src/test/java/org/apache/druid/server/coordination/ChangeRequestHistoryTest.java [hunk 3]
```diff
@@ -171,4 +172,48 @@ public void testNonImmediateFuture() throws Exception
...
+        }
+    );
+
+    history.stop();
+    // any new change requests should be ignored, there should be no waiting futures, and open futures should be resolved
+    history.addChangeRequest(new SegmentChangeRequestNoop());
+    Assert.assertEquals(0, history.waitingFutures.size());
+    Assert.assertTrue(callbackExcecuted.get());
+    Assert.assertTrue(future.isDone());
+    try {
```
Comment (rohangarg) [inline server/src/test/java/org/apache/druid/server/coordination/ChangeRequestHistoryTest.java:211]: maybe can use `Assert.assertThrows`

**Review by rohangarg — COMMENTED** [review]
Nice find! :+1: 
Some minor comments

File: server/src/main/java/org/apache/druid/server/coordination/ChangeRequestsSnapshot.java (hunk 1 above)
Comment (clintropolis) [reply server/src/main/java/org/apache/druid/server/coordination/ChangeRequestsSnapshot.java:46]: oops, yes this isn't used, was experimenting with different ways to handle shutdown, either failing the future or sending a "successful" shutdown, this is the latter, I'll remove it

File: server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java (hunk 2 above)
Comment (clintropolis) [reply server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java:94]: does it matter since the server is shutting down?

File: server/src/test/java/org/apache/druid/server/coordination/ChangeRequestHistoryTest.java (hunk 3 above)
Comment (clintropolis) [reply server/src/test/java/org/apache/druid/server/coordination/ChangeRequestHistoryTest.java:211]: heh, I wasn't sure how to test the exception message, but I see now that `assertThrows` actually returns the thrown exception, will adjust, thanks :+1:

File: server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java (hunk 2 above)
Comment (rohangarg) [reply server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java:94]: I thought this method could end up being called from a `HttpLoadQueuePeon` API request (`/changeRequests`), so would be better if we can return the correct status/error to it as soon as possible. wdyt?

Comment (clintropolis) [reply server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java:94]: it can, but I guess my thoughts are that it doesn't matter since the `HttpLoadQueuePeon` is stopped by the server disappearing from discovery, so it seemed better to silently ignore because its going down anyway and to avoid any extra log spam and not have potentially multiple shutdown paths on the `HttpLoadQueuePeon` side (same reason I opted to go with failing the future with exception instead of a successful "im shutting dowm" response).

**Review by gianm — APPROVED** [review]

File: server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java (hunk 2 above)
Comment (rohangarg) [reply server/src/main/java/org/apache/druid/server/coordination/ChangeRequestHistory.java:94]: Thanks for the clarification - letting all shutdowns being managed by the discovery makes sense to me!

**Review by rohangarg — APPROVED** [review]
